### ISSUE TITLE
Some WI e2e tests don't work in cluster with latest GKE version

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1000]
**Describe the bug**
Some WI e2e tests don't work in cluster with latest GKE version (1.15.11-gke.11) (it works in 1.15.11-gke.9), this causes the e2e-wi-tests fail and blocks PR. 

 **Expected behavior**
WI e2e tests all pass.

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative-GCP release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by grac3gao** [comment]
Now, we skip these test. StorageSource and AuditlogSource

**Comment by grantr** [comment]
Add a comment next to the skips pointing back to this issue. Let's keep it open until the failure is fixed in the latest GKE version.

**Comment by grac3gao** [comment]
We specified gke version 1.15.11-gke.9 now for the e2e-wi-test
