### ISSUE TITLE
Change the service account when running prow e2e tests from superpower service account to service account with only permissions knative-gcp needed 

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#1021]
**Problem**
Currently, when we run E2E tests in prow, we use a superpower service account.
However, when user uses knative-gcp, usually the control plane service account will only have roles https://github.com/google/knative-gcp/blob/master/docs/install/authentication-mechanisms-gcp.md listed here and the data plane service account will only have the roles https://github.com/google/knative-gcp/blob/master/docs/install/pubsub-service-account.md.
When we use a superpower service account to run the E2E tests in prow, sometimes we may fail to catch some bugs related to authentication.

Therefore, we need to change the service account when running prow e2e tests from superpower service account to service account with only permissions knative-gcp needed. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
The service account we use when running E2E tests in prow should only have the permissions listed in https://github.com/google/knative-gcp/blob/master/docs/install/authentication-mechanisms-gcp.md  and https://github.com/google/knative-gcp/blob/master/docs/install/pubsub-service-account.md

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grac3gao** [comment]
Put a summary for the permission I used to conclude:

For brokerGSA:
roles/pubsub.editor. (For basic broker functionality, needed in both Secret mode and WI mode)
roles/monitoring.metricWriter (For metric in WI mode, Secret mode doesn’t need it)
roles/cloudtrace.agent (For tracing in WI mode, Secret mode doesn’t need it)

For controlGSA:
roles/pubsub.editor (for CloudPubSubSource, Pullsubscription and Topic)
roles/storage.admin (for CloudStorageSource)
roles/cloudscheduler.admin (for CloudSchedulerSource)
roles/pubsub.admin, roles/logging.configWriter, roles/logging.privateLogViewer (for CloudAuditLogsSource)
roles/pubsub.subscriber (for CloudBuildSource)

For sourceGSA:
roles/pubsub.editor. (For basic source functionality)
roles/monitoring.metricWriter (For metric in WI mode, Secret mode doesn’t need it, but we disable custom metrics currently)
roles/cloudtrace.agent (For tracing in WI mode, Secret mode doesn’t need it)

**Comment by capri-xiyue** [comment]
We encountered some quota limits issue when running e2e tests.
Based on the discussion in https://github.com/google/knative-gcp/pull/1574.
It looks we should not change the logic in our source code since this e2e test failure issue is kind of related to how we run prow e2e tests.
Is it possible that knative-gcp has its own service account which belongs to knative-gcp specific prow project so that we don't need to share quota with other teams?
