### ISSUE TITLE
Provide a troubleshooting doc for workload identity

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1030]
**Problem**
When reconciling Workload Identity, and having errors, users can refer to a link which provides explanations and solutions for most of the errors.  

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
Having a troubleshooting doc for workload identity

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by akashrv** [comment]
P1 (R1): External documentation. Add to preview guide and work with tech writers to have pubic documentation.
P1(R1): TSE doc
P2 (R1): Link in status message

**Comment by grac3gao** [comment]
This one should be split into two

- [ ] non-default user experience troubleshooting (can start now)

- [ ] default user experience troubleshooting (need a decision for that)

**Comment by grantr** [comment]
First part is 1-2 days, second part is more complicated.

**Comment by grac3gao** [comment]
troubleshooting is in Knative-GCP repo, will open separate issue for public documentation with tech writter
