### ISSUE TITLE
Figure out what the user experience should be regarding the missing or switch of the data plane authentication.

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#1051]
**Problem**
Currently for sources, it's not easy to switch data plane authentication when the sources are in use. For scenario as follows:
1. User enables Workload Identity and user doesn't install any Kubernetes secret related to data plane authtication
2. User create sources without `spec.googleServiceAccount`
3. The source will get stuck in `Revision Missing` stage. 
4. User manually edit the yaml of the source to add `spec.googleServiceAccount` and delete the default `sepc.Secret`
5. The source will still get stuck in `Revision Missing` stage. 
 In this scenario, user will have to delete the source and re-create the source with spec.googleServiceAccount.

And the behavior regarding the switch of data plane authentication of among difference resources are different.
For example, GCP Broker supports switch of data plane authentication  but currently user needs to restart the GCP Broker controller pod to achieve that. But for Sources, the behavior is different.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
Clearly define what user experience should be regarding the missing or switch of the data plane authentication for both GCP Broker and GCP Sources.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grac3gao** [comment]
The cause for this source behavior is: though source got reconciled, the underlying publisher and receive-adaptor KSVC doesn't restart. Thus, they still use the old way to take credentials. User have to restart underlying KSVCs.

**Comment by capri-xiyue** [comment]
@grac3gao  What do you mean by restart underlying KSVCs? Can you show the command? I tried to restart ksvc with 
`kubectl delete pods cre-cloudauditlogssource-test-publish` but it still doesn't work.

**Comment by grac3gao** [comment]
@capri-xiyue KSVC is the knative Service, publisher and reciever-adaptor are using KSVC as deployment. use `kubectl get ksvc` to find them.

**Comment by grac3gao** [comment]
@capri-xiyue's comments from another thread: 

> Another concern is that the user experience. Currently, if users want to use sources with Workload Identity, however, somehow users forget to add the spec.googleServiceAccount. The source will get stuck in Revision Missing stage. It looks like currently users have to delete the source and re-create the source again.

**Comment by capri-xiyue** [comment]
I wrote a typo. I deleted all ksvcs but it still doesn't work. Can you try whether that works in your clsuter. I think `cre-cloudauditlogssource-test-publish` is the ksvc you mentioned.

**Comment by grantr** [comment]
@Harwayne will take a look at this one

**Comment by grac3gao** [comment]
@capri-xiyue I realized that the serviceAccount is taken all the way down from source to topic/pullsubscription, then finally to KSVCs. So in this case, source is reconciled, but topic and pullsubscription stay the same (they don't take the serviceAccount in), so it can't pass the serviceAccount to the publisher and receive-adaptor pod. Thus, it is topic/pullsubscription need to be deleted. I tried this, by deleting topic, and it works.

**Comment by nachocano** [comment]
Seems like we should make this immutable. Users shouldn't change from WI to Secret.
Anyway, this will change due to recent conversations, but we should probably don't allow editions... Just delete and re-create

**Comment by liu-cong** [comment]
Action items:
* Double check the immutable setting and figure our why it doesn't work

**Comment by liu-cong** [comment]
For GCP broker, we should investigate what the UX is.
 *  we probably should add WI configuration to brokerce ll spec.

**Comment by nachocano** [comment]
@grac3gao can you take a look at this one and see if it's still an issue?

**Comment by grac3gao** [comment]
@nachocano serviceAccountName is one of the immutable fields in `CheckImmutableFields` function (secret is also an immutable fields), theoretically, once they have set,  they will not change. User have to delete and re-create source if they want to change them

However, I tested sources today with latest branch, it seems all immutable fields are not 'immutable'.  Use storage Bucket as an example, if I changed the bucket name, and re-apply the yaml, it will successfully rewrite bucket (but bucket is also an immutable fields, and our UT can catch the immutable field check failures for the bucket). 

I was wondering if we can have more investigation for this immutable problems (not sure if #1448 is referring to this?)

**Comment by nachocano** [comment]
Yes, it refers to that. 
While promoting things to v1, CheckImmutable stuff was outdated. I asked to update it, but wanted to make sure it was working. 
I recall Ville fixed a nasty bug in eventing. Let me find it... I think is because of the multiple versions thing, that we need to call stuff manually...

**Comment by grac3gao** [comment]
@nachocano thanks! If we fixed that multiple versions thing for immutable issue, I think this one would not be an issue. (We just make those authentication immutable, then no switching is allowed in this case)

**Comment by nachocano** [comment]
Sounds good. Yes, I think we have an ugly bug when we introduced v1beta1... Updated comment here: https://github.com/google/knative-gcp/issues/1448 
We will have to do this also for v1, fyi @danyinggu

**Comment by capri-xiyue** [comment]
We can close this issue since we have decided that switch of the data plane authentication is not allowed and we created this issue https://github.com/google/knative-gcp/issues/1448 to fix the immutability problem
