### ISSUE TITLE
Investigating WI behavior without serviceAcountAdmin role 

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1052]
**Problem**
Due to security concerns, now investigating approaches to remove project-wide serviceAcountAdmin role given for the controller GSA to perform WI.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment]
@Harwayne will look into the product implications of this change.
