### ISSUE TITLE
Replace static Broker deployments and service with a static BrokerCell

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1054]
Until #867 is resolved, we can replace the deployments and services declared as yaml in `config/broker` with a BrokerCell, also declared as yaml. This will have the same result but helps test the BrokerCell code.

 **Exit criteria**
Shared deployments and services are managed by a BrokerCell declared as yaml in config/broker, or a fix for #867

**Comment by liu-cong** [comment]
Now #867 is a high priority, we may not need to work on this one any more.

**Comment by liu-cong** [comment]
Closing since we are working on #867
