### ISSUE TITLE
Controller probes broker data plane for pubsub readiness

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#1058]
**Problem**
The data plane may not be ready for a Broker even if the controller says ready.
* The `targets-config` volume may not be updated for whatever reason
* Pub/Sub may be temporarily unavailable
* There could be an auth issue preventing access to Pub/Sub

We need probes (not the K8s probes) from the Controller to the data plane components to more accurately tell if a Broker is ready or not.
Checking the configmap volume consistency is tricky when there are multiple pods.  This issue focuses on checking pubsub readiness instead. 
If there is an issue with pubsub(due to auth or simply pubsub outage), it's likely to impact all pods. We can have a readiness probe that checks if any data plane pods fails to communicate with pubsub.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
* Controller probes data plane readiness
* Write an e2e test that simulates data plane error and verify Broker is not ready

**Additional context (optional)**
* The data plane components (ingress/fanout/retry) should provide a readiness endpoint per Broker
* As part of the readiness check, the data plane can
  ~~* Check the config for the requested Broker exists~~
  * Do a read operation on PubSub (e.g., read Topic) to verify communication with PubSub

cc @capri-xiyue

**Comment by grantr** [comment]
Related to #743 

I think this is fairly complex since the data plane may be serviced by several pods in multiple states of readiness. How many pods must be (un)ready for the Broker to be (un)ready?

**Comment by liu-cong** [comment]
We could reduce the scope of the readiness check to only checking the auth setup. If there is an issue with auth, it's likely a global failure for all data plane pods. Therefore checking the auth of a single pod might be sufficient.

**Comment by liu-cong** [comment]
We can use [TestIamPermissions](https://cloud.google.com/pubsub/docs/reference/rpc/google.iam.v1#google.iam.v1.TestIamPermissionsRequest) to check if the data plane has permissions to pubsub resources

**Comment by grac3gao** [comment]
Just add an additional topic related on this:

Broker in wi mode may have 5XX problem. It fail to send event. In ingress pod, it failed to send event to the topic (error showed lack of credentials, and asked the user to do the binding, but we already did the binding). I believe the cause is https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#limitations 
> The GKE Metadata Server takes a few seconds to start to run on a newly created pod. Therefore, attempts to authenticate or authorize using Workload Identity made within the first few seconds of a pod's life may fail. Retrying the call will resolve the problem.

The solution for this issue could also help to avoid the above issue.

**Comment by grantr** [comment]
@grac3gao Just to confirm I understand, the solution you're proposing is to add a retry loop around any usage of the metadata server?

**Comment by grac3gao** [comment]
@grantr Oh no, sorry, I didn't explain clearly. I mean if we probe broker data plane for pubsub readiness, it could also help to solve the 5XX error. (I didn't mean to add the retry loop, the quote is just for showing what the specific limitation is).  TestIamPermissions which Cong mentions is a good idea.
