### ISSUE TITLE
Implement broker retry spec 

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1072]
**Problem**
There are known cases like: if a Knative function was throwing 500 errors, it will infinitely retry until the message expired from the topic, and users can’t drop it during that time, causing the log full of this error message.

In such case, Broker retry needs to figure out ways to handle it gracefully.

Possible Solutions:
1. Rely on cloud event SDK to handle response
2. Check if response code is retriable or not (difference between 400 and 500)
3. Clear application guidance for users to return error code

We can also check deadLetterQueue design in Knative Eventing for more ideas.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by yolocs** [comment]
My understanding of the problem:

With today's CE Go SDK, as long as an event consumer returns an error, the event will acked and retried later. This is not ideal for broker because if a consumer cannot handle an event (and thus return an error), the broker will retry infinitely.

This problem cannot be easily solved on the CE SDK level. To support different protocol, CE SDK can only provides ack or nack as responses to upstream. It doesn't differentiate retryable errors vs. non-retryable.

One option is to have application not to return error even if it cannot handle the event. This is less ideal because the event will be silently dropped. The better solution is dead letter queue (e.g. after certain num of retries, an event will be dead-lettered). But it still incurs that num of unnecessary retries.

It would be ideal if (maybe somehow via CE SDK) we can have knobs to put/retrieve HTTP status code so that we can identity if an error is retryable or not. This would probably require a wider discussion in CE and Eventing working groups.

**Comment by yolocs** [comment]
@akashrv @grantr @liu-cong 

@Harwayne since this is related with event delivery.

**Comment by grantr** [comment]
I've added https://github.com/knative/eventing/issues/2411 to the Delivery WG agenda for next week.

**Comment by grantr** [comment]
Here's the [delivery spec in Knative Eventing](https://github.com/knative/eventing/blob/a34a96f2c953fac85bdbf539e035969f59157b8b/pkg/apis/duck/v1beta1/delivery_types.go#L29-L51):

```go
// DeadLetterSink is the sink receiving event that could not be sent to
// a destination.
// +optional
DeadLetterSink *duckv1.Destination `json:"deadLetterSink,omitempty"`

// Retry is the minimum number of retries the sender should attempt when
// sending an event before moving it to the dead letter sink.
// +optional
Retry *int32 `json:"retry,omitempty"`

// BackoffPolicy is the retry backoff policy (linear, exponential).
// +optional
BackoffPolicy *BackoffPolicyType `json:"backoffPolicy,omitempty"`

// BackoffDelay is the delay before retrying.
// More information on Duration format: https://www.ietf.org/rfc/rfc3339.txt
//
// For linear policy, backoff delay is the time interval between retries.
// For exponential policy , backoff delay is backoffDelay*2^<numberOfRetries>.
// +optional
BackoffDelay *string `json:"backoffDelay,omitempty"`
```

And here's GCP pubsub's (experimental) retry policy and dead letter policy fields on subscriptions. Note that RetryPolicy is [currently marked as experimental where it's used](https://github.com/googleapis/googleapis/blob/247c6514750a2cfca836d946c4e008ca1a5fd1d1/google/pubsub/v1/pubsub.proto#L701-L704), while [DeadLetterPolicy is not](https://github.com/googleapis/googleapis/blob/247c6514750a2cfca836d946c4e008ca1a5fd1d1/google/pubsub/v1/pubsub.proto#L684-L692).

```proto
message RetryPolicy {
  // The minimum delay between consecutive deliveries of a given message.
  // Value should be between 0 and 600 seconds. Defaults to 10 seconds.
  google.protobuf.Duration minimum_backoff = 1;

  // The maximum delay between consecutive deliveries of a given message.
  // Value should be between 0 and 600 seconds. Defaults to 600 seconds.
  google.protobuf.Duration maximum_backoff = 2;
}

// Dead lettering is done on a best effort basis. The same message might be
// dead lettered multiple times.
//
// If validation on any of the fields fails at subscription creation/updation,
// the create/update subscription request will fail.
message DeadLetterPolicy {
  // The name of the topic to which dead letter messages should be published.
  // Format is `projects/{project}/topics/{topic}`.The Cloud Pub/Sub service
  // account associated with the enclosing subscription's parent project (i.e.,
  // service-{project_number}@gcp-sa-pubsub.iam.gserviceaccount.com) must have
  // permission to Publish() to this topic.
  //
  // The operation will fail if the topic does not exist.
  // Users should ensure that there is a subscription attached to this topic
  // since messages published to a topic with no subscriptions are lost.
  string dead_letter_topic = 1;

  // The maximum number of delivery attempts for any message. The value must be
  // between 5 and 100.
  //
  // The number of delivery attempts is defined as 1 + (the sum of number of
  // NACKs and number of times the acknowledgement deadline has been exceeded
  // for the message).
  //
  // A NACK is any call to ModifyAckDeadline with a 0 deadline. Note that
  // client libraries may automatically extend ack_deadlines.
  //
  // This field will be honored on a best effort basis.
  //
  // If this parameter is 0, a default value of 5 is used.
  int32 max_delivery_attempts = 2;
}
```

**Comment by grantr** [comment]
P1: don't retry immediately forever
P2: full retry specification

**Comment by markfisher** [comment]
I'm also interested in this from the perspective of the RabbitMQ Broker. Like the GCP DeadLetterPolicy @grantr shared above, RabbitMQ also provides internal support for a Dead Letter Exchange: https://www.rabbitmq.com/dlx.html

**Comment by liu-cong** [comment]
Capturing some discussion notes:
* We could use pubsub deadletter configuration
* This could be a per-broker configuration

**Comment by liu-cong** [comment]
Unknowns:
* how to translate DeadletterSink to pubsub topic
* unclear if pubsub backoff policy fully supports knative delivery spec

**Comment by grantr** [comment]
@tommyreddad asked offline about default. My preference for defaulting is setting a default BackoffPolicy and BackoffDelay in SetDefaults. That simplifies the default handling code in the controller and shows the user how to use the policy fields. We don't need to set defaults for DeadLetterQueue or Retry.

A future enhancement could create a configmap that allows a cluster admin to modify these defaults for all brokers in the cluster. I created #1516 for this.

**Comment by tommyreddad** [comment]
FYI: I did a quick investigation of the pubsub exponential backoff retry behaviour. Currently, it appears that the exponential factor in retry delay tends to be less than 2, and closer to roughly 1.3. See the attached plots for the measured empirical backoff delay using pubsub's retry policy with two settings, one with MinimumBackoff=1ms, and one with MinimumBackoff=2s.

![backoff 1ms 10m](https://user-images.githubusercontent.com/12170323/88584708-0fc01980-d020-11ea-87a6-70bc634b79a0.png)

![backoff 2s 10m](https://user-images.githubusercontent.com/12170323/88584722-164e9100-d020-11ea-9ffb-8242cfc2e0ab.png)
