### ISSUE TITLE
GCP Broker installation strategy

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#1077]
**Problem**
Define the deployment experience of GCP Broker for next release.

Right now GCP Broker data plane is a static deployment by YAML, and the YAML is a separate installation in addition to standard knative-gcp installation to avoid idle resource usage.
So the question is:   Should there be a separate manual installation step for the GCP Broker data plane?

## Option 1: Separate installation (current behavior)
* Users need to manually install GCP Broker data plane before they can use GCP Broker
* As part of that, they need to pick an auth mechanism, K8s secret or WI

## Option 2: Single installation
Users install Knative-GCP only once, and GCP Broker is ready to use. By default, GCP Broker data plane should use the same auth mechanism as the controller plane. 

### 2-a with idle resource usage
This is straightforward. We just need to include the GCP data plane yaml in the standard installation. To mitigate idle resource, we could use ksvc for the ingress.

### 2-b: no idle resource usage
Only run the data plane when there is at least one Broker. This requires changes in Broker or BrokerCell controller. The controller should also be aware of the auth mechanism that's chosen. This would be a "static" configuration in the controller, maybe as an env var.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
We have to first reach an agreement on which strategy to use. It's likely we need to break this down to sub issues.

**Comment by grantr** [comment]
My preference order is:
1.  2-b
2. 1
3. 2-a

2-a seems problematic since it creates 3 pods that do nothing if the operator only wants to use a source and doesn't intend to use the GCP broker.

#867 tracks the implementation of 2-b.

**Comment by grantr** [comment]
We'll go with 2b for now
