### ISSUE TITLE
TestFanoutSyncPoolE2E Helper Goroutines Never Exit

### ISSUE THREAD

**Issue by ian-mi** [google/knative-gcp#1085]
**Describe the bug**
Some TestFanoutSyncPoolE2E Helper Goroutines never exit. For example, in test "event with delivery timeout was sent to retry queue" the call to helper.VerifyNextTargetRetryEvent is meant to verify that an event is sent to the retry queue: https://github.com/google/knative-gcp/blob/master/pkg/broker/handler/pool/fanout_test.go#L212. However this call will block forever when no event is sent to the retry queue hiding a bug with the delivery timeout.

 **Expected behavior**
Test helpers either fail or succeed before the test is finished.

**Comment by akashrv** [comment]
@grantr to follow-up with @ian-mi to figure out priority
