### ISSUE TITLE
Unneeded Topic Connections are Not Cleaned Up By Ingress

### ISSUE THREAD

**Issue by ian-mi** [google/knative-gcp#1118]
**Describe the bug**
The ingress pubsub CE client will retain topics forever. If a broker is deleted the topic connection will die but will not be removed from the topic map.

 **Expected behavior**
When a broker config is removed from targets the corresponding topic connection should be cleanly stopped and removed.

**Comment by grantr** [comment]
@ian-mi to clarify, this is a memory leak in the container, not a GCP resource leak?

**Comment by ian-mi** [comment]
Yes, this will leak a small amount of memory and potentially some amount of additional overhead but is not a resource leak.

**Comment by liu-cong** [comment]
If we continue to use CE pubsub protocol, looks like the `Close` method should be implemented: https://github.com/cloudevents/sdk-go/blob/master/protocol/pubsub/v2/protocol.go#L243

**Comment by ian-mi** [comment]
Implementing close would be useful for closing the entire protocol but would not help for cleaning up individual topic connections.
