### ISSUE TITLE
Fine grained permissions for the Controller GSA

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1119]
**Problem**
We now use some admin roles (like storage admin) to access APIs, we need to figure out exactly which permissions we need, so that the controller didn’t over-grant permissions.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by capri-xiyue** [comment]
Check with CLI regarding the roles we will use if there is any change of the roles.

**Comment by AlexandraRoatis** [comment]
## Controller GSA permissions and their code uses

- `pubsub.subscriptions.create`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/intevents/pullsubscription/reconciler.go#L237
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/intevents/pullsubscription/reconciler.go#L244
- `pubsub.subscriptions.delete`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/intevents/pullsubscription/reconciler.go#L233
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/intevents/pullsubscription/reconciler.go#L279
- `pubsub.subscriptions.get`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/intevents/pullsubscription/reconciler.go#L180
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/intevents/pullsubscription/reconciler.go#L272
- `pubsub.topics.attachSubscription` same as `pubsub.subscriptions.create` since a subscription is attached to a topic when created
- `pubsub.topics.create`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/intevents/topic/topic.go#L171
- `pubsub.topics.delete`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/intevents/topic/topic.go#L214
- `pubsub.topics.get`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/events/auditlogs/auditlogs.go#L152
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/intevents/topic/topic.go#L206
- `pubsub.topics.getIamPolicy`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/events/auditlogs/auditlogs.go#L153
- `pubsub.topics.setIamPolicy`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/events/auditlogs/auditlogs.go#L159
    - The Cloud Logging API is called to create a new sink with a [unique writer identity](https://cloud.google.com/logging/docs/api/tasks/exporting-logs#using_a_unique_writer_identity) (i.e. newly generated GSA). We then use this permission to [associate the new GSA with the destination Pub/Sub Topic](https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/events/auditlogs/auditlogs.go#L157-L166) that the sink (using the GSA identity) will write to.
- `storage.buckets.get`
    - https://github.com/google/knative-gcp/blob/632e6ca2b464bfa1004cbdd2b1ed9035d5df041b/pkg/reconciler/events/storage/storage.go#L197
    - https://github.com/google/knative-gcp/blob/632e6ca2b464bfa1004cbdd2b1ed9035d5df041b/pkg/reconciler/events/storage/storage.go#L130
- `storage.buckets.update`
    - https://github.com/google/knative-gcp/blob/632e6ca2b464bfa1004cbdd2b1ed9035d5df041b/pkg/reconciler/events/storage/storage.go#L141
    - https://github.com/google/knative-gcp/blob/632e6ca2b464bfa1004cbdd2b1ed9035d5df041b/pkg/reconciler/events/storage/storage.go#L162
    - https://github.com/google/knative-gcp/blob/632e6ca2b464bfa1004cbdd2b1ed9035d5df041b/pkg/reconciler/events/storage/storage.go#L211
    - https://github.com/google/knative-gcp/blob/632e6ca2b464bfa1004cbdd2b1ed9035d5df041b/pkg/reconciler/events/storage/storage.go#L223
- `cloudscheduler.jobs.create`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/events/scheduler/scheduler.go#L126
- `cloudscheduler.jobs.delete`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/events/scheduler/scheduler.go#L168
- `cloudscheduler.jobs.get`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/events/scheduler/scheduler.go#L114
- `logging.sinks.create`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/events/auditlogs/auditlogs.go#L136
    - also used in tests
- `logging.sinks.delete`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/events/auditlogs/auditlogs.go#L182
    - also used in tests
- `logging.sinks.get`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/events/auditlogs/auditlogs.go#L124
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/reconciler/events/auditlogs/auditlogs.go#L139
    - also used in tests
- `resourcemanager.projects.get`
    - occasionally used in the projects running the e2e tests
    - https://github.com/google/knative-gcp/blob/b4692adf21e5cc02b5a59d42061db6987686cb80/pkg/utils/metadata.go#L59
    - according to [IAM permissions for the Google Cloud Console](https://cloud.google.com/storage/docs/access-control/iam-console) this permission is necessary to perform actions involving buckets when using the Cloud Console

## Data Plane GSA permissions and their code uses

- `pubsub.subscriptions.consume`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/broker/handler/handler.go#L76
- `pubsub.subscriptions.get`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/broker/handler/fanout.go#L152
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/broker/handler/retry.go#L131
- `pubsub.topics.get`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/broker/ingress/multi_topic_decouple_sink.go#L128
- `pubsub.topics.publish`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/pkg/broker/ingress/multi_topic_decouple_sink.go#L89
- `resourcemanager.projects.get`
    - https://github.com/google/knative-gcp/blob/b4692adf21e5cc02b5a59d42061db6987686cb80/pkg/utils/metadata.go#L59
- `monitoring.timeSeries.create`
    - https://github.com/google/knative-gcp/blob/0f98edcf37c911c5b75f8f171169deb3528d5830/test/lib/metrics/stackdriver.go#L79
- `cloudtrace.traces.patch`
    - https://github.com/google/knative-gcp/blob/9b9bde18923ad2f6e731ad3c66825ad420cbb4be/vendor/contrib.go.opencensus.io/exporter/stackdriver/trace.go#L151
    - https://github.com/google/knative-gcp/blob/9b9bde18923ad2f6e731ad3c66825ad420cbb4be/vendor/google.golang.org/genproto/googleapis/devtools/cloudtrace/v2/tracing.pb.go#L285
