### ISSUE TITLE
Make sure that sources track their sinks

### ISSUE THREAD

**Issue by n3wscott** [google/knative-gcp#112]
Consider turning this into an issue. Something about status of sinks might not get reflected, there might be issues with this on error conditions.

Consider turning this into an issue. Something about status of sinks might not get reflected, there might be issues with this on error conditions.

_Originally posted by @vaikas-google in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MjY4MDUyNjQy/pull_request_reviews/more_threads_

**Comment by akashrv** [comment]
@n3wscott @vaikas-google Is this alpha blocker? Could we add more details to description?

**Comment by vaikas-google** [comment]
Well, this sure seems like a github fail. Clicking on that link does not work.
As far as I can decode from the bits here, I'd reckon that we should make sure that Sources will set up trackers for their Sinks to reflect their status and be notified of their state changes. I'd expect there to be a corresponding TODO in the code base.

**Comment by akashrv** [comment]
Yes, I found a todo in channel reconciler. But I think when we pick this issue, we should look at all sources and make sure that they track their sinks. 
Example: If a source targets a CR service and I delete the service or the service status goes Ready=False, then the source status should reflect that in control plane.
As @n3wscott and @vaikas-google have been actively adding sources here, you could take care of this for newer sources.
I am updating the title of this issue. This is a beta blocker and we should take care of this sooner than later.
