### ISSUE TITLE
Logs visible in StackDriver - Manual Verification

### ISSUE THREAD

**Issue by Harwayne** [google/knative-gcp#1148]
**Exit Criteria**
Manually verify that the following logs are visible in StackDriver:
- Knative Eventing control plane
- cloud-run-events control plane
- GCP Source receive adapters
- GCP Broker pieces

**Comment by Harwayne** [comment]
Logs are visible in the [Cloud Console](https://console.cloud.google.com/logs/viewer) under `Kubernetes Container` -> Cluster Name -> Namespace Name -> Pod Name prefix.

**Comment by bharattkukreja** [comment]
Verified the logs for knative-eventing, cloud-run-events, GCP broker pieces and cloudpubsubsource (logs attached).

[logs-verification.zip](https://github.com/google/knative-gcp/files/4892564/logs-verification.zip)
