### ISSUE TITLE
PullSubscription names should be more "readable" 

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#1155]
**Problem**

We currently set up the PS names to be `cre-pull-<UID>`... However, it is hard to debug which Source this PS belongs to (unless you inspect the annotations). 
We should do something similar as the new GCP broker does:

A source named "mysource" in the default namespace:

cre-src_default_mysource_08029893-c749-4041-aaef-519f0c6ebad4
 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
Developer

**Exit Criteria**
A more descriptive name for PS

**Time Estimate (optional):** 
1d

**Comment by grantr** [comment]
Something to think about as we implement this is how to evolve resource name formats. As the resource names change controllers will need to recognize the older and newer names. Maybe we can add some kind of version identifier to the name, like `cre-src1`, to make the names uniquely identifiable as a particular format. But I haven't fully worked out the details.

**Comment by grantr** [comment]
This seems to be low effort if we ignore the effort of upgrading existing objects. We should also do any other resources with similar naming schemes.
