### ISSUE TITLE
Test deletion of gcp broker also deletes GCP resources

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#1165]
Problem
We need to verify gcp broker get created and get deleted correctly
For example, when we delete a gcp broker, all the underlying pull subscriptions and topic etc. should also get deleted

Persona:
Which persona is this feature for?

Exit Criteria
Smoke Testing for gcp broker

Time Estimate (optional):
How many developer-days do you think this may take to resolve?

Additional context (optional)
Add any other context about the feature request here.

**Comment by grantr** [comment]
Fixed by #1161
