### ISSUE TITLE
E2E tests and Reconciler should use v1beta1 APIs

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#1168]
**Problem**
We should change the E2E tests to use v1beta1 APIs instead of the v1alpha1 versions

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Contributor

**Exit Criteria**
Reconciler, UT, E2E Tests with v1beta1

**Comment by capri-xiyue** [comment]
I did some investigation of this issue. E2E tests uses some helper methods that shared between both unit tests and e2e tests. If we want to change E2E tests to use v1beta1 APIs, we also need to change the reconciler and unit tests. Therefore, the storypoints should be higher than 2 considering the workload of changing source code, relevant unit tests and e2e tests

**Comment by capri-xiyue** [comment]
Synced with Nacho, we both think this is a good first issue for Danying. Danying is also interested in this issue and she will pick it up later.

**Comment by capri-xiyue** [comment]
blocked by https://github.com/google/knative-gcp/pull/1244 and another relevant WI PR against UT

**Comment by grac3gao** [comment]
#1249 and #1244 shall unblock it now.
