### ISSUE TITLE
Shall Finalizer mark resource sub-conditions when it failed?

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1190]
**Problem**
In FinalizeKind (sources and broker). When deleting resources, we only return error without marking corresponding status failed (showing reasons like SubscriptionDeleteFailed). Thus, when users are trying to delete a resource and got stuck, they can’t track the reason through resource (resource still show ready is true if the last reconciling loop for it is true). 

Note: by checking kubectl describe, it will show a related warning event for that

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment]
It might not be possible to update the status of a finalized resource. If not, we could emit an event for this case.

@grac3gao do you have any specific examples of issues with blocked finalized objects?

**Comment by grac3gao** [comment]
According to the discussion in Eventing WG and issue https://github.com/knative/eventing/issues/3305
it is worthwhile to mark conditions in Finalizer. This issue will track the broker/trigger finalizer. #1294 is used to track finalizer in source and channel
