### ISSUE TITLE
Allow to set both the KSA and the secret via the defaulting mechanism

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1216]
**Problem**
With the review in https://github.com/google/knative-gcp/pull/1214#pullrequestreview-424659736, 

> I think we will eventually want users to be able to set both the KSA and the secret via the defaulting mechanism. But, it is easier to add that feature later rather than remove it. So let's do this for now and if a user asks to default both, we can add the capability then.

currently, we only set either of two in defaulting mechanism. If users ask, we can try and make it possible to use both in the future. (Users may want to use serviceAccoutName for things other than WI)

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

cc @Harwayne

**Comment by nachocano** [comment]
@grac3gao is this still an issue?

**Comment by capri-xiyue** [comment]
@grac3gao  Is this still an issue or we can close it?

**Comment by grac3gao** [comment]
Sorry I didn't notice to reply this thread! @nachocano @capri-xiyue 
I think this issue is just used to track an open question (we are not sure if the users want the `serviceAccountName` field to do other things rather than authentication). We might do some work once the user have such request, but now, we don't need to do that.
We can probably let it open with a low priority only for tracing purpose.
