### ISSUE TITLE
Broker ingress HPA doesn't scale up when qps exceeds 5000

### ISSUE THREAD

**Issue by yolocs** [google/knative-gcp#1254]
When ingress qps exceeds ~5000, ingress pods will constantly be killed by OOM. This seems to happen before memory metrics can be updated so that HPA won't scale it up. Liveness probe failure also occurs from time to time with this qps.

**Comment by grantr** [comment]
P1 for R2: Document limits and keep the pod from crashing

**Comment by yolocs** [comment]
With further investigation, more concrete issues (e.g. https://github.com/google/knative-gcp/issues/1548, https://github.com/google/knative-gcp/issues/1550) are replacing this issue.

https://github.com/google/knative-gcp/issues/1552 should cover a scale we want to support (by the default setup).
