### ISSUE TITLE
 We shouldn't be duplicating all this constants nor the methods for annotations

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#1274]
**Problem**
 We shouldn't be duplicating all this constants nor the methods for annotations. Maybe we should move it outside the v1alpha1 and v1beta1 packages.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
No duplicate constants or methods for annotations

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by Harwayne** [comment]
This internal package is used by a different portion of the apis: https://github.com/google/knative-gcp/blob/master/pkg/apis/messaging/internal/constants.go

**Comment by nachocano** [comment]
This is a good first issue. Maybe @danyinggu can take a look whenever she gets some cycles?

**Comment by danyinggu** [comment]
Sounds good thanks @nachocano, I might need to start it for next sprint because I already have issues working on for this sprint.

**Comment by nachocano** [comment]
> Sounds good thanks @nachocano, I might need to start it for next sprint because I already have issues working on for this sprint.

Yes, that's completely fine. This is a cleanup not needed for this sprint. I'll move it to next

**Comment by nachocano** [comment]
Synced offline with @danyinggu. 

We agreed to make a first pass and move the annotations and the credentials duplicated constants and methods under duck v1alpha1 and v1beta1 to new files under duck
The constants will go in duck/register.go
The default methods will go in duck/defaults.go
And validation stuff in duck/validations.go

We can then revisit whether this is the right place or not. At least it matches more of what eventing has, and we avoid duplicating stuff all over

**Comment by danyinggu** [comment]
Thank you for the comment @nachocano !
