### ISSUE TITLE
Marking source and channel sub-conditions in Finalizer

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1294]
**Problem**
With https://github.com/google/knative-gcp/issues/1190 and https://github.com/knative/eventing/issues/3305, it would be nice if we mark source and channel sub-conditions when resource deletion returns error.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by nachocano** [comment]
@danyinggu this one is a good first issue as well

**Comment by danyinggu** [comment]
@nachocano Thanks Nacho! I will start to work on it after finishing the work on this sprint 👍

**Comment by nachocano** [comment]
Let's sync with @grac3gao to see if we can move forward with this or we have to bring it up with the open source community. 
Whether we should create a new condition or not.

**Comment by grac3gao** [comment]
In GCP Broker, we didn't add new condition (https://github.com/google/knative-gcp/pull/1295). If it is Subscription deletion failed, we mark condition `subscriptionReconcile` unknown (if the deletion failed it is uncertain wether the topic functionality still there or not), and mark the unknown reason as `FinalizeSubscriptionVerificationFailed `. https://github.com/google/knative-gcp/pull/1295 contains more detailed modification in GCP Broker

**Comment by nachocano** [comment]
Thanks @grac3gao ! I think we should do the same as what we are doing in the GCP broker. No need to bring it to the community (at least for now), we have other bigger fishes to fry. @capri-xiyue let me know if you are OK with this... If not, we can revisit in the next triage.

I'll mark this as a good first issue. 
fyi @bharattkukreja @danyinggu so that it is in your radars, maybe for next sprint

**Comment by danyinggu** [comment]
> Thanks @grac3gao ! I think we should do the same as what we are doing in the GCP broker. No need to bring it to the community (at least for now), we have other bigger fishes to fry. @capri-xiyue let me know if you are OK with this... If not, we can revisit in the next triage.
> 
> I'll mark this as a good first issue.
> fyi @bharattkukreja @danyinggu so that it is in your radars, maybe for next sprint

I reassigned this issue back to myself as I already started looking into it.
