### ISSUE TITLE
Allow limiting max scale of BrokerCell deployments

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1300]
**Problem**
BrokerCell currently hardcodes max scale of all 3 deployments to 10 replicas. In some situations it may be useful to limit this scale, for example performance testing or resource-constrained clusters.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Cluster Admin

**Exit Criteria**
I can set the maximum scale of all deployments when creating or modifying the BrokerCell object.

**Additional context (optional)**
I think it's probably best to have one field for each deployment, but another option is a single field that applies to all deployments.

We may want to later add other fields for deployment tuning, like min scale or resource requests.

If the max scale of a deployment is set to 1, then we can skip creating an HPA for it (or delete the existing HPA).

@nlopezgi this may be required to implement the throughput performance test.

**Comment by Ectelion** [comment]
This has been addressed as part of [PR1379: Add hpa knobs for broker-gcp #1379](https://github.com/google/knative-gcp/pull/1379).
