### ISSUE TITLE
Storage version change causes setDefault failure for v1beta1 resources

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1311]
**Problem**
As a follow-up of https://github.com/google/knative-gcp/issues/1306.
When we use v1beta1 resource, all setDefault() functionality seems don't work. 
This caused default credential not setting up, and annotation not setting up. 

We temporarily fix it by changing back the storage version.
Investigation shows that, in v1beta1, the setDefault() is running, and setting the defaults. However, somehow, it is removed later. 
Suspecting there is some conversion issues.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grac3gao** [comment]
Another direction worth to investigate is the storage version change doesn't affect the e2e test, v1beta1's e2e test are all working.

**Comment by nachocano** [comment]
Might have something to do with k8s version? Maybe e2e run with an older
version?
