### ISSUE TITLE
Don't directly set default in NewFoo style function

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1315]
**Problem**
In `NewFoo` style function, we directly setDefault. 
https://github.com/google/knative-gcp/blob/93dbbbb6c32cb68bbc567d07e030f69a1c98e80f/pkg/reconciler/testing/auditlogs.go#L34-L44

It would be better to separate it as an option. 
In UT, we need to set default for credentials. But in E2E, we wish to rely on default webhook to set credentials (setting default here will make defaulting issues in webhook invisible, like #1310 ).

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

cc @capri-xiyue

**Comment by capri-xiyue** [comment]
Duplicated issue: https://github.com/google/knative-gcp/issues/1316
Danying will work on it.
