### ISSUE TITLE
Add Sources conformance tests

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#1321]
**Problem**
Eventing started with a conformance tests for Sources.
We should add those tests to our Sources.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Contributor, Developer

**Exit Criteria**
Our Sources have conformance tests 

**Additional context (optional)**
https://github.com/knative/eventing/pull/3363

**Comment by capri-xiyue** [comment]
We may need a new prow job for the conformance tests.

**Comment by nachocano** [comment]
Should look at this as well: https://github.com/knative/pkg/issues/1563

**Comment by nachocano** [comment]
and this one: https://github.com/knative/eventing/pull/3719
