### ISSUE TITLE
E2E tests should use CE-SDK v2

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#1336]
**Problem**
We should move the E2E tests to the CE V2. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Contributor

**Exit Criteria**
All E2E tests use CE-SDK v2

**Comment by grac3gao** [comment]
Just add some information here: I am working on #1444, it is switching sender image to use a cev2 client. Now that most of the test images are using knclient https://github.com/google/knative-gcp/tree/master/pkg/kncloudevents., we can change the knclient to use cev2 SDK. There might be some changes in receiver pod after we switch to use cev2 SDK.
