### ISSUE TITLE
Corrupt reply may be dropped

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1362]
**Describe the bug**
Like https://github.com/knative/eventing/issues/3438, GCP broker may be dropping corrupt replies and marking the delivery successful.

I think the relevant lines are https://github.com/google/knative-gcp/blob/ebd932b0fa01e57fbd00ce2fd0070ececc5c70c6/pkg/broker/handler/processors/deliver/processor.go#L156-L159

 **Expected behavior**
If a consumer returns a reply but that reply cannot be parsed or is somehow incomplete,  the delivery is retried.

**Comment by grantr** [comment]
Here's the attempt to fix this in eventing https://github.com/knative/eventing/pull/3450

**Comment by grac3gao** [comment]
This may be the one of the causes for flaky GCP Broker related test:
Sender pod sends the event, however, Target pod doesn't receive that, like this:
```
    TestCloudStorageSourceWithGCPBroker: test_gcp_broker.go:101: timed out waiting for the condition
    TestCloudStorageSourceWithGCPBroker: test_gcp_broker.go:101: resp event didn't hit the target pod
```
The event was dropped during the process: Event sent to a KSVC, and resp Event sent to the target. 

After retuning error message `"unknown encoding` for unknown encoding, I caught up the error like this in brokercell-fanout:
(The Event was sent to the KSVC, and replied back.)
```
{"level":"warn","ts":"2020-07-03T05:55:52.069Z","logger":"broker-fanout","caller":"deliver/processor.go:126","msg":"target delivery failed","commit":"8678614","target":"test-cloud-storage-source-with-g-c-p-broker-c5d2j/gcp-hndtawlx/resp-broker-gcp-hndtawlx","error":"unknown encoding"}
```
Then, it goes to brokercell-retry for several rounds of re-send try with error, and finally got delivered:

```
{"level":"error","ts":"2020-07-03T05:55:52.963Z","logger":"broker-retry","caller":"handler/handler.go:119","msg":"failed to process event; backoff nack","commit":"8678614","eventID":"e2e-testing-resp-event-id-storage","backoffPeriod":1,"error":"Post \"http://storage-e2e-test-kybiwjer-target-xgndfiju.test-cloud-storage-source-with-g-c-p-broker-c5d2j.svc.cluster.local/\": dial tcp 10.19.243.10:80: connect: no route to host","stacktrace":"github.com/google/knative-gcp/pkg/broker/handler.(*Handler).receive\n\tgithub.com/google/knative-gcp/pkg/broker/handler/handler.go:119\ncloud.google.com/go/pubsub.(*Subscription).Receive.func2.2\n\tcloud.google.com/go/pubsub@v1.3.2-0.20200506222144-2c46308f8465/subscription.go:793\ncloud.google.com/go/pubsub/internal/scheduler.(*ReceiveScheduler).Add.func1\n\tcloud.google.com/go/pubsub@v1.3.2-0.20200506222144-2c46308f8465/internal/scheduler/receive_scheduler.go:82"}
```

If we could solve this issue, it might also help to reduce flaky in e2e GCP Broker related test.
