### ISSUE TITLE
gcp-broker not removed from broker-targets after deleting

### ISSUE THREAD

**Issue by rlopez4** [google/knative-gcp#1372]
**Describe the bug**
I have 3 gcp brokers in different namespaces. I deleted 1 and it looks like the pubsub subscription was deleted but the broker-fanout is still polling the broker. The deleted gcp-broker is still listed in the broker-targets configmap and the broker-fanout is logging the following error. 

```json
{"level":"error","ts":"2020-07-01T15:58:05.331Z","logger":"broker-fanout","caller":"pool/fanout.go:164","msg":"handler for broker has stopped with error","commit":"d3ddec0","broker":"spinnaker/gcp-broker","error":"rpc error: code = NotFound desc = Resource not found (resource=cre-bkr_spinnaker_gcp-broker_5b767228-b134-4466-9208-c80797d321c4).","stacktrace":"github.com/google/knative-gcp/pkg/broker/handler/pool.(*FanoutPool).SyncOnce.func2.1\n\tgithub.com/google/knative-gcp/pkg/broker/handler/pool/fanout.go:164\ngithub.com/google/knative-gcp/pkg/broker/handler.(*Handler).Start.func1\n\tgithub.com/google/knative-gcp/pkg/broker/handler/handler.go:59"}
```

 **Expected behavior**
Deleting a gcp-broker would clean up the broker targets

 **To Reproduce**
create 1 gcp-broker in a few different namespaces and delete 1

 **Knative-GCP release version**
v0.15.0

**Comment by grantr** [comment]
@rlopez4 thanks for the report! Are you using the 0.15.0 release, or are you on a more recent nightly or commit? If you're using 0.15.0, this might be fixed in 0.16.0 (which will be released this week).

**Comment by rlopez4** [comment]
@grantr I am currently using 0.15.0. Thanks for the info. I will test against 0.16.0 when it gets released.

**Comment by rlopez4** [comment]
This is still happening in 0.16.0. The pubsub topic no longer exists but it's still listed in the broker-targets configmap. I tried restarting the webhook and controller and that did not help.

**Comment by rlopez4** [comment]
Whoops. I forgot those deployments aren't supposed to be there. It's all broker-cells now. In which case it seems to be working fine as far as I can tell.
