### ISSUE TITLE
Data race detected for TestAdapter/successful_with_no_reply 

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#1374]
**Describe the bug**
See
https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/google_knative-gcp/1356/pull-google-knative-gcp-unit-tests/1278405653475364864

This is the first time I see it. Doesn't seem to happen often.

**Comment by nachocano** [comment]
re-assigning to Ian as he has the fix
