### ISSUE TITLE
Figure out the translation from Knative delivery spec to pubsub policy

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#1392]
Ref #1072

**Problem**
A short explanation of the problem, including relevant restrictions.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by yolocs** [comment]
Here is what I propose.

1. DeadLetterSink - We only allow a special URL as the dead letter sink, e.g. pubsub://[dead_letter_sink_topic]. Our controller will go create that dead letter topic (if not exist) and set up the dead letter topic for the subscription as documented in https://cloud.google.com/pubsub/docs/dead-letter-topics
2. Retry (num of retries before dead letter) - This would be a parameter when setting up the dead letter topic. Notice PubSub has a limitation on the this number (between 5-100)
3. BackoffDelay - This should mapping to `MinimumBackoff` in the PubSub RetryPolicy. I _believe_ PubSub does exponential based on `MinimumBackoff`.
4. BackoffPolicy - If "linear" is specified, we just need to specify `MaximumBackoff` to be the same as `MinimumBackoff` in PubSub RetryPolicy. If "exponential" is specified, we need to do some calculation to make sure `MinimumBackoff * 2^Retry >= MaximumBackoff`. PubSub would do exponential backoff for us.

**Comment by yolocs** [comment]
@liu-cong @grantr @grac3gao @capri-xiyue let me know what you think

**Comment by grantr** [comment]
:+1: @yolocs that's exactly what I was thinking.

It's slightly unfortunate that the user needs to specify a full topic name as the dead letter sink, since that makes Brokers difficult to auto-create with dead letter topics. If we later decide this is a problem, we can add optional defaulting for the DLQ URI to the webhook.

**Comment by grantr** [comment]
https://github.com/knative/eventing/issues/3555 may block implementation of this feature.

**Comment by liu-cong** [comment]
Thanks for the details @yolocs , SGTM!

> since that makes Brokers difficult to auto-create with dead letter topics.

@grantr , can you elaborate on this? Can the broker create the dead letter topic if it doesn't exist and update the pull sub?

On a side note, is dead letter topic special? Do we also need to create a pull sub for the dead letter topic in order to keep messages?

**Comment by yolocs** [comment]
Dead letter topics are not special. I think what @grantr means is that if we require explicit dead letter topic from the user, then auto creating broker with dead letter (e.g. auto inject by labeling namespace) would be difficult to do. We can definitely do defaulting.

**Comment by grantr** [comment]
Sorry for the confusion. @yolocs is correct. I meant that if we want to automate the creation of a default broker in a namespace, we might need defaulting of the dead letter topic name, which unlike the other fields cannot be a static default value. But that is a relatively easy addition in a separate component (the webhook), so the Broker controller doesn't need to worry about this.

**Comment by liu-cong** [comment]
#1072 will implement the recommendations from @yolocs
