### ISSUE TITLE
Clarify the UX of authentication configuration for GCP Broker data plane

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#1393]
**Problem**
Right now the auth configuration of GCP broker data plane is different from sources, we need to investigate if the current behavior is desired.

### GCP Broker data plane
Right now, the GCP broker data plane components uses secret if the a credential file is fount at the GOOGLE_APPLICATION_CREDENTIAL env var, or WI if otherwise. This is similar to how the controllers work.

In secret mode, the name of the secret is hard-coded: https://github.com/google/knative-gcp/blob/c624559b2dd57b56da0556b696cc12806e748021/pkg/reconciler/brokercell/resources/deployments.go#L173

In WI mode, the name of the KSA is set via an env var of the controller, but is basically hard-coded for the user: 
https://github.com/google/knative-gcp/blob/c624559b2dd57b56da0556b696cc12806e748021/pkg/reconciler/brokercell/brokercell.go#L48

Users then need to manually bind the KSA to whatever GSA they want to use.

### Sources
In sources, user can specify a GSA via the `IdentitySpec`: https://github.com/google/knative-gcp/blob/d3ddec04958ad0db06d1af6cf8e6128252499616/pkg/apis/duck/v1beta1/identity_types.go#L21

@grac3gao Please feel free to add more details here.

**Comment by grac3gao** [comment]
Just add more context for sources:
User can specify a KSA via the `IdentitySpec`. This KSA
1) previously manually binds to a GSA
or 2) automatically binds to a GSA if users put the KSA: GSA pair in `configmap` config-gcp-auth and give the controller GSA permission to manipulate this GSA

Then, this KSA will be transferring all the way down to the publisher and recieve-adaptor Pod as their serviceAccountName

**Comment by grac3gao** [comment]
We are fine with our current way to make Broker Data Plane's auth config more like our Control Plane do (no `IdentitySpec`). We may want to revisit it if we want to use multiple BrokerCell in one cluster in the future.
