### ISSUE TITLE
Flakiness: E2E test of GCPBroker

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#1394]
**Describe the bug**
E2E test related to GCP Broker under WI mode is flaky.
Example:
https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/google_knative-gcp/1388/pull-google-knative-gcp-wi-tests/1280550413002608640
Error msg is as follows:
`TestGCPBroker: test_gcp_broker.go:59: job: error sending cloudevent: 503 Service Unavailable
TestGCPBroker: test_gcp_broker.go:59: dummy event wasn't sent to broker`

 **Expected behavior**
E2E test of TestGCPBroker consistently pass.

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative-GCP release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by grantr** [comment]
@grac3gao Do you think this issue will be fixed by your investigation of #1362?

**Comment by grac3gao** [comment]
@grantr That may be the different issues. #1362's error is produced in the fanout Pod, this issue's error is produced in the ingress Pod (we handled unknown encoding in ingress Pod). But this issue may be fixed by PR #1358

**Comment by grac3gao** [comment]
fixed by #1415 and #1444
