### ISSUE TITLE
Add docs regarding how to set up tracing and metrics and relevant example docs 

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#1397]
Add docs regarding how to set up tracing and metrics 
Add relevant example docs of tracing and metrics

**Exit Criteria**
Add docs regarding how to set up tracing and metrics 
Add relevant example docs of tracing and metrics

**Comment by grantr** [comment]
Are these docs relevant here? https://knative.dev/docs/eventing/accessing-traces/

**Comment by nachocano** [comment]
I created an issue sometime back in knative docs. 
There are some comments there with a few pointers to docs in the eventing repo.

https://github.com/knative/docs/issues/1792

**Comment by Harwayne** [comment]
/close

Closed in favor of #1405 and #1406, which splits this into tracing and metrics into distinct issues.
