### ISSUE TITLE
Flakiness - E2E test of TestGCPBrokerMetrics 

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#1403]
**Describe the bug**
E2E test of TestGCPBrokerMetrics  is flaky.
Example:
https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/google_knative-gcp/1381/pull-google-knative-gcp-integration-tests/1280619367419088896
Error msg:
    `TestGCPBrokerMetrics: test_gcp_broker.go:68: timeout checking metrics
    TestGCPBrokerMetrics: test_gcp_broker.go:68: unexpected broker metric count (-want, +got) =   map[string]int64{
          	"e2e-dummy-event-type":              1,
        - 	"e2e-testing-resp-event-type-dummy": 1,
        + 	"e2e-testing-resp-event-type-dummy": 2,
          }`
        
   ` TestGCPBrokerMetrics: test_gcp_broker.go:68: unexpected metric "knative.dev/eventing/trigger/event_count" count (-want, +got) =   map[lib.TriggerAssertionKey]int64{
          	{Name: "resp-broker-gcp-oovssiyj", RespCode: 202}:    1,
        - 	{Name: "trigger-broker-gcp-oovssiyj", RespCode: 202}: 1,
        + 	{Name: "trigger-broker-gcp-oovssiyj", RespCode: 202}: 2,
          	{Name: "trigger-broker-gcp-oovssiyj", RespCode: 400}: 2,
          }`
Another example:
https://storage.googleapis.com/knative-prow/pr-logs/pull/google_knative-gcp/1388/pull-google-knative-gcp-wi-tests/1280604142049431552/build-log.txt
 `TestGCPBrokerMetrics: test_gcp_broker.go:68: unexpected metric "knative.dev/eventing/trigger/event_count" count (-want, +got) =   map[lib.TriggerAssertionKey]int64{
        - 	{Name: "resp-broker-gcp-mjvlomyt", RespCode: 202}:    1,
        + 	{Name: "resp-broker-gcp-mjvlomyt", RespCode: 202}:    0,
        - 	{Name: "trigger-broker-gcp-mjvlomyt", RespCode: 202}: 1,
        + 	{Name: "trigger-broker-gcp-mjvlomyt", RespCode: 202}: 0,
        - 	{Name: "trigger-broker-gcp-mjvlomyt", RespCode: 400}: 2,
        + 	{Name: "trigger-broker-gcp-mjvlomyt", RespCode: 400}: 0,
          }`

 **Expected behavior**
TestGCPBrokerMetrics  consistently pass

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative-GCP release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by grantr** [comment]
Additional context: the first example is in secret mode
