### ISSUE TITLE
Promote CloudBuildSource to v1

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#1413]
**Problem**
We need to promote CloudBuildSource to v1.
Some tasks this will entail, and can probably be done in different PRs.

- [x] v1 types with UTs
- [x] add new version to CRD
- [x] defaulting and conversion webhook
- [ ] Update docs and examples
- [ ] Migrate reconciler to v1 with UTs
- [ ] Add e2e tests to also support v1

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Developer

**Exit Criteria**
Build source is in v1

**Comment by bryeung** [comment]
Blocked by #1434

**Comment by danyinggu** [comment]
@capri-xiyue I will remove the promotion of cloudBuildSource from #1450.

**Comment by capri-xiyue** [comment]
This can be done after https://github.com/google/knative-gcp/issues/1544 gets merged so that we can avoid merge conflicts devs don't need to write conversion logic from v1alpha1 to other versions and from other versions to v1alpha1.

**Comment by danyinggu** [comment]
Due to https://github.com/google/knative-gcp/issues/1544#issuecomment-683882784 and synced with @nachocano offline. We will delay the removal of v1alpha1 (#1544) until 0.19 release, but we will still promote CloudBuildSource in 0.18, so it doesn't need to wait for #1544 to be done..
