### ISSUE TITLE
Promote ContainerSource to v1beta1

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#1414]
**Problem**
This is just a duplicate of https://github.com/knative/eventing/issues/3426, so that we can track it in our sprint.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Developer

**Exit Criteria**
ContainerSource in v1beta1

**Comment by nachocano** [comment]
@bharattkukreja can we close this one if the eventing counterpart is fixed?

**Comment by bharattkukreja** [comment]
Yep, closing this issue

**Comment by nachocano** [comment]
Eventing counterpart fixed. Closing this tracking issue
