### ISSUE TITLE
Decide whether to remove IdentityStatus.ServiceAccountName and do it

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#1426]
**Problem**
IdentityStatus has a serviceAccountName field which we are not using. It was used in the previous WI version, where we had googleServiceAccount as part of the spec, and thus we were populating the status with the ksa...
We need to decide whether to remove it completely or rename it and use the gsa in the status instead.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Developer

**Exit Criteria**
Decision made and either removed or renamed to include the GSA

**Comment by nachocano** [comment]
@Harwayne @grac3gao 

As we are starting to move sources to v1, this is something that came up. We used to have a custom IdentityStatus because we were adding the `serviceAccountName` there, in the old times where we were setting the `googleServiceAccount` as part of the spec. Now this is basically the same as `spec.serviceAccountName`. 
Either we should remove it or change it to have a reference to the GSA. 

I wanted to hear your opinion here on what would you prefer?
If we get rid of it, then I think we can get rid of IdentityStatus as well, and move the duckv1.Status to other structs, which will be cleaner I guess. Maybe also the IdentitySpec.
If we change it to have the GSA, it might be easier to debug?
WDYT?

**Comment by grac3gao** [comment]
If we want to add a `googleServiceAccount` status, we might check the KSA's annotation to get that value. 
The benefit for adding a `googleServiceAccount` status is when user choose the non-default mode for WI (users do the WI bindings by themselves), it can help to check wether they annotate the KSA or not. 

However, then it might become easier for people(anyone who have the permission to read yaml of the source) to know which GSA this source is using. (not sure if this has security problems)

I think it is good to have a status to reflect this if it doesn't have security problem, but I am also fine to directly remove this status.

Would like to hear your opinions @Harwayne

**Comment by Harwayne** [comment]
I think we all agree: remove `status.serviceAccountName`. 

Now there is a secondary question, should we add `status.googleServiceAccount`? It seems useful to me. But we can also add that later, as it is an additive change. I don't think it would be a security issue and would likely help debugging significantly.

So for now, I think we should remove `status.serviceAccountName` in v1, but leave `IdentityStatus` in place. If we all agree to add `status.googleServiceAccount`, then we can add it to the v1beta1 API. If we like it, we'll promote it next release. This should be tracked in a distinct issue.

**Comment by danyinggu** [comment]
I created another issue #1447, to track whether we should add the `status.googleServiceAccount`. 
I'm working on a PR to remove the `status.serviceAccountName` based on our discussion here.

**Comment by nachocano** [comment]
Sounds good, thanks @danyinggu !!!
For now, let's remove it, and we can then see where and when to add `status.googleServiceAccount`

**Comment by nachocano** [comment]
Closing this issue as we've decided to remove `status.serviceAccountName`
