### ISSUE TITLE
Pubsub CRDs and broker uses separate code paths to reconcile pubsub topic/sub

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#1430]
**Problem**
Currently the broker controller reconciles pubsub resources directly, while other resources uses the PubSub CRDs. It's not great to have duplicated code, especially when there is a common bug to fix, for example, we had to fix the "user manually delete topic" bug in https://github.com/google/knative-gcp/pull/1268 and https://github.com/google/knative-gcp/pull/1283

Option 1: Broker uses pubsub CRDs
There are some complexities involved: 
* The brokercell needs to watch for pubsub CRs created by the broker in order to get the name and status of the pubsub topic and pull subscriptions, in order to update the configmap. (It can determine the name of the topic but not the pull sub, the pull sub CRD generates pull sub name automatically). 
* Currently the CRDs hard code the config when creating topic/sub. Needs to make that configurable since the broker needs its custom config.

Option 2: Pubsub controllers and broker uses the same [pubsub helpers](https://github.com/google/knative-gcp/tree/master/pkg/reconciler/utils/pubsub) to create pubsub resources
This is the desired option but needs some investigation to make sure this is possible.
In this option, users won't be able to see pubsub GCP resources owned by the broker via the pubsub CRDs. But since the CRDs are internal, this is acceptable.

Option 3: Remove pubsub CRDs and use a common pubsub helper everywhere
Just for completeness. Out of scope. 

cc @grantr @Harwayne

**Comment by zhongduo** [comment]
One of the important factor here when making such choice is: **do we want to reconcile/recreate topics when the topics for broker or trigger are deleted somehow?** 

My experiment shows that if I delete manually a topic for retry, the trigger reconciler will not recreate it in minutes. It might recreate it during the next reconciliation period, but that will be hours later. If we want to do that, we will have to monitor topics in both broker and trigger reconciler, in which case I believe using CRD will be better.

**Comment by liu-cong** [comment]
> It might recreate it during the next reconciliation period, but that will be hours later. 

The resync period is 5 min, so it should recreate within 5 min. Did you have to wait longer than that?

Note that CRDs won't reconcile the topic immediately either.

**Comment by zhongduo** [comment]
> > It might recreate it during the next reconciliation period, but that will be hours later.
> 
> The resync period is 5 min, so it should recreate within 5 min. Did you have to wait longer than that?
> 
> Note that CRDs won't reconcile the topic immediately either.

You just made this a bug.... If you confirm this is the intended behavior, I will open a bug issue. But if I didn't do anything wrong, the retry topic I deleted was not created after 15 mins at least.

**Comment by liu-cong** [comment]
Please file a bug. Thanks @zhongduo for your finding!

**Comment by grantr** [comment]
There should be a k8s event noting that the topic was found to be missing and was recreated (plus the pull subscription was deleted and recreated with the new topic). Looking for that event within 5 minutes of the topic deletion will help narrow down where the issue is.

**Comment by zhongduo** [comment]
> There should be a k8s event noting that the topic was found to be missing and was recreated (plus the pull subscription was deleted and recreated with the new topic). Looking for that event within 5 minutes of the topic deletion will help narrow down where the issue is.

hmm, waited for 5 minutes with `stern -n cloud-run-events controller....`, no output in the 5 minutes.

**Comment by liu-cong** [comment]
I was not able to reproduce this for 0.15. @zhongduo Which version did you test?
