### ISSUE TITLE
Decide on the CE type/subject/source and schema of CloudBuildSource

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#1434]
**Problem**
As we did with other sources, we need to decide on the CE attributes to use for [CloudBuildSource](https://github.com/google/knative-gcp/blob/master/docs/examples/cloudbuildsource/README.md) (e.g., type, source, subject) as well as the schema.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Developer

**Exit Criteria**
CloudBuildSource with new attributes.

**Additional Context**
Still need to decide if we plan to release this one. Creating the issue for tracking purposes so that we don't forget

fyi @yolocs @jskeet @capri-xiyue

**Comment by capri-xiyue** [comment]
Closed as https://github.com/googleapis/google-cloudevents/pull/40 got merged
