### ISSUE TITLE
Decide whether we should remove v1alpha1 support for our Resources

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#1435]
**Problem**
Eventing has been removing v1alpha1 API support. We are currently using v1beta1 and we will eventually have v1 support. We should decide whether we want to keep v1alpha1 around or trim it entirely (as eventing did)

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Developer

**Exit Criteria**
Decide whether we should get rid of v1alpha1 or not.

**Comment by bryeung** [comment]
In eventing, v1alpha1 -> v1beta1 was breaking, so v1alpha1 was removed. This caused problems downstream, but we might not have the same downstream context here.

We need to deprecate in the release before we remove it. (Deprecation => the job which triggers the conversions.)

(When we do this we need to use the open source job that touches everything to trigger the conversions.)

**Comment by nachocano** [comment]
If we decide to remove v1alpha1, we need to:

- Change our converters, not to use v1alpha1 as Hub version anymore. 
- Create a migration tool so that we can move existing users to v1beta1 (or v1)

By removing v1alpha1, we will be removing a bunch of code, and we will reduce the maintenance cost (e.g., fixes to v1beta1 and v1 won't have to be backported to v1alpha1, etc.)
CLI is moving to v1beta1 so there is no risk to break existing tooling. Not that sure about UI, will sync with folks.

**Comment by nachocano** [comment]
Synced with UI folks, there is no risk of removing v1alpha1 on that front

**Comment by nachocano** [comment]
By removing v1alpha1, we will also probably reduce our E2E test time, as we run SmokeTests for all versions.

**Comment by capri-xiyue** [comment]
If removing v1alpha1 doesn't affect UI and CLI, I'm find that we remove v1alpha1.
For sources like CAL source, CloudStorageSource, CloudPubSubSource and CloudSchedulerSource has v1 version.
But for CloudBuildSource and Channel, we only have v1alpha1 and v1beta1. Not sure whether removing v1alpha1 support for those resources have any side effects.

**Comment by capri-xiyue** [comment]
Just checked the https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/,
To remove old version, we need to 

Removing an old version:
Ensure all clients are fully migrated to the new version. The kube-apiserver logs can reviewed to help identify any clients that are still accessing via the old version.
Set served to false for the old version in the spec.versions list. If any clients are still unexpectedly using the old version they may begin reporting errors attempting to access the custom resource objects at the old version. If this occurs, switch back to using served:true on the old version, migrate the remaining clients to the new version and repeat this step.
Ensure the upgrade of existing objects to the new stored version step has been completed.
Verify that the stored is set to true for the new version in the spec.versions list in the CustomResourceDefinition.
Verify that the old version is no longer listed in the CustomResourceDefinition status.storedVersions.
Remove the old version from the CustomResourceDefinition spec.versions list.
Drop conversion support for the old version in conversion webhooks.

**Comment by nachocano** [comment]
OK, given that we have no strong objections, and both CLI and UI have switched to v1beta1, we decided to remove v1alpha1 support. 

re: Channel and CloudBuildSource having v1alpha1 and v1beta1 only, I don't see it as a problem to remove v1alpha1, as long as we do the proper migration for our users.

We should probably do this after 0.17 cuts, but add a Deprecated condition to our resources that v1alpha1 support will be removed. Will create a follow up issue to triage
