### ISSUE TITLE
Decide whether to add `status.googleServiceAccount` and do it

### ISSUE THREAD

**Issue by danyinggu** [google/knative-gcp#1447]
**Problem**
Based on the discussion in #1426, we decided to remove `identityStatus.ServiceAccountName` and there is an ongoing discussion about if we should add `status.googleServiceAccount`, add it to v1beta1 and promote it to v1.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
The Decision is made and implementation is done.

cc @Harwayne @nachocano @grac3gao

**Comment by grac3gao** [comment]
From comment https://github.com/google/knative-gcp/issues/1426#issuecomment-657900212
> I think we all agree: remove `status.serviceAccountName`.
> 
> Now there is a secondary question, should we add `status.googleServiceAccount`? It seems useful to me. But we can also add that later, as it is an additive change. I don't think it would be a security issue and would likely help debugging significantly.
> 
> So for now, I think we should remove `status.serviceAccountName` in v1, but leave `IdentityStatus` in place. If we all agree to add `status.googleServiceAccount`, then we can add it to the v1beta1 API. If we like it, we'll promote it next release. This should be tracked in a distinct issue.

I agree with that, for adding `status.googleServiceAccount` in v1beta1 to help debugging

**Comment by nachocano** [comment]
Moving it to Security area as is more WI-related. Let me know if you think otherwise

**Comment by zhongduo** [comment]
As discussed with @grac3gao, the reconciler has already been promoted to v1, we will not update it now. But later we might want to continue this work with feature flag.
