### ISSUE TITLE
Rewrite TestChannelTracing Using Cloud Trace

### ISSUE THREAD

**Issue by ian-mi** [google/knative-gcp#1455]
**Describe the bug**
TestChannelTracing currently uses Zipkin which can cause issues as TestGCPBrokerTracing is configured to use Cloud Trace instead. 

 **Expected behavior**
TestChannelTracing should test tracing behavior with Cloud Trace.

**Comment by Harwayne** [comment]
This could be done by making the upstream test framework in knative/eventing be backend agnostic, but the easier and more likely fix is to copy the framework into this repo and alter it as needed to use Cloud Trace as the backend, instead of Zipkin (as is assumed in knative/eventing's framework).

**Comment by Harwayne** [comment]
Note that this test is currently skipped because other StackDriver tests assume that the backend is StackDriver and the tests assume that the backend setting is set once. We do not currently have a mechanism to have one test use a particular backend while another uses a distinct backend.

**Comment by Harwayne** [comment]
Lowering to P2 because Channels are lower priority than other work. But this should be considered blocking for Channels.
