### ISSUE TITLE
 Move CloudEvent client in test image to cev2 

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1467]
**Problem**
Now that we are using cev2 in most of the places, we can probably move CloudEvent client in test image to cev2. Most test images are using https://github.com/google/knative-gcp/tree/master/pkg/kncloudevents.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by nachocano** [comment]
I think this is a dupe from https://github.com/google/knative-gcp/issues/1336
We should close one. I'll leave it to you to decide which one. I'm fine with either.
