### ISSUE TITLE
Can't install if Knative Eventing is not installed

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1468]
**Describe the bug**
Since the controller now depends on Knative Eventing CRDs, it's possible the controller will crash unless Knative Eventing is also installed. I haven't confirmed this.

 **Expected behavior**
I can install and create a knative-gcp source pointing directly at a consumer without also having Knative Eventing installed.

 **Additional context**
I'm not sure if the expected behavior above is actually expected or a high priority.

**Comment by grantr** [comment]
Install docs say this:

> 5. Install Knative. Preferably, set up both Serving and Eventing. The latter is only required if you want to use the Pub/Sub Channel or a Broker backed by a Pub/Sub Channel.

If Eventing is required, we should update that line.

**Comment by grantr** [comment]
A compromise fix for this is a clear error message in the controller when Eventing is not installed.

**Comment by Harwayne** [comment]
P1 - Change in documentation, saying that you need Knative Eventing installed.
P2 - Have the controller check if Knative Eventing is installed, if it isn't give a good error message to the user. As opposed to the existing code which will have all the reconcilers startup in parallel and the returned error may not be as helpful.

**Comment by cathyzhyi** [comment]
@cathyzhyi is working on this now.

**Comment by cathyzhyi** [comment]
Potential fix in `pkg` https://github.com/knative/pkg/issues/1663

**Comment by cathyzhyi** [comment]
Change this issue to P2 as the P1 part in https://github.com/google/knative-gcp/issues/1468#issuecomment-665286067  is completed
