### ISSUE TITLE
Update CRDs to use `apiextensions.k8s.io/v1` 

### ISSUE THREAD

**Issue by danyinggu** [google/knative-gcp#1475]
**Problem**
In [serving](https://github.com/knative/serving/tree/master/config/core/resources) and [eventing](https://github.com/knative/eventing/tree/master/config/core/resources), we already used `apiextensions.k8s.io/v1` as the CRD API version. We should eventually update all of our CRD to use `apiextensions.k8s.io/v1` as well. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
All of our CRDs of resources are using `apiextensions.k8s.io/v1` as well. 

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

cc @Harwayne @nachocano

**Comment by Harwayne** [comment]
@danyinggu has this work started?

**Comment by danyinggu** [comment]
> @danyinggu has this work started?

No It hasn't started yet. I think we can utilize your PR #919 to change it to use v1 template?

**Comment by capri-xiyue** [comment]
Synced with @Harwayne  offline, Adam is ok if we use yaml merge to rewrite the yaml. So currently we can work on this issue first and Adam will work on that template change #919 later.
And here is the file of the PR that you can refer to https://github.com/google/knative-gcp/pull/1473/files#diff-03dcdd5a50d164008de2bb1c827d7cab regarding how to update CRDs to use `apiextensions.k8s.io/v1` and 
use yaml merge to rewrite the yaml.

**Comment by Harwayne** [comment]
> > @danyinggu has this work started?
> 
> No It hasn't started yet. I think we can utilize your PR #919 to change it to use v1 template?

With the changes made in #1473, namely usage of `<<:` to inject the differences between versions, I think the CRD generation is less useful than it used to be. 

I think we are better off moving to `apiextensions.k8s.io/v1`, then if we still want the CRD generation in #919, we can make it match the handmade CRDs. 

If we end up having issues like incorrect schemas, then we can reprioritize and get the generation first. But until we actually encounter those problems, let's prioritize moving to `apiextensions.k8s.io/v1`.

**Comment by danyinggu** [comment]
@nachocano @capri-xiyue I checked the code base, since I already update all sources' CRDs to use `apiextensions.k8s.io/v1` during the promotion of source to v1, the only resources that will need to be updated are Channel and BrokerCell.
