### ISSUE TITLE
Promote ApiServerSource to v1beta1

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#1477]
**Problem**
This is just a dupe of https://github.com/knative/eventing/issues/3611 so that we can track it in our own sprint.
Once we close that one, we can close this one.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Developer

**Comment by capri-xiyue** [comment]
Close this issue because https://github.com/knative/eventing/issues/3611 gets closed
