### ISSUE TITLE
Repeatable testing setup for analyzing broker performance and resource usage

### ISSUE THREAD

**Issue by yolocs** [google/knative-gcp#1489]
The test setup could be manual. The goal is to make it easy to run a certain workload against the broker.

**Comment by yolocs** [comment]
Test setup tool is at: https://github.com/yolocs/ce-test-actor
Existing scenarios are at: https://github.com/yolocs/ce-test-actor/tree/master/scenarios

**Comment by yolocs** [comment]
@grantr @grac3gao Do you think the current test setup is repeatable enough to close this issue? If not, what's missing?

**Comment by grac3gao** [comment]
I think it is repeatable enough, it helps me a lot to run the test.

**Comment by grantr** [comment]
I think all that's missing is documentation of how to use the tool. That can go in https://github.com/google/knative-gcp/tree/master/docs/development.
