### ISSUE TITLE
Release-0.16 branch vendors an outdated Knative Eventing 0.15 dependency

### ISSUE THREAD

**Issue by Ectelion** [google/knative-gcp#1494]
**Describe the bug**
In [go.mod (version 0.16)]( https://github.com/google/knative-gcp/blob/v0.16.0/go.mod), see knative.dev/eventing dependency.

 **Expected behavior**
The branch should vendor the respective 0.16 Eventing version.

**Comment by Harwayne** [comment]
@ericlem We might want a new issue that addresses the fact that it seems like our update-deps.sh script doesn't always update to what we expect.

**Comment by Ectelion** [comment]
@Harwayne, @ericlem I suspect it's due to calling update-deps without the "--upgrade" flag. Maybe a simple warning in such case would do.

**Comment by nachocano** [comment]
This is the PR that did the update. I'm almost sure I ran it with `--upgrade` (although I might be wrong)
https://github.com/google/knative-gcp/pull/1390
If you see the go.mod there, you can see that serving went to 0.16, but not eventing. So, I'm more confident that it was run with `upgrade`
If you see this PR that move pkg to 0.16 https://github.com/google/knative-gcp/pull/1373, you can see the go.mod that doesn't have pkg in 0.16.

Something similar happened to me a few times internally. I think is worth investigating a bit... 

Maybe is something related to this: https://stackoverflow.com/questions/58364988/go-module-not-downloading-latest-minor-version/60660853#60660853
