### ISSUE TITLE
Setup instructions with Workload Identity is too complicated

### ISSUE THREAD

**Issue by meteatamel** [google/knative-gcp#1496]
**Problem**
If you want to setup Knative on GKE with Knative-GCP project and with Workload Identity auth, the setup instructions are way too complicated. You need to first follow [install-knative-gcp](https://github.com/google/knative-gcp/blob/master/docs/install/install-knative-gcp.md) and then follow [dataplane-service-account.md](https://github.com/google/knative-gcp/blob/master/docs/install/dataplane-service-account.md). There are many steps, some of them are manual, some of them are script based. In the end, it's very error prone. I couldn't get it working and in the end, I reverted to Kubernetes secrets. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Anyone wanting to read Google Cloud events into Knative.

**Exit Criteria**
Give me a single script or a controller or something that sets everything up for me with defaults.

**Time Estimate (optional):** 
2-3 days

**Comment by grac3gao** [comment]
@meteatamel I added auto-script to the data plane for both secret and workload identity method. So now, the quick-steps would be: running script to set up the control plane, then running script to set up the data plane. Please let me know if these would help to reduce the complexity for authentication configuration. Thanks!

**Comment by meteatamel** [comment]
Ok. I'll try them next time I install Knative-GCP and open a new bug, if I feel like it's still hard to install and configure auth.
