### ISSUE TITLE
Source API objects must be able to round-trip between API versions without information loss

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#1499]
**Describe the bug**
 Source API objects must be able to round-trip between API versions without information loss. FYI: https://kubernetes.io/docs/reference/using-api/deprecation-policy/
But currently we don't support it. We lost spec.PayloadFormat for v1beta1 and v1alpha1 CloudStorageSource when we convert them from v1 CloudStorageSouece
https://github.com/google/knative-gcp/blob/b3228460098345fa5e8e81691b212ab4b6cff41f/pkg/apis/events/v1alpha1/cloudstoragesource_conversion_test.go#L145

 **Expected behavior**
Source API objects must be able to round-trip between API versions without information loss.

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative-GCP release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by nachocano** [comment]
I think when dowgrading to v1beta1 for status.ServiceAccontName, you can just set status.ServiceAccontName = spec.ServiceAccountName, as it is the same.
For CloudStorageSource spec.PayloadFormat, you can just set it to "JSON_API_V1". We weren't honoring that attribute, we were always using the same value.

**Comment by capri-xiyue** [comment]
Not sure whether it's a bug, not sure whether it falls under the exception: 
Rule #2: API objects must be able to round-trip between API versions in a given release without information loss, with the **exception of whole REST resources that do not exist in some versions.**
@adam Do you have any ideas?

**Comment by capri-xiyue** [comment]
> I think when dowgrading to v1beta1 for status.ServiceAccontName, you can just set status.ServiceAccontName = spec.ServiceAccountName, as it is the same.
> For CloudStorageSource spec.PayloadFormat, you can just set it to "JSON_API_V1". We weren't honoring that attribute, we were always using the same value.
I don't think we need to do roundtrip for status.ServiceAccontName since reconciler will never set the status.ServiceAccontName now and user also won't set it.
Yep. I think for CloudStorageSource spec.PayloadFormat, you can just set it to "JSON_API_V1".

**Comment by capri-xiyue** [comment]
For this Rule #2: API objects must be able to round-trip between API versions in a given release without information loss, with the **exception of whole REST resources that do not exist in some versions** listed under https://kubernetes.io/docs/reference/using-api/deprecation-policy/, I'm not sure whether our case falls in the category of exception. If it is, then it's not a bug.

**Comment by capri-xiyue** [comment]
Just talked with @Harwayne, the [deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#:~:text=Occasionally%20a%20Kubernetes%20release%20needs,year%20after%20their%20announced%20deprecation.) is for kubernetes. Since we build on kubernetes, we may not need to follow it. But it's a good reference for us when we reach stable api. Since v1alpha1 and v1beta1 are not stable apis, so I will close this issue for now.
