### ISSUE TITLE
Document broker stress testing scenarios

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1500]
**Problem**
We need a list of standard test scenarios to use when probing the broker's performance characteristics. Related to #1489, #1490, and #1491.

The test scenarios should be designed to push the broker to its limits and beyond, but based on realistic customer use cases and performance targets.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Contributor

**Exit Criteria**
A document listing test scenarios

**Additional context (optional)**
Some useful scenarios have been documented at #876, #1254, and #1265.

**Comment by liu-cong** [comment]
I unassigned myself for now as I don't think I will get to it this week.

**Comment by yolocs** [comment]
@grantr @grac3gao Do you think the scenarios here https://github.com/yolocs/ce-test-actor/tree/master/scenarios are good enough to close this issue? For all the problems we have detected, it doesn't seem we went beyond these scenarios (some parameters might be different from the generated yamls).

**Comment by grantr** [comment]
I think those scenarios are a good start, but to close this issue they need to be documented in this repo (ideally with a link to the scenario directory in the ce-test-actor repo).
