### ISSUE TITLE
Add data plane performance regression tests for sources

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#1517]
**Problem**
Add data plane performance regression tests for sources

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
Add data plane performance regression tests for sources

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by capri-xiyue** [comment]
Maybe we can follow how broker does for the performance tests

**Comment by nachocano** [comment]
We should do an investigation and split this into multiple issues.
Maybe try to have mako tests measuring throughput, and some memory/cpu profiling of our receive adapter as well
