### ISSUE TITLE
Provide guidance about configuring memory request and limit for users

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1524]
**Problem**
Once https://github.com/google/knative-gcp/pull/1509 lands, user will be able to set request and limits for broker pods.

We might need to provide some guidance for configuring memory request and limits for users, considering different resource setting combinations leads Pod to be in different QoS class, and would affect Broker Pods to have potential OOM killed/Eviction issues as  https://github.com/google/knative-gcp/issues/1502#issuecomment-664793074 indicates. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by liu-cong** [comment]
This is important as an interal document too, even if customers don't need to know all the details.

**Comment by liu-cong** [comment]
Need to decide whether we'd like to follow GKEs recommendation of request=limit for memory.

**Comment by liu-cong** [comment]
It's important to provide knobs for customers. However, we think it's better to provide some high level "broker profiles" to the customers, and we can adjust all knobs based on the profile. For instance, ask the user to ask how many bytes of events they have and derive values for knobs based on that.

**Comment by grantr** [comment]
> Need to decide whether we'd like to follow GKEs recommendation of request=limit for memory.

Tracked in #1545.

**Comment by grantr** [comment]
This is blocked by #1553.
