### ISSUE TITLE
need deploy knative crd if want use knative-gcp

### ISSUE THREAD

**Issue by runzexia** [google/knative-gcp#1527]
**Describe the bug**
knative-gcp controller would pending in init if the cluster do not have knative crds.

 **Expected behavior**
As readme It can be useful independently, but is best mixed with Knative.

 **To Reproduce**
Install knative gcp without knative serving/eventing crds.

**Comment by grantr** [comment]
Sorry you had trouble with the docs @runzexia. The readme is incorrect. In fact the knative-gcp controller currently depends on serving and eventing also being installed in the cluster. This is a bug in our docs and #1468 tracks fixing them.

Is it important for your use case to be able to use the knative-gcp components without eventing installed, or without serving installed? We'd love to know if this is a feature you need so we can prioritize it accurately.

**Comment by runzexia** [comment]
In our scenario, being able to deploy independently is very useful.
We use resources such as cloudpubsub and forward them to the kubernetes service (not knative service).
We are still investigating the use of knative core. But I now need to deploy many additional components (istio/knative)

**Comment by Harwayne** [comment]
FYI @bryanzimmerman.
