### ISSUE TITLE
knative-gcp broken CI/CD

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#1532]
**Describe the bug**
Currently the CI/CD of knative-gcp is broker. All e2e tests which involves ksvc can't pass.
https://prow.knative.dev/job-history/gs/knative-prow/pr-logs/directory/pull-google-knative-gcp-integration-tests
and https://prow.knative.dev/job-history/gs/knative-prow/pr-logs/directory/pull-google-knative-gcp-wi-tests
It looks like the issue is related to serving.
The root cause is `Ingress can not be configured`

 **Expected behavior**
CI/CD consistenly pass
 **To Reproduce**
Steps to reproduce the behavior.

 **Knative-GCP release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by capri-xiyue** [comment]
fyi @liu-cong

**Comment by liu-cong** [comment]
This should be temporarily fixed by https://github.com/google/knative-gcp/pull/1533.

I am going to look into whether we should use a release or nightly for serving.
