### ISSUE TITLE
Decide whether we should set request=limit for memory for broker data plane

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#1545]
**Problem**
A short explanation of the problem, including relevant restrictions.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by liu-cong** [comment]
Things to consider:
* Setting limit>request helps us handle memory surges, though at the cost of potentially OOM other pods with request<limit
* Also, when usage>request, it's more easily to be killed when node is overcommited

**Comment by liu-cong** [comment]
Action items:
* Ask GKE team about recommendation in this particular case (spiky memory use)
* How to avoid memory spikes?

**Comment by Ectelion** [comment]
I believe it indeed makes sense to match resource requests and limits for the Broker replicas. Here are few reasons for that:
1. This is explicitly recommended in Component ResourceRequest Policy for the GKE;
1. While Kubernetes's guidance is not as conclusive on that, it's [part of requirement](https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/) for the pod to obtain "Guaranteed" QoS class;
1. The case "requested memory < consumed memory < memory limit" is prone to higher OOM risks. Beyond the pod's burstability considerations, this would address a [related OOM edge case issue](https://github.com/google/knative-gcp/issues/1520), because request will now always be higher than the memory-based autoscaling threshold.

**Comment by liu-cong** [comment]
I think allowing memory spikes (request < limit) helps us prevent OOM as we currently cannot reliably limit the pod memory usage. 
If we set HPA threshold to be lower than requested, hopefully our autoscaling strategy kicks in timely so that  **usage**>requested should be very very rare.

> While Kubernetes's guidance is not as conclusive on that, it's part of requirement for the pod to obtain "Guaranteed" QoS class;

I think the pod is "Guranteed" QoS class as long as its actual **usage** is below requested. Even if we set request<limit, the pod should stay in "Guaranteed" during the majority of its lifetime.

**Comment by Ectelion** [comment]
Good points. I think the additional risk is that the safety span between request and limit is not guaranteed to be available at the time of the memory peak. Yeah, interesting trade-off between having a reasonable memory utilization and further reducing the OOM risks.

**Comment by Ectelion** [comment]
We had some more thoughts and discussions about this, let me try to summarize it.

To recap, we have a trade-off between more meaningful resource utilization and the following pod failure risks:
* When consumption goes above the request, the pod is considered as ‘overcommitted’ and becomes a candidate for eviction;
* A pod is not guaranteed to get resources above the request, e.g. it may be scheduled to a node which won’t be able to provide enough safety span to accommodate a memory surge;

To come up with a more weighted decision, one needs to take into consideration the following factors:
1. **Distribution of memory utilization**, with data points like _“for the given workload, memory consumption remains within 500Mb for 85% of time, under 1Gb for 95% of time and under 2Gb for 99.9% of time”_;
1. **Tolerance to pod failures**, with data points like _“we are targeting 99.9% availability”_;
1. **Cost**, with data points like _“we would compromise 0.1% of availability for every $x saved per month”_;

What made this decision so ambiguous is that we don’t really have enough data points about the typical workloads and load patterns to answer the questions above. One thing that is probably safe to assume is that the factors above may vary quite significantly across applications and customers.

Overall, considering the OOM risks and these uncertainties, with the data we have at hand, it seems reasonable to settle on “requests==limits” for the GA. We’ve also already settled on these for Ingress (#1600) and Fanout (#1601), and, while final Retry numbers are upcoming (#1602), it’s likely that we will end up with a consistent decision for Retry as well. Besides, this setup won’t be set in stone, as we now support configurability for the Broker deployments (#1484). As we gain more signal about our customers and their typical needs, this may be subject to further consideration.
