### ISSUE TITLE
Mark v1alpha1 being Deprecated

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#1547]
**Problem**
We decided to remove v1alpha1 support after 0.17 cuts. We should document in the release notes that we will be removing it. Further, we should have a deprecation warning in the status of the resources, probably set in the v1alpha1 conversion logic.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Developer

**Exit Criteria**
Mark v1alpha1 to be deprecated and state in the release notes that this will be remove in 0.18.

**Additional context (optional)**
See https://github.com/google/knative-gcp/issues/1544
and https://github.com/google/knative-gcp/issues/1435

**Comment by nachocano** [comment]
We should add a Deprecated status condition, similar to what this does:
https://github.com/knative/eventing/pull/3141/files#diff-99d1987d2919a2cce497502d2ecee2b0R218

But we should probably add it in the v1alpha1 conversion logic...

**Comment by nachocano** [comment]
fyi @danyinggu in case you are interested and have some cycles

**Comment by danyinggu** [comment]
@nachocano Sure, I am definitely willing to work on it. A quick question: should it be done after v1alpha1 is removed, or these are two separate issues that can be done in parallel?

**Comment by nachocano** [comment]
> @nachocano Sure, I am definitely willing to work on it. A quick question: should it be done after v1alpha1 is removed (#1544), or these are two separate issues that can be done in parallel, or all of these should be completed altogether?

Great! This should be done first and before 0.17 cuts. After the cut, we remove the support for v1alpha1 for 0.18.

**Comment by capri-xiyue** [comment]
@danyinggu  You can also take this PR as an example https://github.com/knative/eventing/pull/2107/files#diff-e18136aeccdc97c7dda5625ba2457979
