### ISSUE TITLE
Use desugared logger in broker data plane and fields instead of Sprintf

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1551]
**Problem**
The broker ingress currently uses ~the Zap sugared logger and~ fmt.Sprintf to interpolate variables before logging. ~The desugared logger is safer at runtime and more efficient. We should be using the desugared logger everywhere in the data plane.~

Using Sprintf means we allocate memory for a log message even if it is below the current log level. We should use Zap fields instead, as they are only evaluated when the log level would allow the message to be logged.

**Exit Criteria**
All broker data plane services use desugared logger without pre-interpolating messages.

**Comment by yolocs** [comment]
All broker components _are_ using desugared logger already.

**Comment by grantr** [comment]
Oops, you're absolutely right @yolocs. When I [looked at the code](https://github.com/google/knative-gcp/blob/4cba2abf97865752025fa6a8eb8a4f2825e376e2/pkg/broker/ingress/handler.go#L87) earlier I was thinking there was a `zap.DesugaredLogger` class and `zap.Logger` was the sugared one. Sorry for the misdirection. 😞
