### ISSUE TITLE
Adjust broker components resource request/limit and HPA for a reasonable default setup

### ISSUE THREAD

**Issue by yolocs** [google/knative-gcp#1552]
We need to adjust the broker components resource request/limit and HPA so that it can meet the most common needs. Some criterias:

* Components won't crash because of OOM
  * This implies each component, with a limit in mind, is able to protect itself from over consuming memory.
  * This also means we fixes all the memory leaks (if there are more).
* The setup will be able to support common loads.
  * We first need to define several common loads we expect to see or from customer surveys.

**Comment by grantr** [comment]
I created some issues breaking this down to two tasks for each broker service:
- determine the default target
- measure resource requirements to meet that target and use those requirements in the deployment

Ideally we would like to avoid crashing with any arbitrary load, but for this issue we will settle for not crashing with our default load targets.

**Comment by grantr** [comment]
Broke this down into smaller issues.
