### ISSUE TITLE
Flip the storage bit to v1beta1 in core eventing sources

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#1588]
**Problem**
In 0.17 we moved core sources to v1beta1. We need to flip the storage bit now, so that we store v1beta1.
This is used to track the follow eventing issues: https://github.com/knative/eventing/issues/3674, https://github.com/knative/eventing/issues/3630, and https://github.com/knative/eventing/issues/3615. 
We should also sync with Lionel to see if he will take care of PingSource, which also needs to move the reconciler to v1beta1.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Developer

**Exit Criteria**
All core sources store v1beta1

**Additional context (optional)**
See links provided above.

**Comment by nachocano** [comment]
/assign @nlopezgi 

This is just for tracking the eventing issues in our sprint. Solving those, should solve this.
If you can also sync with Lionel regarding PingSource, maybe you can flip the storage bit there as well, and you will have to change the reconciler to use v1beta1 as well.

**Comment by nlopezgi** [comment]
ContainerSource and SinkBinding fixed here: https://github.com/knative/eventing/pull/3895. ApiServerSource is pending confirmation on the bug that its ready to proceed. Is https://github.com/knative/eventing/issues/3886 also part of what is needed for this issue? @danyinggu  and @bharattkukreja might be taking on https://github.com/knative/eventing/issues/3886?

**Comment by danyinggu** [comment]
> ContainerSource and SinkBinding fixed here: [knative/eventing#3895](https://github.com/knative/eventing/pull/3895). ApiServerSource is pending confirmation on the bug that its ready to proceed. Is [knative/eventing#3886](https://github.com/knative/eventing/issues/3886) also part of what is needed for this issue? @danyinggu and @bharattkukreja might be taking on [knative/eventing#3886](https://github.com/knative/eventing/issues/3886)?

Thanks Nick! I don't have free-cycles for now, but I'm willing to pick it up when I have cycles.

**Comment by danyinggu** [comment]
@nlopezgi Seems like someone from Knative Community was assigned with knative/eventing#3886 and will take care of it.

**Comment by nlopezgi** [comment]
> @nlopezgi Seems like someone from Knative Community was assigned with [knative/eventing#3886](https://github.com/knative/eventing/issues/3886) and will take care of it.

sgtm

**Comment by nlopezgi** [comment]
I noted in https://github.com/knative/eventing/issues/3630 that I wont be able to complete the issue in the upcoming weeks as the effort required is a bit more than I planned and I dont have the cycles available. https://github.com/knative/eventing/issues/3630

**Comment by nachocano** [comment]
Thanks @nlopezgi for working on this! Someone else will pick the remaining ApiServerSource in the upcoming sprint(s)

**Comment by capri-xiyue** [comment]
closed since all https://github.com/knative/eventing/issues/3674, https://github.com/knative/eventing/issues/3630, https://github.com/knative/eventing/issues/3615 and https://github.com/knative/eventing/pull/3951 get closed or merged
