### ISSUE TITLE
Allow configuring retry on specific response codes

### ISSUE THREAD

**Issue by yolocs** [google/knative-gcp#1594]
Originated from https://github.com/google/knative-gcp/issues/970

The current delivery spec doesn't allow setting up retry for specific response codes. We might consider upstream this issue to knative/eventing.

**Comment by yolocs** [comment]
@alexander-alvarez FYI we have split this issue from https://github.com/google/knative-gcp/issues/970. There is ongoing work to implement the eventing delivery spec which would allow you to configure retry delay/strategy, etc.

**Comment by grantr** [comment]
https://github.com/cloudevents/sdk-go/pull/596 makes this possible by allowing a custom function to specify the retry policy.

**Comment by zhongduo** [comment]
> [cloudevents/sdk-go#596](https://github.com/cloudevents/sdk-go/pull/596) makes this possible by allowing a custom function to specify the retry policy.

**Comment by Harwayne** [comment]
When we do this, we should make sure to have a Trigger `retry_event_count` metric, so that we can easily see how many events going to a given Trigger are failing and forcing a retry.
