### ISSUE TITLE
Determine default target for broker ingress events per second

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1596]
**Problem**
What is our default target for published events per second handled by the broker ingress service? This is separate from the fanout's delivered events per second (and is likely to be lower).

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
User

**Exit Criteria**
We have a goal in published events per second to tune the default ingress resource requirements.

Part of #1552.

**Comment by grantr** [comment]
@liu-cong suggests default target 1000 events per second.

**Comment by yolocs** [comment]
The default target I'm setting for a single ingress pod is: <= 1000 qps, <= 256k event size.
