### ISSUE TITLE
Determine default target for broker retry delivery attempts per second

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1598]
**Problem**
What is our default target for delivery attempts per second handled by the broker retry service?

This could be defined as a percentage of delivery attempt rate (#1597), for example "10% of delivery attempts will be retried," but since events may be retried multiple times, it's probably clearer to set an explicit rate goal.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
User

**Exit Criteria**
We have a goal in delivery attempts per second to tune the default fanout resource requirements.

**Additional context (optional)**
Part of #1552.

**Comment by grantr** [comment]
Decided on 10% of total throughput being retried.

**Comment by cathyzhyi** [comment]
The default target for retry is set to cover 10% failure rate for the fanout delivery. The resulting throughput is sum of a geometric progression with scale factor of 10% and base of 2.5Gb which is fanout target throughput set in #1597 . ( 10%+10%*10% + 10%*10%*10%....)*2.5 Gb/s ~280Mb/s.
