### ISSUE TITLE
Adjust broker fanout resource requirements to meet default delivery attempts per second target

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1601]
**Problem**
Once we have an events per second target #1597 and a default event payload size #1599, we can measure the resource requirements for a single fanout pod to meet the target. That's our default resource requirement value.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
User

**Exit Criteria**
The broker fanout deployment is created with default resource requirements allowing it to meet the default delivery attempts per second target.

**Additional context (optional)**
Part of #1552.

**Comment by yolocs** [comment]
We currently use the default outstanding bytes limit (1G). We probably need a smaller number.

**Comment by Ectelion** [comment]
Key notes from our investigation on fanout:
*  We’ve started with single pod experiments, which suggested that a single Fanout pod can not reach a sustainable throughput under our initially assumed Ingress load (1000 rps and 256kb payload) even with high resource requests. For a suitable max load for a single fanout pod, please refer the table on #1597;
* We’ve then adjusted our goal to supporting the target load with multiple replicas and autoscaling. There were few issues with this, but eventually, better results were achieved and we reached the desired throughput -- 256Mb/s inbound rate and up to 2.5Gb outbound rate, -- with 4-5 replicas;
* Main challenges were in figuring the bottlenecks that limited fanout’s scale out efficiency. While some of them were legitimate, the others had to do with experimental setup;
    * [PubSub quotas](https://cloud.google.com/pubsub/quotas) on both publisher and subscriber were confirmed to be among the bottlenecks and were extended. CPU quotas on the cluster (72 units or up to 120 with some workarounds) are also pretty troublesome and can't be extended;
    * Occasional OOM crashes were worked around by tuning the memory limit, outstanding bytes parameter on Receiver settings and allocating more resources to the node pool;
    * One of consistently observed patterns was a sudden drop in the CPU consumption that re-appeared periodically, even though the pods were up and running. This turned out to be due to a bottleneck on the consumer side that reveals when more fanout replicas start hitting them with concurrent requests. Can be mitigated by making explicit (and high enough) resource requests to the consumer pods;
    * Autoscaling appears to be more reliable and results in higher throughput when we use a considerably lower CPU utilization threshold (e.g. ~60% vs currently used 95%). As we increase the threshold, there is a growing risk that autoscaling won’t be triggered even under overwhelming load, which results in a rapidly growing backlog of undelivered messages;
    * Based on our observations throughout these experiments, by default, Kubernetes tends to distribute the load across nodes more or less evenly over time, which makes sense. However, we should be careful with very high CPU requests for HPA-enabled deployments, because this may put at risk horizontal scaling even when the cluster is reasonably under its max load. For example, given a cluster with 25 n1-standard machines (with 4 cores) and the overall utilization of 75%, we may end up with an allocatable CPU of 25000m overall, but only 1000m available on each machine, which may block the scheduling of a 3000m pod. Similar situation was observed in several experiments;
* Outstanding bytes on ReceiverSettings is indeed an important and a bit tricky parameter:
    * Increasing it results in a higher throughput at the cost of increased memory consumption;
    * Lowering it decreases OOM risks, but at the same time (expectedly) decreases throughput and (not so expectedly) increases the risks with autoscaling. In particular, even under a high rps fanout may simply pull not enough data to keep itself busy, process it at a slow pace with not high enough CPU utilization to trigger the HPA and not let other replicas join in processing the growing backlog;
* When analyzing memory consumption with Stackdriver, be careful with the minimal aggregation scale of 1 minute on the metrics - it may smooth out rapid spikes that appear for a short time. So, it makes sense to assume a higher surge than what was actually observed;
* Consideration for future work: a custom metric based autoscaling (e.g. the size of the backlog on PubSub) may likely work better than a pure consumption-based autoscaling: fanout may scale more operatively and this would guarantee that the scale will be reached regardless of low consumption.

In the end, here is how a typical fanout throughput looks like under a load that is slightly higher than our max target, when starting cold from a single replica and scaling up to 5:
![image](https://user-images.githubusercontent.com/1721518/93390811-249c7a80-f823-11ea-98f8-69e783699bbd.png)

This comes with reasonable cold start and manageable backlog properties:
![image](https://user-images.githubusercontent.com/1721518/93390995-65948f00-f823-11ea-8afa-094a64fff207.png)

**Comment by Ectelion** [comment]
The results above were reliably achieved with the following config:
* **CPU**
    * **Request:** 2500m request
        * There was some trade-off here: as can be seen from the past experiments, high CPU is important for fanout throughput. On the other hand, see notes on the risk of high CPU requests for horizontal scaling.
    * **Limit:** No limit for the CPU, as suggested by GKE's best practices;
* **Memory**
    * **Limit:** 5Gb
        * In most experiments, memory consumption stayed safely below 500Mb. This is based on (1) the memory stress test described in the previous related doc, where we’ve observed the maximal spike of 3.4Gb, plus some safety span; (2) auto scaling experiments, where we’ve also experienced occasional OOM issues even with 4Gb;
    * **Request:** same as the limit, as suggested by the GKE’s best practices;
* **Autoscaling params**
    * **Target CPU utilization threshold:** 60%
        * See notes above on the CPU utilization; 
    * **Memory consumption threshold:** 2500Mb
        * Memory consumption spikes can be rapid, especially when a sudden load is applied during a cold state. This leaves a single deployment some safety buffer. It is now also below the request, which should address the [memory-based autoscaling edge case](https://github.com/google/knative-gcp/issues/1520);
* **Other**
    * **OutstandingBytesLimit on ReceiverSettings:** 800Mb (default is 1Gb)
        * This reduces memory consumption and OOM risks, while also keeping it well above our target delivery rate of 256Mb/s

Note that the above resource requirements per individual pod are quite high. For better resource utilization and being considerate of feedback like [this](https://github.com/google/knative-gcp/issues/1671), as a follow up, we aim to reduce the initial resource request and make it more demand-driven by relying increasingly more on autoscaling -- this additional work will likely be outside of the scope of this task.

**Comment by grantr** [comment]
Thank you @Ectelion, this is really useful knowledge to have about our performance characteristics.

We now have the parameter values to meet the original target, and all remaining work is now part of #1713, so this issue can be closed.
