### ISSUE TITLE
Change EventType of CloudBuildSource

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#1608]
**Problem**
Since https://github.com/googleapis/google-cloudevents/pull/40 gets merged, we need to change the CE type of CloudBuildSource from `com.google.cloud.build.event` to `google.cloud.cloudbuild.build.v1.statusChanged`

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
Change CE type of CloudBuildSource  from com.google.cloud.build.event to `google.cloud.cloudbuild.build.v1.statusChanged` and also modify the relevant docs

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by nachocano** [comment]
fyi @bharattkukreja 
this is an simple one

**Comment by nachocano** [comment]
See this release notes: https://github.com/google/knative-gcp/pull/1340

**Comment by nachocano** [comment]
Also change the schemaURL to point to the correct one: 
https://raw.githubusercontent.com/googleapis/google-cloudevents/master/proto/google/events/cloud/build/v1/data.proto

and see how we are doing it in pubsub for example.
