### ISSUE TITLE
Make v1 the storage version of CloudBuildSource

### ISSUE THREAD

**Issue by danyinggu** [google/knative-gcp#1610]
**Problem**
We will not make v1 the storage version for CloudBuildSource in 0.18 release cut. We will v1 the storage version OF CloudBuildSource in 0.19 release cut, create a stand-alone issue to track this.
Relates to #1413, #1608 and #1482.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
v1 is the storage version for CloudBuildSource.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

cc @nachocano @capri-xiyue

**Comment by nlopezgi** [comment]
Hey Folks, sorry to chime in on this so late after its been closed. We should be avoiding writing any more pre-install jobs and instead rely on post install jobs. Pinging here for future reference as I'm not sure where else to note this.
