### ISSUE TITLE
Report error in GCP broker when `google-broker-key` is not setup

### ISSUE THREAD

**Issue by zhongduo** [google/knative-gcp#1624]
**Problem**
Currently in an absence of `google-broker-key`, the broker will be started to a ready state, but reject all the messages/events by returning 500. It will be more helpful if the broker can give a serivous warning or just not get to ready state at all.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Event consumer (developer)

**Exit Criteria**
Without setting up the authentication part in https://github.com/google/knative-gcp/blob/master/docs/install/install-gcp-broker.md, an obvious error should be observed when applying the broker.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grac3gao** [comment]
related to #1058

**Comment by grantr** [comment]
We could check in the controller if the secret exists, but it won't exist if WI is enabled and there's no obvious way to know if WI is enabled.

**Comment by zhongduo** [comment]
Is it possible to use some sort of startup check? Like keep-alive beacon.

**Comment by grantr** [comment]
Yes, that solution is tracked in #1058. For now we plan to add troubleshooting docs to help users debug this case.

**Comment by grantr** [comment]
Related to #1393

**Comment by Harwayne** [comment]
@grac3gao did #1947 fix this?

**Comment by grac3gao** [comment]
@Harwayne Yes, it did.
Fixed by #1947
