### ISSUE TITLE
True ingress readiness for GCP Broker

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#1627]
**Describe the bug**
The ingress returns an error if the broker status is not ready:
https://github.com/google/knative-gcp/blob/57e63f94a1447dcba916336aed86001c8de4ae12/pkg/broker/ingress/multi_topic_decouple_sink.go#L137

Currently a Broker is marked ready when the brokercell (including data plane services and HPAs) and pubsub topic/subscription is ready. However, from the  ingress's perspective, it is ready as long as the pubsub topic is ready. In our probes, we have noticed that Broker readiness can fluctuate due to for example the retry HPA is not reconciled properly for some reason. In such cases, we do not want to reject the event, otherwise this reduces our SLO.

### Option 1 (Preferred): Optimistically send events to the topic
Remove the broker status check logic in ingress. Instead, just go ahead and send the event to the topic. An error will be returned anyway if the topic is not ready.

### Option 2: Redefine Broker readiness to be ingress readiness
Current definition of broker readiness includes the entire brokercell readiness plus decouple topic/subscription. We could redefine it so that a broker is ready as long as its ingress is ready. This doesn't seem an ideal UX. For example, if there is an issue with fanout, user has no visibility until they create a trigger (and the trigger status should take the fanout status into consideration).

**Comment by grantr** [comment]
Thanks @liu-cong for finding this issue!

Before making the change in #1628, let's confirm that the original reasoning for #1261 and #1272 no longer applies or is less important than the issue here. I believe the original discussion was recorded in our meeting notes.

**Comment by liu-cong** [comment]
Thanks for reminding me the previous discussions! @grantr 

The purpose of #1261 is to reject events if topic/sub is not ready. So it seems that we could have a topic/sub status in the config and the ingress can check that instead. I guess it's better than just optimistically sending events to the topic. @yolocs may have more context on this.

**Comment by grantr** [comment]
Thanks for the reminder @liu-cong. Now I recall the concern was that messages would be published but never delivered if the fanout subscription has not yet been created. I think I recall some discussion of separating broker readiness (from the user perspective, as shown in the object) from readiness of internal pubsub objects.

Theoretically the brokercell can use the Broker's pubsub topic and subscription ready conditions to determine publish readiness and add that to the configmap. Or it could add both topic and subscription readiness to the configmap and let the ingress use them to determine publish readiness.
