### ISSUE TITLE
BrokerCell Configurability: settle on the policy around the HPA metrics

### ISSUE THREAD

**Issue by Ectelion** [google/knative-gcp#1632]
**Problem**
In #1603, we iterated over some of the UX aspects of [BrokerCell configurability](https://github.com/google/knative-gcp/issues/1484). Since there are quite many possible combinations of these parameters and their values are inter-related, we had discussions around defaulting and validation approaches, and the user experience around it. For instance, when any of the CPU parameters is set, but neither memory requests nor limits are specified, we've eventually settled on treating this as _"keep with the Kubernetes defaults for the memory"_ and not applying our Eventing defaults. One remaining decision to settle on is related to the auto-scaler configurability. By default, we specify two metrics for the HPA to scale by: average CPU utilization and average memory consumption. Now consider what happens when the user specifies only the CPU utilization metric, but not memory (or vice versa). There are at least three approaches that we can choose from:
1. Don't default or enforce anything for the unspecified HPA metric (similar to the example above);
2. Apply our defaulting logic to the unspecified metric;
3. Enforce users to always specify both;

The task is about settling on any of these (or other) options and making the change, if needed. 

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Comment by grantr** [comment]
Looks like we missed this in triage. @Ectelion did we make a decision about this, or is it still an issue?

**Comment by Ectelion** [comment]
@grantr current implementation follows approach 1, but we didn't discuss if everyone is fine with this policy. My bad on putting this to the backlog. I will bring this up during the next team sync up.
