### ISSUE TITLE
Source event schema validation

### ISSUE THREAD

**Issue by yolocs** [google/knative-gcp#1640]
**Problem**

We currently "blindly" pass data from upstream, assuming they match the desired schemas defined in https://github.com/googleapis/google-cloudevents. If any change happens, it would break this contract without us knowing.

**Solution**

Option 1: Manual validation. This is probably good as one-shot validation before releases.
Option 2: Automated integ tests that validates the schemas.
Option 3: Runtime validation. This would require mode detailed design: 1) how to do validation efficiently? since it impacts runtime perf 2) what's desired behavior if validation fails?

**Suggestion**

In the short term, some doc for doing manual validation could be sufficient. In mid to longer term, investigating in option 2 would preferable.

**Comment by yolocs** [comment]
@nachocano @capri-xiyue for proper planning.

**Comment by nachocano** [comment]
I think we should aim to have Option 2. We might be able to add that to our current E2E tests. 
Estimating it as if we are doing Option 2.

BTW, the Serverless WG has the Discovery/Subscription/SchemaRegistry APIs, and there is being some talks about doing runtime validations (Option 3). I think I'd rather hold off on that one for a bit until we get more clarity what CloudEvents is thinking of doing in that space.

**Comment by nachocano** [comment]
fyi @danyinggu @bharattkukreja

**Comment by danyinggu** [comment]
> fyi @danyinggu @bharattkukreja

Thanks for mentioning! I may not have free cycles for this sprint. Not sure if @bharattkukreja does

**Comment by capri-xiyue** [comment]
I checked the status https://github.com/googleapis/google-cloudevents-go. It looks like currently user has to run some script like `./gen.sh` to generate the libraries. After this https://github.com/googleapis/google-cloudevents-go/issues/2 gets resolved, I think we can use this repo https://github.com/googleapis/google-cloudevents-go to automate integ tests that validates the schemas.
