### ISSUE TITLE
Investigate using zapdriver to format logs

### ISSUE THREAD

**Issue by ian-mi** [google/knative-gcp#1654]
**Describe the bug**
Zap's structured log format differs from the format expected by Cloud Logging. For example zap's level field is not recognized as "severity" by Cloud Logging.

 **Expected behavior**
zapdriver or another solution should be used to ensure that severity is set correctly in cloud logging.

**Additional Context**
https://github.com/blendle/zapdriver is a possible solution which outputs structured logs which are fully compatible with Cloud Logging.

**Comment by Harwayne** [comment]
Fixed by knative/pkg#1773.
