### ISSUE TITLE
Brokercell reconciliation will reset deployment replicas during upgrade

### ISSUE THREAD

**Issue by yolocs** [google/knative-gcp#1683]
See https://github.com/google/knative-gcp/issues/611#issuecomment-689850159

Fix: do not change deployment replica number.

**Comment by grantr** [comment]
Looks like we never triaged this one. This seems like it might be a P1. What do you think @yolocs?

**Comment by yolocs** [comment]
Should be fixed in https://github.com/google/knative-gcp/pull/1690
