### ISSUE TITLE
Document broker default performance target and auto scaling limitations

### ISSUE THREAD

**Issue by yolocs** [google/knative-gcp#1696]
In multiple issues (e.g. https://github.com/google/knative-gcp/issues/1596) we have set a default load target for the default broker setup. We should document that in details.

Additionally, we probably want to document:

- How to customize the resource requirements for different loads
- The current auto scaling strategy (cpu/mem based) and its limitations (e.g. not capable of detecting backpressure).

**Comment by grantr** [comment]
Related to #1671

**Comment by grantr** [comment]
Related to #1553
