### ISSUE TITLE
Evaluate the impact of initial delivery timeout on throughput

### ISSUE THREAD

**Issue by Ectelion** [google/knative-gcp#1699]
Currently, BrokerCell deployments have a default timeout of 10 minutes per event. There is also a cap on the number of concurrent open connections. When there is a mix of fast and slow clients, from throughput perspective, it may not always be optimal to hang on to slow clients for that long. For example, if 10 clients out of 1000 are very slow and they happen to be at the beginning of the delivery queue, then there may be notably higher latency observed by the rest of the clients, compared to the case when the slow clients are at the end of the delivery queue. It is likely possible to come up with a more optimal policy, where we would prioritize more responsive clients by keeping it with a shorter timeout on the initial delivery attempt and handing over the slower ones to the retry queue. This task is about quantifying the effect and, if it is meaningful, applying the change.

**Comment by grantr** [comment]
Exit criteria: benchmark results of a workload with a variety of response times
