### ISSUE TITLE
Automatically restart broker data plane when broker secret created or updated

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1700]
**Problem**
Update secret have sync period + cache propagation delay https://kubernetes.io/docs/concepts/configuration/secret/#mounted-secrets-are-updated-automatically, it is around 1 min. For the control plane, we automatically restart the controller pod once the secret got updated to avoid the delay. For the broker data plane, we need to wait for 1 min or manually restart ingress/fanout/retry pod. 

It would be useful to automatically restart broker data plane when broker secret created or updated (similar as we did for the control plane)

Note: it is a corner case. Secret is unlikely to change once it is set, and in practice, the key expiration for GSA (which stored in the secret) is 10 years.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment]
The deployment controller used for control plane can be used to restart data planes as well.

**Comment by grantr** [comment]
Also note: during a rolling restart, pod rollover takes at least 30 seconds
