### ISSUE TITLE
WI: Broker Ingress Readiness should depend on getting a valid Credential

### ISSUE THREAD

**Issue by Harwayne** [google/knative-gcp#1709]
**Problem**
We think that spans are getting dropped when the Broker ingress is just starting up in Workload Identity mode. Because the credential is not available for a few seconds, so sending to StackDriver fails.

**Feature Request**
Broker Ingress, when running in WI mode, should have a readiness probe that depends on getting a valid credential from WI. 

**Exit Criteria**
When running in WI mode, the Broker Ingress Pod is not ready until it has a valid credential.

**Comment by grac3gao** [comment]
Related: https://github.com/google/knative-gcp/issues/1058

**Comment by grac3gao** [comment]
fixed by adding the authentication check into the pod
