### ISSUE TITLE
Switch Topic and PullSubscription to use normal pubsub client

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1739]
**Problem**
Topic and PullSubscription reconcilers still use the gpubsub client, making their tests different from the Broker and Trigger tests which use pstest. It would be nice, especially for horizontal features like #1678, if the tests used similar helpers.

**Exit Criteria**
Topic and PullSubscription reconciler code stop using gpubsub, and tests use pstest.

Related to #1430.

/cc @nachocano @Harwayne @zhongduo

**Comment by zhongduo** [comment]
gpubsub has a way to inject errors in a normal client call, eg create new topic or deleting a topic, this is currently not supported in `pstest`, so we will be missing some tests of server error handling.
