### ISSUE TITLE
Reconcile deleted topics created by broker or trigger

### ISSUE THREAD

**Issue by zhongduo** [google/knative-gcp#1749]
**Describe the bug**
Currently if a retry topic is deleted, the trigger reconciler cannot recreate it in minutes. I have tested with 30 mins at least.

 **Expected behavior**
When the resync period is reached, which is 5 mins currently, the deleted topic should be recreated.

 **To Reproduce**
Follow the gcp example, then delete the retry topic, and wait long enough to see if the topic is recreated.

 **Knative-GCP release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by zhongduo** [comment]
This is also discussed in #1430

**Comment by liu-cong** [comment]
It seems there was some recent change to the reesyncPeriod validation logic. I found the following log in my controller:
`W0922 21:37:44.196866       1 shared_informer.go:461] resyncPeriod 300000000000 is smaller than resyncCheckPeriod 36000000000000 and the informer has already started. Changing it to 36000000000000`

The resync is overriden to 10 hours. Need to find the code where the 10 hour limit is set.

**Comment by zhongduo** [comment]
> It seems there was some recent change to the reesyncPeriod validation logic. I found the following log in my controller:
> `W0922 21:37:44.196866 1 shared_informer.go:461] resyncPeriod 300000000000 is smaller than resyncCheckPeriod 36000000000000 and the informer has already started. Changing it to 36000000000000`
> 
> The resync is overriden to 10 hours. Need to find the code where the 10 hour limit is set.

The default reconciler period is 10 hours from Adam, maybe in webhook.

**Comment by zhongduo** [comment]
Found it, `pkg/reconciler/reconciler.go`.

**Comment by zhongduo** [comment]
IIUC, the problem is due to the fact that the actual resync period is rounded up to at lest the `resyncCheckPeriod` which is passed when creating the informer. The actually informer creation is hidden deeply in the injection code:

The injection in the project eventually called this function in `pkg/client/injection/informers/factory/factory.go`:
```

func withInformerFactory(ctx context.Context) context.Context {
	c := client.Get(ctx)
	opts := make([]externalversions.SharedInformerOption, 0, 1)
	if injection.HasNamespaceScope(ctx) {
		opts = append(opts, externalversions.WithNamespace(injection.GetNamespaceScope(ctx)))
	}
	return context.WithValue(ctx, Key{},
		externalversions.NewSharedInformerFactoryWithOptions(c, controller.GetResyncPeriod(ctx), opts...))
}
```

Where `GetResyncPeriod` will check if one is set in context, if no, the k8s default 10 hours is used as the checkedPeriod, which means almost all the `AddEventHandlerWithResyncPeriod` will always has a resync period of at least 10 hours.

**Comment by zhongduo** [comment]
I don't think `resyncPeriod` is the right method for doing this, it seems that what we need is just a topic monitoring at a fixed interval etc. Note that resync operation can be costly as it will try to reconcile all resources, eg 10000 triggers, so we should really investigate other alternative here.

**Comment by grantr** [comment]
@nachocano this might also affect source reconcilers. Seems like we may have a bug in injection-gen with a recent version of client-go.

**Comment by capri-xiyue** [comment]
I tested CloudSchedulerSource with latest knative-gcp.
Verified that CloudSchedulerSource can't recover from Topic deletion now.
Saw error logs in the controller logs of cloud-run-events namespace
`W0929 18:43:26.592792       1 shared_informer.go:461] resyncPeriod 300000000000 is smaller than resyncCheckPeriod 36000000000000 and the informer has already started. Changing it to 36000000000000
`
I believe that's the reason that the non-default resync period does not work.

**Comment by capri-xiyue** [comment]
I verified that knative-gcp release-0.16 works but master is broken.
Did some investigation.
It looks like in knative-gcp release-0.16 and master, the informers start at different time.
In master, the informer starts before source/broker controller starts, therefore, it fails when we try to set non-default resync period.
But in release-0.16,  the informer starts after the source/broker controller starts, we are still able to set the non-default resync period.
