### ISSUE TITLE
Target Test Pod Exits Without Sending HTTP Response Status

### ISSUE THREAD

**Issue by ian-mi** [google/knative-gcp#1751]
**Describe the bug**
The target test pod will sometimes exit after successfully receiving the target event but will not send the response status causing the trigger to get an EOF error.

 **Expected behavior**
The target test pod should send status OK before exiting when receiving the target event.

 **To Reproduce**
This issue causes occasional failures in TestGCPBrokerMetrics.

**Comment by grac3gao** [comment]
[Summary](https://docs.google.com/spreadsheets/d/1foMAzCFvOk07SEvp0uD9lsm4OC-cMJInC3wDndkf7LI/edit?usp=chrome_omnibox&ouid=117204249182022171180) for TestGCPBrokerMetrics failure
