### ISSUE TITLE
Sending a huge event crashes the broker ingress

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1753]
**Describe the bug**
Reported by @Ectelion. An extremely large event causes the broker ingress to crash with OOM.

 **Expected behavior**
Extremely large events don't crash the broker ingress. Events greater than a configured or hardcoded size are rejected with HTTP status code 413 Payload Too Large.

 **To Reproduce**
Send an event payload of multiple gigabytes (not sure exactly how big). 

 **Knative-GCP release version**
HEAD

**Comment by Ectelion** [comment]
Oh, just got an e-mail notification about this and by that time I have also reported it over [here](https://github.com/google/knative-gcp/issues/1754). We can mark that one as a duplicate, but, whoever needs, may refer there for some additional details.
