### ISSUE TITLE
Move PingSource to v1beta2

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#1785]
**Problem**
This is just a duplicate of https://github.com/knative/eventing/issues/4167, so that we can track it in our sprint.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Developer

**Exit Criteria**
PingSource in v1beta2

**Comment by nachocano** [comment]
Fixed by https://github.com/knative/eventing/pull/4474
Closing
