### ISSUE TITLE
Remove dependency on serving v1alpha and v1beta API

### ISSUE THREAD

**Issue by zhongduo** [google/knative-gcp#1801]
**Describe the bug**
The Knative serving has removed support for v1alpha and v1beta, https://github.com/knative/serving/releases

Though the official EOL is 0.19, the master branch has already remove the support, so errors will be encountered when running `./hack/update-deps.sh --upgrade`. Currently the serving repo is pinned to v0.18.0.

 **Expected behavior**

`./hack/update-deps.sh --upgrade` should be able to upgrade to serving master.

 **To Reproduce**
Remove the replace part for knative serving in go.mod if exists, and run `./hack/update-deps.sh --upgrade`.

 **Knative-GCP release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by grantr** [comment]
> ./hack/update-deps.sh --upgrade should be able to upgrade to serving v0.18.1.

I think the exit criterion is that we can upgrade to serving master, not v0.18.1

**Comment by zhongduo** [comment]
> > ./hack/update-deps.sh --upgrade should be able to upgrade to serving v0.18.1.
> 
> I think the exit criterion is that we can upgrade to serving master, not v0.18.1

Thanks for catching it, updated. Also agree this is one of the highest priority items, as any upgrade of knative.dev might fail or introduce unexpected bug now that we are not using master.
