### ISSUE TITLE
Properly implement linear backoff in Broker delivery spec

### ISSUE THREAD

**Issue by tommyreddad** [google/knative-gcp#1832]
**Describe the bug**
The Broker delivery linear backoff policy is incorrectly implemented and actually implements constant backoff, i.e., the same duration is used as a delay between each retry.

 **Expected behavior**
The linear backoff policy should have the delay increase linearly between each retry, i.e., the n-th retry delay should be `backoffDelay*n`.

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative-GCP release version**

 **Additional context**
The Knative Eventing delivery spec had improperly defined linear backoff, which has recently been addressed: https://github.com/knative/eventing/pull/4240#event-3850977200. The current implementation is based on the prior incorrect definition.

The Knative-GCP broker delivery spec implementation is configured through Pub/Sub, which itself only supports exponential backoff using a minimum backoff delay and a maximum backoff delay. A constant backoff policy can be implemented as such by setting the maximum backoff to equal the minimum backoff: see https://github.com/google/knative-gcp/blob/master/docs/spec/delivery.md for a description of the mapping between the Knative Eventing backoff policy and Pub/Sub backoff policy.

There does not seem to be any way to configure Pub/Sub to implement a linear backoff policy, so correctly implementing the Knative backoff policy might require a client-side implementation.

**Comment by tommyreddad** [comment]
As discussed during the sync meeting, we decided not to support linear backoff, and we can reject linear backoff configuration during webhook validation.

**Comment by grantr** [comment]
When we start rejecting linear backoff, we should correct the description of linear backoff in https://github.com/google/knative-gcp/blob/master/docs/spec/delivery.md.
