### ISSUE TITLE
maybe pull-google-knative-gcp-build-tests should skip *_gen.go files?

### ISSUE THREAD

**Issue by nlopezgi** [google/knative-gcp#1852]
**Problem**
Auto generated PRs fo Format Go code (https://github.com/google/knative-gcp/pull/1850) are not getting through.
From that PR:
> Looks like wire doesn't generate properly formatted files according to goimports. Maybe this job should skip *_gen.go files too?

Alternatively we should fix the tooling to generate properly formatted files? 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Developer

**Exit Criteria**
Auto generated PRs can pass.

**Time Estimate (optional):** 
1

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment]
This might be as simple as adding `*_gen.go` to the list of patterns in .gitattributes: https://github.com/google/knative-gcp/blob/master/.gitattributes

**Comment by nlopezgi** [comment]
Tested in PR above and using .gitattributes does not work as intended.

**Comment by grantr** [comment]
Looks like it's not quite that simple. I think we'll need to update the format bot to exclude files with the `linguist-generated` attribute set to `true`.

Currently the format bot uses this find command to get the names of files:
`export FILES=( $(find -path './vendor' -prune -o -path './third_party' -prune -o -name '*.pb.go' -prune -o -type f -name '*.go' -print) )`
(it already attempts to exclude some generated files with `*.pb.go`)

This command gives the list of files in the repo marked as generated:
`GENFILES=$(git ls-files | xargs git check-attr linguist-generated | grep 'true$' | cut -d: -f1)`

I think we'll need to filter the find to exclude the files in that list. Here's one possible way to do that (but haven't tested yet):

`NONGENFILES=$(echo $GENFILES | grep -v -f - $FILES)`

**Comment by nlopezgi** [comment]
This still needs https://github.com/google/knative-gcp/pull/1856/files
