### ISSUE TITLE
Storage creates multiple Notifications

### ISSUE THREAD

**Issue by Harwayne** [google/knative-gcp#186]
Occasionally I see that Storage creates two GCS notifications. Then, when the Storage CO is deleted, only the more recent notifications is deleted. This caused me to hit the limit of 10 notifications on a bucket.

```shell
$ gsutil notification list gs://eventing-demo
# Nothing

$ kn importers create storage desjani --parameters bucket=eventing-demo
# Finishes when the importer is ready.

$ gsutil notification list gs://eventing-demo
projects/_/buckets/eventing-demo/notificationConfigs/67
        Cloud Pub/Sub topic: projects/harwayne2/topics/storage-e711b0c4-f647-4723-be61-99ce59801287
        Custom attributes:
                knative-gcp: google.storage

projects/_/buckets/eventing-demo/notificationConfigs/68
        Cloud Pub/Sub topic: projects/harwayne2/topics/storage-b7cbfa63-a7ba-4f8f-8306-efc574daa7e4
        Custom attributes:
                knative-gcp: google.storage

$ ./kn importers generic delete storage desjani  
# Finishes successfully.

$ gsutil notification list gs://eventing-demo
projects/_/buckets/eventing-demo/notificationConfigs/67
        Cloud Pub/Sub topic: projects/harwayne2/topics/storage-e711b0c4-f647-4723-be61-99ce59801287
        Custom attributes:
                knative-gcp: google.storage
```

**Comment by n3wscott** [comment]
@Harwayne can you try this flow again with the operations ?

**Comment by vaikas-google** [comment]
as @n3wscott mentions, this should not happen again. The problem was that occasionally depending on which write (finalizer or the status update with the notificationId in Status) would go first we would indeed end up getting the duplicate notification. With the operations model, creating the subscription should be idempotent because the state is stored in the Job that creates the Subscription and not in the reconciler.

**Comment by vaikas-google** [comment]
@Harwayne can you still repro this?

**Comment by Harwayne** [comment]
Looking through the code, I think it should be much safer now. 

However, it is still possible if the Pod creating the notification dies at the wrong time. If the Pod dies after https://github.com/google/knative-gcp/blob/master/pkg/operations/storage/notification.go#L228, but before https://github.com/google/knative-gcp/blob/master/pkg/operations/storage/notification.go#L243, or writing the termination message fails for some reason, then we would still leak a Notification.

One possible solution is to set a custom attribute in the notification to the UID of the Storage object. Then, before creating a Storage notification, list the existing ones and search for that UID. If found, then accept it.

**Comment by nachocano** [comment]
I cannot repro this in 0.12... leaving it open for now, but may close it in 0.13 if nobody can reproduce
