### ISSUE TITLE
[Respectful Code]Replace Disrespectful Terms

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1862]
**Problem**
Replace disrespectful terms.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by zhongduo** [comment]
I think native to "" can be a problem to enforce, as our project is.... Knative

**Comment by grac3gao** [comment]
@zhongduo for unavoidable terms, the guidance is to minimize the usage outside of it.

**Comment by grac3gao** [comment]
Summary:

hit -> reach (17 times)
native -> "" (4 times)
dummy -> sample (55 times)
victim -> "" (1 times)
special -> "" (4 times)
health check -> probe check (72 times)
