### ISSUE TITLE
[Respectful Code]Tooling to avoid regressions

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1863]
**Problem**
Tooling to avoid regressions. Mainly for adding a presubmit to avoid regressions in the codebase for disrespectful code.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by nlopezgi** [comment]
Hi @grac3gao thanks for creating this issue,
Could you specify a bit more what kind of regressions you are referring to? If possible, if we have an issue or PR that shows the specific kind of regression you refer to please link it here.
