### ISSUE TITLE
TestCloudAuditLogsSourceBrokerWithPubSubChannel is very flaky

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#1882]
**Describe the bug**
This test has caused several nightly test failures, also noticed this in presubmit tests. Example: https://prow.knative.dev/view/gcs/knative-prow/logs/ci-google-knative-gcp-nightly-release/1321747110059577344

 **Additional context**
Can we just get rid of this test? This test is part of the "conformance" tests for PubSubChannel integration with MT broker. We don't need to include all source types in order to make sure PubSubChannel works.

cc @tommyreddad

**Comment by tommyreddad** [comment]
@liu-cong We currently have the following conformance tests:
- TestEventTransformationForTrigger
- TestBrokerChannelFlow
- TestBrokerWithPubSubChannel
- TestCloudPubSubSourceBrokerWithPubSubChannel
- TestCloudStorageSourceBrokerWithPubSubChannel
- TestCloudAuditLogsSourceBrokerWithPubSubChannel
- TestCloudSchedulerSourceBrokerWithPubSubChannel

I'm not sure how valuable it is to keep any of the source tests, and in particular as you have noticed the CloudAuditLogsSource test is flaky. If we had to keep one, in my mind it would be the CloudPubSubSource test. So, I propose we drop a few and only keep:
- TestEventTransformationForTrigger
- TestBrokerChannelFlow
- TestBrokerWithPubSubChannel
plus-or-minus TestCloudPubSubSourceBrokerWithPubSubChannel.

Thoughts?

**Comment by liu-cong** [comment]
@tommyreddad 

SGTM. Do you know what each of "TestEventTransformationForTrigger", "TestBrokerChannelFlow","TestBrokerWithPubSubChannel" does exactly? Just from the name it looks there might be some duplication there as well.

**Comment by tommyreddad** [comment]
- TestEventTransformationForTrigger:
  - Same as the knative/eventing test with the same name, using MTBroker backed by PubSubChannel rather than InMemoryChannel. Uses the knative/eventing test library.
  -  A diagram explains the test flow:
```go
/*
TestEventTransformationForTrigger tests the following scenario:

                         5                 4
                   ------------- ----------------------
                   |           | |                    |
             1     v	 2     | v        3           |
EventSource ---> Broker ---> Trigger1 -------> Service(Transformation)
                   |
                   | 6                   7
                   |-------> Trigger2 -------> Service(Logger)

Note: the number denotes the sequence of the event that flows in this test case.
*/
```
- TestBrokerChannelFlow:
  - Same as the knative/eventing test with the same name, using MTBroker backed by PubSubChannel rather than InMemoryChannel. Uses the knative/eventing test library.
  - A diagram explains the test flow:
```go
/*
TestBrokerChannelFlow tests the following topology:

                   ------------- ----------------------
                   |           | |                    |
                   v	       | v                    |
EventSource ---> Broker ---> Trigger1 -------> Service(Transformation)
                   |
                   |
                   |-------> Trigger2 -------> Service(Logger1)
                   |
                   |
                   |-------> Trigger3 -------> Channel --------> Subscription --------> Service(Logger2)

Explanation:
Trigger1 filters the orignal event and transforms it to a new event,
Trigger2 logs all events,
Trigger3 filters the transformed event and sends it to Channel.

*/
```
- TestBrokerWithPubSubChannel:
  - Appears to be a knative-gcp implementation of the knative/eventing TestBrokerChannelFlow test.
  - A diagram explains the test flow:
```go
/*
PubSubWithBrokerTestImpl tests the following scenario:

                              5                   4
                    ------------------   --------------------
                    |                 | |                    |
          1         v	      2       | v         3          |
(Sender or Source) ---> Broker(PubSub) ---> trigger -------> Knative Service(Receiver)
                    |
                    |    6                   7
                    |-------> respTrigger -------> Service(Target)

Note: the number denotes the sequence of the event that flows in this test case.
*/
```

It looks like TestBrokerWithPubSubChannel is redundant and could be removed.
