### ISSUE TITLE
Possible bug in trigger event count

### ISSUE THREAD

**Issue by zhongduo** [google/knative-gcp#1920]
**Describe the bug**
During the upgrade test, I found that the broker event count is not the same as sum of all the trigger event counts. Note that the receiver pod does receive all the events as the broker event count, so there is a possibility that we didn't record all the trigger event counts.

 **Expected behavior**
Broker event count should be same as sum of all trigger event count in stackdriver.

 **To Reproduce**
Run the upgrade test, then check the number of event counts for broker and triggers.

 **Knative-GCP release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by Harwayne** [comment]
The description of the bug is a bit ambiguous. Was the test set up such that every event sent to the Broker should pass the only Trigger's filter? Or that every event sent into the Broker passes exactly one Trigger's filter? 

Which was greater, the Broker's event_count or Sum(Trigger event_count)?

---

The Broker's event_count and sum of all the Trigger event_counts for that Broker do not need to equal each other.

#### Broker event_count > Sum(Trigger event_count)

I send 1 event to the Broker and that event does not pass the filter for any of my 5 Triggers.
Broker event_count = 1
Sum(Trigger event_count) = 0

#### Broker event_count < Sum(Trigger event_count)

I send 1 event to the Broker and that event passes the filter for all of my 5 Triggers.
Broker event_count = 1
Sum(Trigger event_count) = 5

#### Broker event_count < Trigger event_count

I send 1 event to the Broker and that event passes the filter for my 1 Trigger. However, the initial delivery fails because the downstream service returns a 503. On the next attempt, the Trigger successfully sends the event to the downstream service, which returns a 202.

Broker event_count = 1
Trigger event_count = 2

**Comment by zhongduo** [comment]
Broker event_count > Sum(Trigger event_count)

The difference is about missing 300 events.

**Comment by zhongduo** [comment]
There are two triggers, `step` gets almost all the events from broker, `finished` gets only one.

**Comment by grantr** [comment]
@quentin-cha

**Comment by Harwayne** [comment]
@zhongduo and I talked, this issue is reproducible via the `TestEventingUpgrades` E2E test. 

There is a Broker which is being sent events continuously at roughly 30 QPS. Each event going into the Broker should match a single Trigger's filter, all of which point to a receiver Pod. At the end of the test, the Broker event_count is 4200, which exactly matches the number of events seen by the receiver Pod. However, the Sum(Trigger event_count) is only 3900. Which is very odd as it should be at least as large as the number of events seen by the receiver Pod.

**Comment by Harwayne** [comment]
Because the Pods were restarting, I thought it might have something to do with not flushing properly in the fanout/retry Pods, but from what I can see, the ingress, fanout, and retry Pods all flush metrics in the exact same way.

**Comment by Harwayne** [comment]
As far as I can tell this line is the only place a Trigger sends an event to the subscriber:

https://github.com/google/knative-gcp/blob/2ef4ca1b39478f1d423b167a0c1e37ab62f495f2/pkg/broker/handler/processors/deliver/processor.go#L151

The only way to get out of that function without calling `p.StatsReporter.ReportEventDispatchTime`, which is what increments the event_count metric, is if that line returns a non-nil error that is not a timeout.

https://github.com/google/knative-gcp/blob/2ef4ca1b39478f1d423b167a0c1e37ab62f495f2/pkg/broker/handler/processors/deliver/processor.go#L151-L159

But even if that happens, the Trigger should retry the event, which would result in the same code being called again and once the event is sent successfully, `p.StatsReporter.ReportEventDispatchTime` is called, which would increment `event_count`.

**Comment by quentin-cha** [comment]
Reran the test (`TestEventingUpgrades`) a couple of times and confirmed the issue. 
Observations so far:
- There is always a difference between the Broker event count and Trigger event count.
- Trigger event count is always less than Broker event count.
- The delta amount varies from run to run.

Investigate
- make sure triggers have a chance to report all counts before test tear down
- add logging to figure out the number of invocations made to Broker and Trigger event count

**Comment by quentin-cha** [comment]
Observation update:
- broker event count doesn't always have the correct count, and sometimes the trigger event count is higher than the broker event count.
- added log around where the broker event count and trigger event count are being recorded
https://github.com/google/knative-gcp/blob/eae120d016abff5a176662a9329e3456e64970f0/pkg/broker/ingress/handler.go#L234
https://github.com/google/knative-gcp/blob/eae120d016abff5a176662a9329e3456e64970f0/pkg/broker/handler/processors/deliver/processor.go#L156
https://github.com/google/knative-gcp/blob/eae120d016abff5a176662a9329e3456e64970f0/pkg/broker/handler/processors/deliver/processor.go#L173
after counting the number of times these logs appear, they **match** with the expected event count reported by the prober. 
- added log around exporter flushing
https://github.com/google/knative-gcp/blob/eae120d016abff5a176662a9329e3456e64970f0/pkg/observability/observability.go#L52
observed that the Flushing is **being invoked during redeployment**.

Conclusion so far:
- the actual broker and trigger event count are being recorded correctly based on the log instance count.
- pods do have the chance to invoke flushing before being killed.

**Comment by quentin-cha** [comment]
After some more investigation, a possible theory is that:

When we record metrics, the metrics themselves do not get pushed into the bundlers right away, instead, they are stored in intermediaries call views:
https://github.com/google/knative-gcp/blob/3fc6d6f43caca85fa04ff85b231f7a414d74b010/vendor/go.opencensus.io/stats/view/worker_commands.go#L166

There is a separate mechanism that periodically puts these view data into bundler:
https://github.com/google/knative-gcp/blob/3fc6d6f43caca85fa04ff85b231f7a414d74b010/vendor/knative.dev/pkg/metrics/stackdriver_exporter.go#L173
https://github.com/google/knative-gcp/blob/3fc6d6f43caca85fa04ff85b231f7a414d74b010/vendor/contrib.go.opencensus.io/exporter/stackdriver/stats.go#L139
https://github.com/google/knative-gcp/blob/3fc6d6f43caca85fa04ff85b231f7a414d74b010/vendor/go.opencensus.io/metric/metricexport/reader.go#L148
This is where the metrics actually get into the bundler to be exported:
https://github.com/google/knative-gcp/blob/3fc6d6f43caca85fa04ff85b231f7a414d74b010/vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics.go#L52

So after the metric is recorded and before the reader puts it into the bundler, the metric is essentially 'in-flight' within the system.
If the pod were to terminate, flushing of the bundlers are initiated:
https://github.com/google/knative-gcp/blob/3fc6d6f43caca85fa04ff85b231f7a414d74b010/pkg/observability/observability.go#L52
https://github.com/google/knative-gcp/blob/3fc6d6f43caca85fa04ff85b231f7a414d74b010/vendor/contrib.go.opencensus.io/exporter/stackdriver/stats.go#L202

Notice how flushing only flushes the bundlers, so there is a chance that the reader has not pushed the metrics from view into those bundlers ('in-flight metrics'). This will likely lead to one interval of metrics being essentially discarded.

**Comment by zhongduo** [comment]
Does this explain why the broker always has the right number?

**Comment by quentin-cha** [comment]
Based on what I have seen during the investigation, broker event counts can also be off. So the root cause would most likely be in the common layers.

**Comment by zhongduo** [comment]
It might be a coincidence in this case then. My previous experience has
always been that the broker is getting the right number *when the test
succeeds.*

**Comment by Harwayne** [comment]
@quentin-cha found the root cause to be OpenCensus not flushing all metric buffers on process shutdown. https://github.com/census-instrumentation/opencensus-go/pull/1248 was made to add an API to flush this buffer.

/unassign

**Comment by grantr** [comment]
Looks like that PR was merged. When can we get the fix into this repo?

**Comment by grantr** [comment]
Also thanks @quentin-cha for tracking this down!

**Comment by quentin-cha** [comment]
No worries. 
A couple more PRs needs to happen for the change to propagate to here.
The second PR just got approved: https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/282
There will be at least two more PRs, one in knative/pkg and one in this repo.
I will close this when all the PRs are merged.
