### ISSUE TITLE
Set the correct value for SYSTEM_NAMESPACE

### ISSUE THREAD

**Issue by AlexandraRoatis** [google/knative-gcp#1958]
**Describe the bug**
The stated assumption seems to be that `SYSTEM_NAMESPACE`/`system.Namespace()` is set to `cloud-run-events`.
However, there are instance where it is defined as `knative-eventing` or `knative-testing`, e.g.:
- https://github.com/google/knative-gcp/blob/38d5ca803ff48e839b248963506cf527e8ef6d4b/test/lib.sh#L20
- https://github.com/google/knative-gcp/blob/38d5ca803ff48e839b248963506cf527e8ef6d4b/pkg/reconciler/brokercell/testingdata/fanout_deployment.yaml#L64-L65
- https://github.com/google/knative-gcp/blob/38d5ca803ff48e839b248963506cf527e8ef6d4b/pkg/reconciler/brokercell/testingdata/retry_deployment_with_status.yaml#L65-L66
- https://github.com/google/knative-gcp/blob/38d5ca803ff48e839b248963506cf527e8ef6d4b/pkg/reconciler/brokercell/testingdata/retry_deployment_with_restart_annotation.yaml#L66-L67
- https://github.com/google/knative-gcp/blob/38d5ca803ff48e839b248963506cf527e8ef6d4b/pkg/reconciler/brokercell/testingdata/ingress_deployment_with_status.yaml#L74-L75
- https://github.com/google/knative-gcp/blob/38d5ca803ff48e839b248963506cf527e8ef6d4b/pkg/reconciler/brokercell/testingdata/ingress_deployment_with_restart_annotation.yaml#L75-L76
- https://github.com/google/knative-gcp/blob/38d5ca803ff48e839b248963506cf527e8ef6d4b/pkg/reconciler/brokercell/testingdata/ingress_deployment_with_filtering_annotation.yaml#L76-L77

 **Expected behavior**
A clear specification of what is the value assigned to `SYSTEM_NAMESPACE`/`system.Namespace()`.

**Comment by grantr** [comment]
The testingdata ones can remain `knative-testing`, that value is independent of any value outside tests.

**Comment by MohamedElhawaty** [comment]
The `system.Namespace()` value can either be:

* initialized as an environment variable. 
* set to `knative-testing` by importing `"knative.dev/pkg/system/testing"`

So in unit tests, if we don't `import _ "knative.dev/pkg/system/testing"`, a panic would be raised:

```
If this is a process running on Kubernetes, then it should be using the downward
API to initialize this variable via:

  env:
  - name: %s
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace

If this is a Go unit test consuming system.Namespace() then it should add the
following import:

import (
	_ "knative.dev/pkg/system/testing"
)
```

**Comment by MohamedElhawaty** [comment]
The one in `lib.sh` should be set to `knative-eventing` as well. It was added as part of this [PR](https://github.com/google/knative-gcp/pull/1867).

As per my discussion with @tommyreddad, eventing test library depends on `system.Namespace()` in `pkg/system` and needs this value to point to the namespace in which Knative Eventing is installed

**Comment by nlopezgi** [comment]
Is there anything pending or can this be closed?

**Comment by MohamedElhawaty** [comment]
This could be closed now. 

According to https://github.com/knative/eventing/issues/4626#issuecomment-740080407 eventing is using this `SYSTEM_NAMESPACE="knative-eventing"` for find eventing configmaps like config-tracing.
