### ISSUE TITLE
Document Broker data plane on docs/install/authentication-mechanisms-gcp.md

### ISSUE THREAD

**Issue by Harwayne** [google/knative-gcp#1972]
**Describe the bug**
docs/install/authentication-mechanisms-gcp.md describes the control plane and sources data plane, but does not mention the Broker data plane. 

 **Expected behavior**
Broker data plane should also be documented.

**Comment by grac3gao** [comment]
@Harwayne Broker’s instruction is in https://github.com/google/knative-gcp/blob/master/docs/install/install-gcp-broker.md, we set the broker as an independent part. Shall I add the link in installation doc for that or combine it to the installation doc?

**Comment by Harwayne** [comment]
At the very least we should update  https://github.com/google/knative-gcp/blob/master/docs/install/authentication-mechanisms-gcp.md to state that it is setting up the source data plane (rather than the current implication of the entire data plane), and we should link to the install-gcp-broker docs.
