### ISSUE TITLE
Properly tear down knative related installation 

### ISSUE THREAD

**Issue by cathyzhyi** [google/knative-gcp#1991]
**Describe the bug**
In e2e-secret-tests.sh `knative_teardown` overwrites the original definition https://github.com/google/knative-gcp/blob/6d964ddaae98f1c3ed062e39145f25e9fc5165c6/test/e2e-secret-tests.sh#L59 and just removes some temp file. However, the original `knative_teardown` defined in https://github.com/google/knative-gcp/blob/6d964ddaae98f1c3ed062e39145f25e9fc5165c6/vendor/knative.dev/eventing/test/e2e-common.sh#L249 does more complicated job and uninstall things properly. 

Similar for `test_teardown`:
our definition  https://github.com/google/knative-gcp/blob/6d964ddaae98f1c3ed062e39145f25e9fc5165c6/test/e2e-common.sh#L44 
original definition https://github.com/google/knative-gcp/blob/6d964ddaae98f1c3ed062e39145f25e9fc5165c6/vendor/knative.dev/eventing/test/e2e-common.sh#L300

 **Expected behavior**
Maybe we should also uninstall resources properly as the original definition does?

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative-GCP release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by zhongduo** [comment]
The `test_teardown` in eventing is to uninstall the channel CRD, which is not applicable in knative-gcp. `knative-teardown` however removes the system namespace, which knative-gcp will have problem due to the dependency of webhook and brokercell in the same namespace. The whole teardown is not very important as the Prow job will remove the whole cluster after the test, but not sure what people will expect in local test.

**Comment by cathyzhyi** [comment]
I thought the `knative_teardown` in knative-gcp needs to cleanup knative-gcp related resources and then do whatever the original `knative_teardown` in e2e-common.sh does to cleanup eventing related resources.

**Comment by nlopezgi** [comment]
Hey @zhongduo do you know more about @cathyzhyi followup Q?

**Comment by zhongduo** [comment]
I agree to teardown the resources properly. If you are going to uninstall `knative-gcp`, just make sure you remove the webhook in the last step rather than removing the namespace directly. Having said that, the teardown process is not tested in Prow jobs as the whole cluster will be deleted.

**Comment by cathyzhyi** [comment]
I just feel surprising when noticing this and want to raise the issue to make sure it's not unintentional. If the testing team believes this is not an issue I can close it.
