### ISSUE TITLE
Add e2e test for detecting naming conflicts between knative-gcp and other components

### ISSUE THREAD

**Issue by cathyzhyi** [google/knative-gcp#1994]
**Problem**
Need an e2e test to verify that no cluster-scoped or namespaced objects installed by knative-gcp have the same name as other objects

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
add e2e test to verify that no cluster-scoped or namespaced objects installed have the same name as other objects

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
In https://github.com/google/knative-gcp/issues/1824, we found both knative-gcp and eventing have clusterrole called `addressable-resolver`. The clusterrole in knative-gcp will overrride the clusterrole with the same name.

**Comment by nlopezgi** [comment]
Some Qs about this issue:
- What is the impact of having duplicates, afaik, our release process should clean them up
- It does not seem to me that an e2e test is necessarily the best way to test for this, is there a better alternative that you know maybe?

**Comment by cathyzhyi** [comment]
> Some Qs about this issue:
> 
> * What is the impact of having duplicates, afaik, our release process should clean them up

I think we want to avoid unintentionally overwrite any installed object. This is the original issue where knative-gcp overwrites cluster roles defined by eventing https://github.com/google/knative-gcp/issues/1824 by mistake. 

> * It does not seem to me that an e2e test is necessarily the best way to test for this, is there a better alternative that you know maybe?

I don't know about other alternatives but here is an e2e test I come up with https://github.com/google/knative-gcp/pull/1995. Not sure if testing team has other suggestions.

**Comment by nlopezgi** [comment]
thanks for the additional info!
