### ISSUE TITLE
knative trigger status Unknown due to TopicReady Unknown

### ISSUE THREAD

**Issue by Uvindu96** [google/knative-gcp#2011]
**Describe the bug**
Recently I'm trying out the Knative sample https://github.com/meteatamel/knative-tutorial/blob/master/docs/image-processing-pipeline.md, I have created knative trigger with default broker(MTChannelBasedBroker) & trigger, I have also installed the Google Cloud Pub/Sub Channel in the same namespace. I'm not sure what causes this error.
![Screenshot from 2020-12-21 21-56-10](https://user-images.githubusercontent.com/31029812/102801024-af6cb280-43da-11eb-8445-4565faaa101f.png)

 **Expected behavior**
Trigger should be ready

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative-GCP release version**
v0.18

**Comment by Uvindu96** [comment]
Is there any solution for this?

**Comment by zhongduo** [comment]
This typically means authentication problem to Cloud resource, which in this case is Google Pub/Sub. Can you try if this help: https://github.com/google/knative-gcp/blob/master/docs/install/authentication-mechanisms-gcp.md#option-2-kubernetes-secrets

**Comment by Uvindu96** [comment]
@zhongduo Thanks for the response, I tried the Kubernetes secrets option but I keep getting the same issue with the trigger.

![Screenshot from 2020-12-30 20-33-06](https://user-images.githubusercontent.com/31029812/103363375-fba5aa00-4ae0-11eb-8f94-ae7e80524cde.png)


Steps Followed

1. Install both Knative serving and eventing (v0.18).
2. Install Knative GCP (From GitHub release version 0.18).
3. Configured and authenticate the control plane manually (https://github.com/google/knative-gcp/blob/master/docs/install/authentication-mechanisms-gcp.md/#authentication-mechanism-for-the-control-plane)
4. Install service account for the data plane manually (https://github.com/google/knative-gcp/blob/master/docs/install/dataplane-service-account.md#create-a-google-cloud-service-account-to-interact-with-pubsub)
5. Authenticate the Data plane (https://github.com/google/knative-gcp/blob/master/docs/install/authentication-mechanisms-gcp.md/#option-2-export-service-account-keys-and-store-them-as-kubernetes-secrets)
6. Then tried this sample (https://github.com/meteatamel/knative-tutorial/blob/master/docs/storageeventing.md)

For the trigger, I got the same issue, I'm not sure what wrong :(

**Comment by zhongduo** [comment]
There is no `google-broker-key`, can you also do it by following: https://github.com/google/knative-gcp/blob/master/docs/install/install-gcp-broker.md#option-2-export-service-account-keys-and-store-them-as-kubernetes-secrets

**Comment by Uvindu96** [comment]
@zhongduo I have created the google-broker-key as you requested, but It didn't help :(. Still, my trigger is in an unknown state. I'm followed each step can't find what is missing :( 

![Screenshot from 2020-12-31 00-08-31](https://user-images.githubusercontent.com/31029812/103374300-3fa6a800-4afd-11eb-9c4a-830b2c0f676c.png)

This is the trigger file -:
![Screenshot from 2020-12-31 00-16-32](https://user-images.githubusercontent.com/31029812/103374487-bb085980-4afd-11eb-8cc4-58063cbaf0f6.png)

**Comment by Uvindu96** [comment]
I want to add another thing, for the sample I'm following, It's using the default broker, not the GCP broker.

**Comment by Uvindu96** [comment]
@zhongduo Thank you yes auth is the issue here

**Comment by zhongduo** [comment]
Awesome, great it helps. Auth is a big feature that GCP supports for real
production, but it does get a little bit tricky at the beginning. If
possible can you please update the original material you were following to
point to the solution?

**Comment by Uvindu96** [comment]
@zhongduo I tried so many times to setup GCP for knative and always I failed, actually, for starters, even the Knative GCP setup documentation is a bit complex, it helps if you can more simplify the process. I need to include one more thing automated scripts didn't work for me when setting up the Knative GCP, I always like Kubernetes secret option. But finally, I used the setup config file used to setup the kative in the tutorial (https://github.com/meteatamel/knative-tutorial/tree/master/setup). This worked fine for me.

**Comment by zhongduo** [comment]
I agree that the doc can be enhanced. We are actively working on improving
the tutorial and documentation for both the release version of knative-gcp
on GKE and open source knative-gcp. If you are having trouble with the doc,
you can simply open an issue like this and someone will help you for sure.

Here is a quick start for the release version:
https://cloud.google.com/kuberun/docs/events/quickstart

Here is a simple GCP broker installation for knative-gcp:
https://github.com/google/knative-gcp/tree/master/docs/examples/gcpbroker

**Comment by nlopezgi** [comment]
Is there anything pending here or can this issue be closed?

**Comment by Uvindu96** [comment]
@nlopezgi This issue is resolved you can close this.

**Comment by nlopezgi** [comment]
Thanks!
