### ISSUE TITLE
Make round trip duck test for Storage API

### ISSUE THREAD

**Issue by n3wscott** [google/knative-gcp#204]
Re: https://github.com/google/knative-gcp/pull/203/files#r316266232

I guess there is something to do with performance or whatever so serving has been making this test instead of doing the asserts like above: https://github.com/google/knative-gcp/blob/master/pkg/apis/pubsub/v1alpha1/implements_test.go#L26

it lets you test round trips in json form so that is useful.

_Originally posted by @n3wscott in https://github.com/google/knative-gcp/pull/203/review_comment/create_

**Comment by vaikas-google** [comment]
done
