### ISSUE TITLE
Require upgrade tests after the namespace change is in a release

### ISSUE THREAD

**Issue by AlexandraRoatis** [google/knative-gcp#2047]
**Problem**
The upgrade tests were made optional in https://github.com/knative/test-infra/pull/2619 to accommodate merging the namespace change from `cloud-run-events` to `events-system` (https://github.com/google/knative-gcp/pull/1917).

**Exit Criteria**
The tests should be changed back to required once the first release with the new namespace is published.

**Comment by zhongduo** [comment]
done in knative/test-infra#2628
