### ISSUE TITLE
#Bug Updating the event types of an GCS importer doesn't work and is not immutable

### ISSUE THREAD

**Issue by akashrv** [google/knative-gcp#207]
Create a GCS importer with just the "finalize" event type.
Then edit it to add "metadataupdate". Webhook accepts it and the object is ready.
However, gsutil notification list <bucketurl> doesn't show the new type. (also old ones stay forever, but I believe there is another bug tracking it).

I haven't tested for other fields. 

Expected behavior:
Either make the field immutable, or reconcile (ideal) it.

**Comment by vaikas-google** [comment]
Looks like GCS notification is not updateable (or at least I couldn't find an API for it). So, we could do couple of things:
 1. delete/create the subscription
 2. make it immutable

for the first option probably better to create a new Notification first, then after it has been successfully created remove the old one. I'll think about this some more.

**Comment by nachocano** [comment]
let's make it immutable for now

**Comment by nachocano** [comment]
/assign @nlopezgi 

This has been opened for a while. It would be nice if we can make eventTypes immutable... I haven't seen the code, but some other things might need to be immutable as well...
