### ISSUE TITLE
Metrics around Trigger Replies

### ISSUE THREAD

**Issue by Harwayne** [google/knative-gcp#2117]
**Problem**
We have metrics for Triggers sending events to the subscriber, `event-count` and `dispatch-latency`. But we don't have any metrics around sending replies back into the Broker. After #2107, if the Trigger's reply request does not succeed, the overall delivery is considered a failure and the event is sent to the subscriber again. We need to have metrics so that the user understands what went wrong.

**Exit Criteria**
Triggers expose metrics around sending replies to the Broker's Ingress.

**Additional context (optional)**
- I believe `event-count` is all that is really required, but `dispatch-latency` may also be useful too.
- This will likely need to be added knative/eventing Broker's spec.

**Comment by bharattkukreja** [comment]
Doesn't this correspond to filtering out 2xx responses and summing the values in a group by clause containing all the labels apart from response_code/response_code_class?

**Comment by bharattkukreja** [comment]
Created a similar issue in knative/eventing: https://github.com/knative/eventing/issues/4831

**Comment by Harwayne** [comment]
> Doesn't this correspond to filtering out 2xx responses and summing the values in a group by clause containing all the labels apart from response_code/response_code_class?

I don't think so. The only events that would affect `reply-event-count` are those that already are in the 2xx status code of `event-count`, because the only way a reply is even attempted is if the request to the subscriber succeeds and it replies with an event. 

Essentially, the flow of the event is something like:
1. An event is sent to the Broker and goes to this Trigger.
2. This Trigger sends the event to the subscriber.
3. The subscriber responds with a 200 and a cloud event.
    - This is added to the `event-count` and `dispatch-latency` metrics.
4. The Trigger sends the replied event to the reply address.
5. The reply address responds with some status code.
    - This is added to the `reply-event-count` metric, suggested in this issue (name is just an example, not a real suggestion).
