### ISSUE TITLE
Knative Eventing sample for Java Spring with Cloud Storage Events 

### ISSUE THREAD

**Issue by Uvindu96** [google/knative-gcp#2194]
**Problem**
Hi all,

I'm doing a project using Knative and GCP cloud events. And I need to read cloud events that from GCP storage buckets. as an example,
      "object-finalize-event" -> broker -> trigger -> Spring application
So, are there any examples that I can refer to? this could be really helpful for me.

**Comment by zhongduo** [comment]
This is an example of cloud storage -> event sink: https://github.com/google/knative-gcp/tree/main/docs/examples/cloudstoragesource
This is an example of using broker and trigger: https://github.com/google/knative-gcp/tree/main/docs/examples/gcpbroker

Note that if your application is in Cloud Run, you might also want to try Eventarc: https://cloud.google.com/blog/topics/developers-practitioners/eventarc-unified-eventing-experience-google-cloud

**Comment by Uvindu96** [comment]
thank you @zhongduo
