### ISSUE TITLE
Event Display shows errors in its output for Extensions

### ISSUE THREAD

**Issue by vaikas-google** [google/knative-gcp#224]
When using Event Display (which uses Cloud SDK), both Storage and Scehduler examples show errors in the output:
For example:
☁️  cloudevents.Event
Validation: valid
Context Attributes,
  specversion: 0.3
  type: google.storage.object.finalize
  source: //storage.googleapis.com/buckets/vaikasvaikas-notification-test
  subject: testfilehere
  id: 710717795564381
  time: 2019-08-27T16:35:03.742Z
  schemaurl: https://raw.githubusercontent.com/google/knative-gcp/master/schemas/storage/schema.json
  datacontenttype: application/json
Extensions,
  error: unexpected end of JSON input

**Comment by n3wscott** [comment]
Fixed.
/close
