### ISSUE TITLE
Need to add finalizer to the secret used for Topic and PullSubscriptions.

### ISSUE THREAD

**Issue by n3wscott** [google/knative-gcp#281]
We can get into the state of a namespace is deleted, the first thing to delete is the secret and then the topic and subscriptions can not be cleaned up, so the finalizers just stick around on those resources.

**Comment by yolocs** [comment]
@Harwayne  Would it be possible to add finalizer per topic/subscription to the secret?

**Comment by Harwayne** [comment]
> @Harwayne Would it be possible to add finalizer per topic/subscription to the secret?

I'm not sure. I _think_ we would run into problems when there are 100s-1000s of finalizer entries. We might have the same problem if we add Owner References for each Topic/PullSubscription as well. @n3wscott would likely have a better idea of the scaling limits of K8s resources.
