### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS in e2e-common.sh needs to be updated

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#290]
When doing integration test in RROW, the storage e2e test will fail.

Error message: googleapi: Error 403: The service account 'service-758498956531@gs-project-accounts.iam.gserviceaccount.com' does not have permission to publish messages to to the Cloud Pub/Sub topic '//pubsub.googleapis.com/projects/knative-boskos-68/topics/storage-54292b44-d992-11e9-a940-42010a800073', or that topic does not exist., forbidden). 

However, it works locally.

Root cause:
In e2e-common.sh:
If it is not in PROW, we create a new service account, give it required pubsub.publisher and storage.admin permissions, and create secret with its key. 
If it is in PROW, we use GOOGLE_APPLICATION_CREDENTIALS instead of creating a new service account.

It seems GOOGLE_APPLICATION_CREDENTIALS doesn't have required permission, and needs to be updated.

Note: Tried to create new service account in PROW (same as run it locally), got error:
(gcloud.projects.add-iam-policy-binding) User [prow-job@knative-tests.iam.gserviceaccount.com] does not have permission to access project [knative-boskos-37:setIamPolicy] (or it may not exist): The caller does not have permission
https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/google_knative-gcp/283/pull-google-knative-gcp-integration-tests/1174413811340283906
So this way doesn't work.

**Comment by n3wscott** [comment]
are you sure you have done step 6
<https://github.com/google/knative-gcp/tree/master/docs/storage>:

Give Google Cloud Storage permissions to publish to GCP Pub/Sub.

   1.

   First find the Service Account that GCS uses to publish to Pub/Sub
   (Either using UI or using curl as shown below)
   1.

      Use the steps outlined in Cloud Console or the JSON API
      <https://cloud.google.com/storage/docs/getting-service-account> Assume
      the service account you found from above was
      service-XYZ@gs-project-accounts.iam.gserviceaccount.com, you'd do: shell
      export GCS_SERVICE_ACCOUNT=
      service-XYZ@gs-project-accounts.iam.gserviceaccount.com
      2.

      Use curl to fetch the email:

   export GCS_SERVICE_ACCOUNT=`curl -s -X GET -H "Authorization:
Bearer \`GOOGLE_APPLICATION_CREDENTIALS=./cloudrunevents-pullsub.json
gcloud auth application-default print-access-token\`"
"https://www.googleapis.com/storage/v1/projects/$PROJECT_ID/serviceAccount"
| grep email_address | cut -d '"' -f 4`

   1.

      Then grant rights to that Service Account to publish to GCP Pub/Sub.

      gcloud projects add-iam-policy-binding $PROJECT_ID \
        --member=serviceAccount:$GCS_SERVICE_ACCOUNT \
        --role roles/pubsub.publisher


-Scott

**Comment by grac3gao** [comment]
Have included in https://github.com/google/knative-gcp/pull/283/files/4a038ebeacf7fc992a7c3556f2f3fb7ea371a202#diff-bd936cfe1323838e9372afd0ae4135a3R99-R103

**Comment by grac3gao** [comment]
contacted test-infra
