### ISSUE TITLE
Performance test for PubSub Channel

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#310]
We need a perf test, similar to the ones in knative/eventing and eventing-contrib, that measures latency and throughput of the PubSub Channel and records results in Mako.

**Comment by grantr** [comment]
This should test with a Broker.

**Comment by chizhg** [comment]
The benchmarks are now up and running:
https://mako.dev/benchmark?benchmark_key=6592390798245888&tseconds=604800
https://mako.dev/benchmark?benchmark_key=6246352530964480&tseconds=604800

/close
