### ISSUE TITLE
PullSubscription docs need cluster-local-gateway

### ISSUE THREAD

**Issue by meteatamel** [google/knative-gcp#321]
PullSubscription requires cluster-local-gateway for Knative service sinks. We should mention this in the docs somewhere

**Comment by vaikas-google** [comment]
https://github.com/knative/docs/issues/1842

**Comment by n3wscott** [comment]
Only if istio is installed.

**Comment by vaikas-google** [comment]
This has been updated in the docs and cherry picked to 0.9 documents.
