### ISSUE TITLE
Topic can't be deleted in a Terminating Namespace

### ISSUE THREAD

**Issue by Harwayne** [google/knative-gcp#327]
Related to #281.

Deleting a namespace puts that namespace into TERMINATING, tries to delete everything inside it, and blocks any new resources from being created in that namespace. According to https://github.com/eBay/Kubernetes/blob/master/docs/design/namespaces.md#phases (this is years old, but we couldn't find anything more recent), the NS is immediately put into the Terminating phase when the deletion timestamp exists. And "Admission control blocks creation of new resources in that namespace". 

The current design of Topic requires that when a Topic is deleted, a Job is created (to delete the GCP Cloud PubSub Topic). So when I delete a namespace with a Topic in it, the Topic is marked for deletion, but can never make progress.

```shell
Name:         cre-reply-ch-chan
Namespace:    includes-incoming-trace-id-mhlk5
Labels:       events.cloud.run/channel=cloud-run-events-channel-controller
              events.cloud.run/channel-name=reply-ch
              events.cloud.run/controller-uid=17633f18-e955-11e9-b584-42010a800089
Annotations:  <none>
API Version:  pubsub.cloud.run/v1alpha1
Kind:         Topic
Metadata:
  Creation Timestamp:             2019-10-07T22:52:08Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2019-10-07T22:56:54Z
  Finalizers:
    cloud-run-events-pubsub-topic-controller
  Generation:  2
  Owner References:
    API Version:           messaging.cloud.run/v1alpha1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Channel
    Name:                  reply-ch
    UID:                   17633f18-e955-11e9-b584-42010a800089
  Resource Version:        28963734
  Self Link:               /apis/pubsub.cloud.run/v1alpha1/namespaces/includes-incoming-trace-id-mhlk5/topics/cre-reply-ch-chan                                                                           
  UID:                     1766bce7-e955-11e9-91f5-42010a8000ac
Spec:
  Propagation Policy:  CreateDelete
  Secret:
    Key:   key.json
    Name:  google-cloud-key
  Topic:   cre-chan-17633f18-e955-11e9-b584-42010a800089
Status:
  Address:
    Hostname:  cre-reply-ch-chan-publish.includes-incoming-trace-id-mhlk5.svc.cluster.local
    URL:       http://cre-reply-ch-chan-publish.includes-incoming-trace-id-mhlk5.svc.cluster.local
  Conditions:
    Last Transition Time:  2019-10-07T22:52:17Z
    Status:                True
    Type:                  Addressable
    Last Transition Time:  2019-10-07T22:52:17Z
    Status:                True
    Type:                  PublisherReady
    Last Transition Time:  2019-10-07T22:56:54Z
    Message:               Failed to delete topic: "jobs.batch \"pubsub-t-cre-reply-ch-chan-topic-delete\" is forbidden: unable to create new content in namespace includes-incoming-trace-id-mhlk5 because it is being terminated".
    Reason:                DeleteFailed
    Status:                False
    Type:                  Ready
    Last Transition Time:  2019-10-07T22:56:54Z
    Message:               Failed to delete topic: "jobs.batch \"pubsub-t-cre-reply-ch-chan-topic-delete\" is forbidden: unable to create new content in namespace includes-incoming-trace-id-mhlk5 because it is being terminated".
    Reason:                DeleteFailed
    Status:                False
    Type:                  TopicExists
  Observed Generation:     1
  Project Id:              harwayne2
  Topic Id:                cre-chan-17633f18-e955-11e9-b584-42010a800089
Events:                    <none>
```

**Comment by Harwayne** [comment]
Actually, I take it back, they are deletable, if the Topic's `spec.propagationPolicy` is set to either `CreateNoDelete` or `NoCreateNoDelete`. However, that still leaks the GCP Cloud PubSub Topic.

**Comment by yolocs** [comment]
Would having finalizer on the namespace be helpful at all?

**Comment by Harwayne** [comment]
> Would having finalizer on the namespace be helpful at all?

I don't think so. I believe the problem is that as soon as the NS is marked for deletion, you can no longer create new resources in it (e.g. no new Jobs or Pods). Whereas adding a finalizer would just ensure the NS is not deleted until it is removed, the NS would still be in the terminating state.

**Comment by n3wscott** [comment]
This is related to the secret being removed. Finalized on secret will help.

**Comment by akashrv** [comment]
Please consider #354 when designing a fix for this current issue

**Comment by nachocano** [comment]
need to check if this is still an issue...
the easy way to do it is to have some sources instantiated, that create a topic and pullsubscription underneath, and then delete the namespace. Hopefully everything should be cleaned up, and then the controller removed, together with the control-plane secret. I think this has already been fixed with https://github.com/google/knative-gcp/pull/444 

@capri-xiyue can you double check whenever you have few cycles?

**Comment by capri-xiyue** [comment]
> need to check if this is still an issue...
> the easy way to do it is to have some sources instantiated, that create a topic and pullsubscription underneath, and then delete the namespace. Hopefully everything should be cleaned up, and then the controller removed, together with the control-plane secret. I think this has already been fixed with #444
> 
> @capri-xiyue can you double check whenever you have few cycles?

Yep. I will check it.

**Comment by capri-xiyue** [comment]
I use the latest serving(commit b101b5518c11584547b14691221ec02d9c6ef6f8), eventing(702be2256abf1be34390b7eb4ea63f600d46ba8d), knative-gcp(31fae447e59550de1a140237e0d9a28d98c89604), I created namespace `test`, created Pub/Sub Enabled Service Account in `test` namespace, created `cloudauditlogs source` with this https://github.com/google/knative-gcp/blob/master/docs/examples/cloudauditlogssource/README.md, then I deleted `test` namespace with `kubectl delete namespace test`. I verified everything resources including `topic`, `pullsubscription` in `test` namespace got deleted, and the `topic`, `pullsubscription` in pantheon got deleted. I think we can close this issue.

**Comment by nachocano** [comment]
> I use the latest serving(commit b101b5518c11584547b14691221ec02d9c6ef6f8), eventing(702be2256abf1be34390b7eb4ea63f600d46ba8d), knative-gcp([31fae44](https://github.com/google/knative-gcp/commit/31fae447e59550de1a140237e0d9a28d98c89604)).
> 
> I created namespace `test`, created Pub/Sub Enabled Service Account in `test` namespace, created `cloudauditlogs source` with this https://github.com/google/knative-gcp/blob/master/docs/examples/cloudauditlogssource/README.md, then I deleted `test` namespace with `kubectl delete namespace test`.
> 
> I verified all resources including `topic`, `pullsubscription` in `test` namespace got deleted, and the `topic`, `pullsubscription` in pantheon got deleted. I think we can close this issue.

Awesome @capri-xiyue 
Thanks for verifying!!! closing it...

/close
