### ISSUE TITLE
Perf test for Broker+Channel and Knative Service subscriber

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#330]
#328 tests this scenario:

```
pod -> broker (-> pubsub chan) -> pod
```

We expect most users will send events to Knative Services instead of bare pods. We should add a perf test for this scenario in addition to the pod test:

```
pod -> broker (-> pubsub chan) -> knative service
```

/area performance
/assign @grac3gao

**Comment by capri-xiyue** [comment]
@grantr  Hi Grant, it seems like this issue has been covered by this PR https://github.com/google/knative-gcp/pull/328/commits

**Comment by nachocano** [comment]
@chizhg does any of the e2e tests that we have for broker with pubsub channel use a Kn Service as subscriber?

**Comment by chizhg** [comment]
https://github.com/google/knative-gcp/blob/3f6b17d1a02bfe2cfc9d6891c09d8c185372d5b9/test/e2e/test_broker_pubsub.go#L45 is using Kn service.

**Comment by nachocano** [comment]
sounds good....

sorry my bad... it was for perf tests I guess...
