### ISSUE TITLE
Limit of PullSubscription name length

### ISSUE THREAD

**Issue by xorver** [google/knative-gcp#336]
I wonder what is the limit of name length for triggers/sources.

I see that for PullSubscription it is lower than for Trigger (for trigger ~40 chars works fine), I tried to create a subscription with 40 character name (30 works fine)

```
apiVersion: pubsub.cloud.run/v1alpha1
kind: PullSubscription
metadata:
  name: aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd
spec:
  topic: testing
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default
```

And it fails to create:

```
lichon@lichon:/google/src/cloud/lichon/events-cli/google3/knative-gcp$ kubectl get pullsubscription.pubsub.cloud.run/aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd -oyaml
apiVersion: pubsub.cloud.run/v1alpha1
kind: PullSubscription
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"pubsub.cloud.run/v1alpha1","kind":"PullSubscription","metadata":{"annotations":{},"name":"aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd","namespace":"default"},"spec":{"sink":{"apiVersion":"eventing.knative.dev/v1alpha1","kind":"Broker","name":"default"},"topic":"testing"}}
  creationTimestamp: "2019-10-10T09:05:37Z"
  generation: 1
  name: aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd
  namespace: default
  resourceVersion: "2813512"
  selfLink: /apis/pubsub.cloud.run/v1alpha1/namespaces/default/pullsubscriptions/aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd
  uid: 203ae800-eb3d-11e9-945f-42010a8000b5
spec:
  ackDeadline: 30s
  mode: CloudEventsBinary
  retentionDuration: 168h0m0s
  secret:
    key: key.json
    name: google-cloud-key
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default
  topic: testing
status:
  conditions:
  - lastTransitionTime: "2019-10-10T09:05:37Z"
    status: Unknown
    type: Deployed
  - lastTransitionTime: "2019-10-10T09:05:37Z"
    message: 'Failed to create Subscription: "unknown".'
    reason: CreateFailed
    status: "False"
    type: Ready
  - lastTransitionTime: "2019-10-10T09:05:37Z"
    status: "True"
    type: SinkProvided
  - lastTransitionTime: "2019-10-10T09:05:37Z"
    message: 'Failed to create Subscription: "unknown".'
    reason: CreateFailed
    status: "False"
    type: Subscribed
  observedGeneration: 1
  sinkUri: http://default-broker.default.svc.cluster.local
  subscriptionId: cre-pull-203ae800-eb3d-11e9-945f-42010a8000b5
```

Do you know if there's some limit enforced, also is there an easy way to get more detailed failure logs from PullSubscription?

I was running it on 0.8 knative&CRDs, I'll be upgrading to current head so I don't know yet how it behaves with PubSub objects.

**Comment by n3wscott** [comment]
We use a name trimming function and have tests to confirm this works in k8s, so I am surprised this is an issue.

And you get the logs from the jobs that are failing for that PullSubscription? I would like to understand what the error really is. (we have a todo to output errors from the job pod into the status, but we are still working on it)

**Comment by xorver** [comment]
I realized that I've put in the first post an example with 30 chars, which worked fine, I've edited it to be 40 (`aaaaaaaaaabbbbbbbbbbccccccccccdddddddddd`) as in quoted error messages.

I don't see any jobs related to that pullsubscription, I've created a similar one with shorter name for which I can find the job using:
```
lichon@lichon:/google/src/cloud/lichon/run/google3$ kubectl get jobs -A
NAMESPACE      NAME                                                              COMPLETIONS   DURATION   AGE
default        pubsub-s-aaaaaaaaaabbbbbbbbbbcccccccccc-pullsubscription-c9jq5f   1/1           6s         4d22h
```
Do I need any additional flag, or is the job not created at all?

**Comment by nachocano** [comment]
@xorver we have removed the Job-based architecture in 0.12. Once the release comes out (in the upcoming hours), you should be able to test it out, and should not see any job being created... 

The limit that you will face in naming resources is the one that k8s has, which IIRC is about 253 chars.. See [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).. I just created a trigger with 200 characters, and was successfully created.

Closing this one as the system has been re-architected. If you find similar issues with the new version, please do let us know.

/close
