### ISSUE TITLE
Proposal: allow using default GCE service account to operate GCP services when running on GKE

### ISSUE THREAD

**Issue by yolocs** [google/knative-gcp#347]
### Current behavior and problem

When operating GCP services (e.g. pubsub topic/subscription), if a secret is not provided, we always default to `google-cloud-key` - https://github.com/google/knative-gcp/blob/master/pkg/apis/duck/v1alpha1/google_cloud_secret_defaults.go. This totally makes sense on non-GKE clusters.

This behavior requires a user to create a (either `google-cloud-key` or a custom one) secret under each namespace before they can use eventing in them. It'd be kinda of a hassle if the eventing is automatically installed but still require the user to create a secret manually before they can start to use eventing. In the future, this behavior could also preventing us from automatically creating PubSub channels without user intervention.

### Proposal

On GKE, we can leverage https://cloud.google.com/docs/authentication/production#finding_credentials_automatically - with which if no secret (including `google-cloud-key`) is provided, we can by default use GCE default service account to access GCP services.

A rough idea:
Instead of defaulting secret selector on the api level, have reconciler to figure that out:
1. If a secret is provided, use that
2. If a secret is missing, check if secret `google-cloud-key` exists. If so, use that; otherwise don't specify a secret.
In Jobs if no secret is mounted as application default credentials, the client lib will automatically figure out it's on GKE and use default GCE service account.

Before creating a GKE cluster, the user still needs to grant the GCE default service account the permission to any resource they need to operate by eventing, like pubsub. When creating the cluster, they also need to check the corresponding API scope. But once the cluster is created, it's no longer mandatory to set up secret in the cluster before start using eventing. 

### Caveats

I vaguely remember using default GCE service account is encouraged as an easy way to call GCP services from GKE clusters. But now it seems using dedicated service accounts are more preferred: https://cloud.google.com/kubernetes-engine/docs/tutorials/authenticating-to-cloud-platform#why_use_service_accounts

However, I still think this change makes sense especially for the purpose of easy start with eventing on GKE.

**Comment by yolocs** [comment]
@akashrv @n3wscott

**Comment by evankanderson** [comment]
One consideration, though this is probably a product decision:

By using the default service account, all namespaces in the cluster use the same security context (credential/identity). This works if all your namespaces are equally trusted, but might not be a good default if the common user case is to have a central project which vends resources to less-privileged namespaces, because the default robot could have access to more things than intended on the project.

**Comment by akashrv** [comment]
@yolocs Did you follow-up with Ryan and have a design about what the first time user experience will be?

**Comment by nachocano** [comment]
@yolocs I'm closing this one as is obsolete. We've discussed with PMs and we've taken the approach of having a control plane secret, and then data plane ones, which are created with a `gcloud create broker command`.
Now that we are introducing workload identity for GKE clusters, users will be able to specify a GSA as part of their GCP sources spec. If not specified, we might fallback to a default one in the namespace (also created with that gcloud create broker command). 

Please re-open if you don't agree and we can further discuss
