### ISSUE TITLE
Channels - Don't self-heal deleted GCP Topics

### ISSUE THREAD

**Issue by Harwayne** [google/knative-gcp#362]
I created a PubSub Channel. Then deleted the GCP Topic via gcloud. 

**Expectation**:
Eventually the Channel would notice and both mark itself as unhealthy, as well as self-heal.

**Observation**:
Nothing noticed. It will stay broken forever, until I manually delete either the Topic or the Job.

**Note**:
This is a general problem of how do we notice and fix issues with resources outside the K8s cluster itself.

**Comment by capri-xiyue** [comment]
This issue should get fixed with this merge request https://github.com/nachocano/knative-gcp/pull/1. Will close it after Nacho merges this PR into knative-gcp
