### ISSUE TITLE
Does it make sense for a Source to be associated with a region?

### ISSUE THREAD

**Issue by loonybear** [google/knative-gcp#367]
I am working on internal eventing.
Our api server is regional. 
So we could run into a case where a user create a trigger in a different region from where the Source the trigger is interested in.
This could create challenge for us to deliver the event. 
So we are asking if it makes sense to indicate the source region when user create a Trigger.

**Comment by evankanderson** [comment]
I think that the Trigger and the Source need to be on the same cluster / using the same apiserver to be able to link things up via CloudEvents attributes. Regional GCP resources (different from the Source custom object) tend to already have the GCP region somewhere in their (opaque) resource path. The Source and Trigger's region is specified by the address of the apiserver, e.g. `us-east1.eventing.googleapis.com`.

Assume the following environment:

Original system: Firestore in region A
Cluster: apiserver in region B
Compute: Cloud Run Service in region C

In this case, the Source and Trigger would both be instantiated in region B; the Source would refer to the Firestore resource in region A by some sort of GCP object reference like a resource URL. Similarly, the Trigger would refer to the Cloud Run Service in region C using a `uri` reference, not a Kubernetes `ref` type, which is only for same-cluster references.

Note that this particular configuration requires three regions to be available for the system to be operating: A, B, and C. Your availability will therefore be 0.9999^3 ~= 0.9997. As the service provider, you might want to enforce a rule like "Sources should refer to resources in the same region" or "Triggers should refer to resources in the same region"; this would either end up with:

A: Firestore, apiserver (Source + Trigger)  || C: Cloud Run Service
A: Firestore || C: apiserver (Source + Trigger), Cloud Run Service

Either of these would have 0.9999^2 ~= 0.9998 availability. Note that if you enforce both rules, you'd block users from being able to directly route events from one region to another, which is probably undesirable.

In some cases (I'm looking at IAM, GCLB, and possibly Stackdriver Logging), the service may be global in nature. In that case, if you are enforcing "Sources must refer to resources in the same region", you'd need a special carve-out for global services. Similarly, if you are enforcing "Triggers should refer to resources in the same region", `uri` targets for Triggers provide an end-run around that enforcement, at the expense of being harder to write and validate than `ref` targets.

**Comment by evankanderson** [comment]
(Please `/close` if the above made sense, or re-ask the question if not.)

**Comment by loonybear** [comment]
I personally would vote for the first option. 

It is also convenient for the api server to watch any changes to the actual source. 
It doesn't really matter where C is. 

I agree that we shouldn't restrict users from keeping the actual resource in the same region as where they create the Trigger. But maybe users can specify in which region they want the resource as the Source.

For instance, if there's a global service that is set up in region A B C D
User wants to create a flow triggered by source in region A B C. So they create 3 triggers:
Trigger 1, destination = URI, source = obj ref to region A, specifying the source region to A
Trigger 1, destination = URI, source = obj ref to region B, specifying the source region to B
Trigger 1, destination = URI, source = obj ref to region C, specifying the source region to C?

**Comment by akashrv** [comment]
@loonybear Is this still an open issue?

**Comment by loonybear** [comment]
I don't think we really finalized a decision yet. 
Global Events has rich use cases in my opinion. But as Evan described above, it is hard to actually associate a source or an event with a particular region. 

I will pass this issue to my colleagues who spent a lot of time researching rationality to take a final look before we close this or mark this obsolete.

Thanks

**Comment by riaj** [comment]
In the case of a multi-regional service like the one @loonybear mentioned above, even if we restrict users to create the Trigger from one of the regions where their resource lives, the event can happen in other regions as well - in the example above, say users created a Trigger in A, since the resource lives in A,B,C, events can come from either one of those regions; if users created Triggers in all those regions A,B,C, users would have to keep track of all those Triggers and merge events from three regions and we can't really guarantee which events would come from which regions inside (A,B,C). If we know the resource region when user is creating the Trigger, it would help us know where to match the event and users would only need to create Trigger once for multi-regional/global services. I was going to write a one-pager detailing our use cases, maybe we can leave this issue open until then?

**Comment by grantr** [comment]
@loonybear is this issue still relevant or can it be closed? Thanks!

**Comment by loonybear** [comment]
We can close this now. Thanks
