### ISSUE TITLE
0.10: delete previous webhook configuration on webhook startup

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#394]
#393 changed the name of the webhook, so on upgrade there will be two webhooks. I think what will happen is that objects will be sent to the webhook twice. The system will probably work fine, but we should advise users to delete the old webhook to avoid double validating objects.

**Comment by grantr** [comment]
Here's the delete command: `kubectl delete mutatingwebhookconfiguration webhook.cloud-run-events.events.cloud.google.com`

**Comment by nachocano** [comment]
I think this is done with https://github.com/google/knative-gcp/pull/393. Can we close it @grantr ?

**Comment by nachocano** [comment]
/close obsolete
we are in 0.12 now...
