### ISSUE TITLE
PubSub Source - Doesn't notice GCP topic deleted

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#399]
I created a PubSub as Source. After it was in ready status, I deleted the binding GCP Topic via gcloud.

**Expectation**
PubSub source would notice the deletion of this GCP topic, and propagate this status 

**Observation**
Nothing noticed. PubSub will stay in ready status

**Comment by capri-xiyue** [comment]
This issue should get fixed with this merge request https://github.com/nachocano/knative-gcp/pull/1. Will close it after Nacho merges this PR into knative-gcp

**Comment by nachocano** [comment]
/close
This was fixed by @capri-xiyue and included as part of the job reconciler PR #444
