### ISSUE TITLE
Update knative-gcp to use the same e2e test framework that knative eventing is using

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#413]
**Problem**
knative-gcp uses its own test framework to do e2e tests. https://github.com/knative/eventing already developed a framework to do e2e tests and https://github.com/knative/eventing-contrib also uses the test framework in https://github.com/knative/eventing. To keep it consistent, knative-gcp should use the same test framework.

**Comment by capri-xiyue** [comment]
@akashrv

**Comment by nachocano** [comment]
/assign @chizhg 
so that it's on your radar. I don't know Peter's github id.

**Comment by nachocano** [comment]
@grantr can you add @chizhg to the collaborators of this repo? I do not see the settings tab to add him.

**Comment by grantr** [comment]
Sure, I added @chizhg as a collaborator.

**Comment by nachocano** [comment]
> Sure, I added @chizhg as a collaborator.

Thanks!

**Comment by nachocano** [comment]
/assign @chizhg 
so that it's on your radar. I don't know Peter's github id.

**Comment by nachocano** [comment]
I think a good start would be to add an e2e test for Scheduler using the eventing test-infra, as it's the only source that doesn't have an e2e. And then we can start refactoring the current ones.

**Comment by chizhg** [comment]
Fixed by https://github.com/google/knative-gcp/pull/471.

/close
