### ISSUE TITLE
Enable ApiServer Source

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#429]
**Problem**
In order for users to consume Kubernetes events, we need to enable the ApiServerSource in eventing.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Developer

**Exit Criteria**
ApiServerSource enabled

**Time Estimate (optional):** 
1d

**Comment by nachocano** [comment]
Note that this actually refers to the ApiServerSource in eventing. 
The task will involve enabling this in our release
