### ISSUE TITLE
Tests for Upgrades

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#434]
**Problem**
We need to make upgrades smooth for users. In order to confirm upgrades can be done properly, we need automatic tests that tests such upgrades.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
Developer

**Exit Criteria**
E2E tests that checks the upgrade from previous version(s) to latest one.

**Time Estimate (optional):** 
~1w

**Additional context (optional)**
Lately, there has been some breaking changes to webhooks (e.g., https://github.com/knative/eventing/pull/2147) that raised this concern. As we are getting closer to beta and GA, we need a better upgrade story.

**Comment by chizhg** [comment]
/unassign
Currently I don't have the bandwidth to work on this issue.

**Comment by ericlem** [comment]
This has been further broken down in
https://github.com/google/knative-gcp/issues/977
https://github.com/google/knative-gcp/issues/749
https://github.com/google/knative-gcp/issues/666
https://github.com/google/knative-gcp/issues/610
https://github.com/google/knative-gcp/issues/609
Closing this to track specific work in those places.
