### ISSUE TITLE
Automatic event registration does not work with GcpPubSubSource

### ISSUE THREAD

**Issue by meteatamel** [google/knative-gcp#435]
**Describe the bug**
In Event Registry [docs](https://knative.dev/docs/eventing/event-registry/), it says that there's automatic registration for GcpPubSubSource. However, when I configure and test a GcpPubSubSource, I don't see automatic registration for Pub/Sub events. `kubectl get eventtypes` always returns `No resources found`.

**Expected behavior**
When I configure GcpPubSubSource, I see an event type automatically registered.

**To Reproduce**
```
kubectl apply -f gcp-pubsub-source.yaml
pubsub.events.cloud.google.com/testing-source created

kubectl get eventtypes
No resources found.
```
**Knative release version**
0.10

**Comment by allenday** [comment]
same problem in 0.11

**Comment by nachocano** [comment]
Thanks for reporting... Waiting for a refactor to happen in eventing that we will be able to leverage, and easily add this feature...
