### ISSUE TITLE
PubSub source: passing a service account email as an optional parameter

### ISSUE THREAD

**Issue by loonybear** [google/knative-gcp#441]
When users provide PubSub topic as a source, we might need to set a Subscription to the source. And we will need to be authenticated in user's project to create a Subscription subscribing to the input topic.

Users could provide an authorized service account as an optional parameter in PubSubSpec, to solve this issue.

@nachocano @capri-xiyue

**Comment by nachocano** [comment]
This is something that @grac3gao will add as part of the integration with workload identity in https://github.com/google/knative-gcp/issues/540. 
Assigning it to Grace

/assign @grac3gao

**Comment by nachocano** [comment]
Fixed by @grac3gao in PR https://github.com/google/knative-gcp/pull/625
Closing
