### ISSUE TITLE
Rename Sources to have a Cloud prefix and a Source suffix

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#447]
Our current Sources are called Storage, Scheduler, and PubSub. To be more consistent with knative sources, let's rename them to CloudStorageSource, CloudSchedulerSource, CloudPubSubSource.

**Comment by nachocano** [comment]
fyi @ian-mi @capri-xiyue this will also apply to CAL. But if it adds too much noise, we can rename it after we get the first PR in

**Comment by nachocano** [comment]
Further, I think once the CAL source gets merged, we should remove the cloud prefix. All others don't have it, e.g., Scheduler, Storage, PubSub... Having just one with Cloud, IMO is confusing. So I think it will end up being `AuditLogsSource`.

**Comment by hrasadi** [comment]
For posterity, note that after renaming, the audit log source should be called 'CloudAuditLogsSource'.

**Comment by capri-xiyue** [comment]
@hrasadi Do we need to add "Cloud" as a prefix for "Storage", "Scheduler", and "PubSub"?

**Comment by nachocano** [comment]
As agreed offline, we should also include the Cloud prefix...

`CloudAuditLogsSource`, `CloudPuySubSource`, `CloudSchedulerSource`, and `CloudStorageSource`
