### ISSUE TITLE
CAL source misses the CloudAuditLogs which gets created shortly after CAL source becomes ready

### ISSUE THREAD

**Issue by chizhg** [google/knative-gcp#480]
From the comment in https://github.com/ian-mi/knative-gcp/pull/2#pullrequestreview-333515256.

If the AuditLog was created shortly after the CAL source becomes ready, the log will be missed. e.g. when the log sink got created and CAL source becomes ready at 1:42:35pm and one AuditLog got fired at 1:43:04pm, the AuditLog will get missed by the CAL source.

**Comment by chizhg** [comment]
Also the e2e test for it is pretty flaky - https://testgrid.knative.dev/knative-gcp#continuous&exclude-non-failed-tests=

**Comment by nachocano** [comment]
I don't see this as our issue. It seems to be related to CAL SLO. 
Closing it as I fixed the flakiness by increasing the timeout... 
We should properly document that users should wait a few seconds before they will start receiving events.

If you disagree, please re-open and we can revisit
