### ISSUE TITLE
E2E tests for sending one event to Channel is flaky

### ISSUE THREAD

**Issue by chizhg** [google/knative-gcp#486]
**Describe the bug**
When we run the E2E test in eventing for Channel, `TestSingleBinaryEventForChannel` and `TestSingleStructuredEventForChannel` are flaky.

The error message when it happens:

channel_single_event_helper.go:74: Failed to send fake CloudEvent to the channel "e2e-singleevent-channel-binary": addressable's URL does not have a Host: &{TypeMeta:{Kind:Channel APIVersion:messaging.cloud.google.com/v1alpha1} ObjectMeta:{Name:e2e-singleevent-channel-binary GenerateName: Namespace:v1alpha1-t8bvk SelfLink:/apis/messaging.cloud.google.com/v1alpha1/namespaces/v1alpha1-t8bvk/channels/e2e-singleevent-channel-binary UID:5d955bfc-27bc-4a3b-96ac-b745a2c71c54 ResourceVersion:5634 Generation:2 CreationTimestamp:2020-01-15 20:15:42 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Initializers:nil Finalizers:[] ClusterName: ManagedFields:[]} Status:{Address:0xc001a6dd80}}

 **Expected behavior**
The two tests should be able to consistently pass.

**Comment by nachocano** [comment]
@chizhg any updates on this? Do you know if we can enable them? 
Was the one with the default-ch-webhook configMap problem, that wasn't being updated?

BTW, that one got fixed?

**Comment by chizhg** [comment]
I don't think they can be enabled as there was no change related to them. I can revisit them again today to see what's the exact reason for the failure.

The default-ch-webhook is a different issue and it hasn't been fixed. There are only two ways to fix it, one is changing the resync time for the informer, the other is recreating the webhook Pod in the tests.
I'm not sure which one is more preferable to you.

**Comment by Harwayne** [comment]
Switching release as Channel is not in scope for `release/2`.
