### ISSUE TITLE
Add UTs for CloudAuditLogsSource validation

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#493]
**Problem**
#492 added missing validation for the CloudAuditLogsSource. We should add UTs for it.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Contributor

**Exit Criteria**
UTs for cloudauditlogssource_validation.go

**Comment by nlopezgi** [comment]
Created https://github.com/google/knative-gcp/pull/498 for this.
