### ISSUE TITLE
Clean up Topics and Subscriptions before running e2e tests

### ISSUE THREAD

**Issue by chizhg** [google/knative-gcp#494]
**Problem**
When the e2e tests are run, Topics and Subscriptions will be created under the hood. If tests are being teared down properly, these Topics and Subscriptions will be automatically cleaned up as the upper level resources are deleted. But the tests can possibly be interrupted in the middle, in that case the Topics and Subscriptions will be leaked.

Aside from deleting them after the tests are finished, we should also try to clean up all leaked Topics and Subscriptions before running the tests.

**Exit Criteria**
All Topics and Subscriptions are deleted from the GCP project before the e2e tests are run.

/cc @peterfeifanchen

**Comment by nachocano** [comment]
/assign @chizhg 
would you have cycles to work on this? or maybe @peterfeifanchen ?

**Comment by chizhg** [comment]
I'll take care of it, it's an easy fix.
