### ISSUE TITLE
CloudPubSubSource should use PushCompatible mode

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#497]
**Problem**
CloudPubSubSource should be configured to send events in PushCompatible mode. 
Here is an example of a PubSub push message, which we should include as part of the CE data

```json
{
   "message": {
      "attributes": {
         "[KEY1]" : "[VALUE1]",
         "[KEY2]" : "[VALUE2]",
         …
      },
      "data" : "[DATA]",
      "messageId" : "[MESSAGE_ID]",
      "publishTime" : "[PUBLISH_TIME]"
   },
   "subscription": "[SUBSCRIPTION_ID]"
}

```

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Developer

**Exit Criteria**
CloudPubSubSource emits CloudEvents with Push format

**Time Estimate (optional):** 
2 days

**Additional context (optional)**
Currently there is a ConvertToPush method within pkg/adapter/push that does that. The problem is that the code goes through the pubsub converter first, which promotes attributes to extensions, and then performs this latter conversion to Push. During the first conversion, we might be missing attributes, as they might not be valid extensions. 
Given that CloudPubSubSource is the only one that currently supports Push, we can move the push.go code up to the pubsub.go converter, and do the appropriate changes there...
If users want the Pull format, they can simply use the PullSubscription.

**Comment by nlopezgi** [comment]
I'm going to try to solve this one. Its a bit more complex than the previous ones I've done, will update here if I have questions or run into issues.
