### ISSUE TITLE
Specify sideEffects in the webhook

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#502]
**Problem**
As with https://github.com/knative/eventing/pull/2410

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Contributor

**Exit Criteria**
Webhook with sideEffects

**Time Estimate (optional):** 
10m

**Comment by nlopezgi** [comment]
Created https://github.com/google/knative-gcp/pull/506
