### ISSUE TITLE
Add labels to GCP resource to organize/identify them

### ISSUE THREAD

**Issue by akashrv** [google/knative-gcp#509]
**Problem**
After creating few sources and pubsub channel it becomes difficult to figure out which topic/subscription is created for which source and channels/subscriptions. 
This makes debugging difficult.
Could we add labels to these GCP resource such that users can identify which source or channel or broker the resource belongs to? This will also help someone administering the resource understand that they were created by Knative/CloudRun

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
End users

**Comment by nachocano** [comment]
/assign @nlopezgi

Can you take a look at this one? Not sure if with the ownerReference is clear already, but we might be able to add some extra label or annotation to specify the name of the Source or Channel that ended up creating the underlying resources..
