### ISSUE TITLE
E2E test: Each source with PubSub backed channel

### ISSUE THREAD

**Issue by akashrv** [google/knative-gcp#511]
We need to test each source with PubSub backed channel to avoid breaking CRfA. This could be done in knative-gcp repo or CloudRun repo. I would prefer knative-gcp repo so that issues are caught early at source.

**Comment by nachocano** [comment]
@chizhg do you guys think you might have the cycles to work on some of this?
fyi @nlopezgi

**Comment by nachocano** [comment]
We need this e2e tests, sending from one of our Sources to a Broker backed by PubSub channel, and receiving on the Kn Service on the other end. In order of priority:

- [ ] CloudPubSubSource
- [ ] CloudAuditLogsSource
- [ ] CloudStorageSource
- [ ] CloudSchedulerSource

I think each of the tests can be committed in their own PR, and once we have all of them checked, we can close this issue...

**Comment by nachocano** [comment]
Some docs to look at on how to run e2e tests... 
https://github.com/google/knative-gcp/tree/master/test/e2e

TL'DR: either submit a WIP PR and PROW will run it for you. Or you can run some scripts locally to upload the tests images, and then run your particular test in your own cluster (will probably be faster for development, unless you skip all the other ones in the WIP PR)

A bunch of the stuff here https://github.com/google/knative-gcp/blob/master/test/e2e/test_broker_pubsub.go can be reused...
The thing we need to change is who is the sender... The current code just tests a sender pod, see https://github.com/google/knative-gcp/blob/67cc0dc976701689356a3a8c50fa344ec1df9d6b/test/e2e/test_broker_pubsub.go#L117
For our new tests, we need the sender to be an actual Source. 
For an example of a Source, you can see https://github.com/google/knative-gcp/blob/67cc0dc976701689356a3a8c50fa344ec1df9d6b/test/e2e/test_pubsub.go#L67, where we create the Source object, and then publish to a pubsub topic...
There are examples for the other Sources as well in the same package.

@chizhg is our guy when it comes to e2e, so he will help out with the review (and maybe with some suggestions on how to properly refactor things out)
