### ISSUE TITLE
E2E tests creating objects with gcloud

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#556]
**Problem**
Our e2e tests currently create the resources using the client-go. However, many users will be inclined to use gcloud. The experience there is to create a Trigger, which in turn will create a Source and hook them together.
We've seen problems because of gcloud sending nil values as empty, unkown fields, etc.
We should have e2e tests that create things using gcloud.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Contributor

**Exit Criteria**
E2E tests that use gcloud to create objects

**Time Estimate (optional):** 
?

**Comment by nachocano** [comment]
We should also test the reply mechanism as part of these tests

**Comment by nachocano** [comment]
Moving to v1beta1 seems that it might break gcloud. We need to make sure we are not.

**Comment by nlopezgi** [comment]
@danyinggu will start looking at this issue

**Comment by grantr** [comment]
Great thanks @danyinggu!

/assign @danyinggu

**Comment by ericlem** [comment]
We're going to test this elsewhere.

**Comment by nlopezgi** [comment]
Are we no longer doing this? I had planned with Danying for her to work on this.
