### ISSUE TITLE
Use peribolos to manage repo settings

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#558]
**Problem**
Managing contributors is done manually by admins with no obvious audit trail. I think GitHub does provide audit logs to org admins, but none of us are google org admins.

Prow has a component called [Peribolos](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos) that updates github settings based on a checked-in config file. Using this we could use PRs and normal approval mechanisms to add collaborators.

We probably don't want it managing the entire google org, so this is only feasible if it can manage a single repo instead.

**Comment by chizhg** [comment]
Related: https://github.com/knative/test-infra/issues/148
