### ISSUE TITLE
CloudAuditLogs E2E tests are flaky

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#596]
**Describe the bug**
E2E tests for CloudAuditLogs failed in 0.13 branch though consistently pass in master. Cannot trigger a release because of this problem. As of the time of this writing, both master and 0.13 are exactly the same.

 **Expected behavior**
E2E test passing

 **Knative-GCP release version**
0.13

 **Additional context**
https://testgrid.knative.dev/knative-gcp#auto-release

**Comment by nachocano** [comment]
Will skip them in 0.13 branch so that we can get a release out

**Comment by chizhg** [comment]
It was because the service account used in release jobs missed some permissions, https://github.com/knative/test-infra/pull/1781 added the permission for it, and the tests can pass now.

/close
