### ISSUE TITLE
E2E correctness of GCP broker during upgrade

### ISSUE THREAD

**Issue by ericlem** [google/knative-gcp#609]
**Problem**
We need an e2e functional test that performs event transmission during broker upgrade and ensures that any events receiving a 200 return value are eventually delivered through to subscribers to that event type. We should investigate whether the work done in https://github.com/knative/eventing/pull/2388 can be extended and used for this, but this is not a requirement.

Eventually we want this test to ensure that the deliveries never return anything other than a 200 even during upgrade, so it is desirable to design this test in a way that we can later turn on that functionality.

**Exit Criteria**
Running automated E2E test that fails if any  event that was sent to the broker and received a 200 response is not delivered to a subscriber after upgrade.  It should also fail if the does not succeed in reasonable time  or event delivery to the broker ingress does not start returning 200 responses after upgrade. 

**Time Estimate (optional):** 

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by liu-cong** [comment]
@ericlem , can you give some updates on this one? Should this be closed or should we move it to release/2?

**Comment by ericlem** [comment]
This should be moved to release/2.  We decided that we could live with the manual test for now.

**Comment by grantr** [comment]
Clarifying that this issue is about automating the E2E upgrade test, not doing it manually.
