### ISSUE TITLE
E2E availability test for broker ingress during upgrade

### ISSUE THREAD

**Issue by ericlem** [google/knative-gcp#610]
**Problem**
Test that the broker never goes unavailable during upgrade.  This will build on the E2E test from https://github.com/google/knative-gcp/issues/609 that insured that accepted events were eventually delivered to test that the events never receive a response other than 200 even during upgrade.

**Exit Criteria**
E2E test for event delivery during upgrade has been modified to fail if any events transmitted during upgrade receive a non-200 response code or any of the events transmitted during upgrade are dropped.  This should largely be turning on this functionality in the test and verifying that it passes.

**Time Estimate (optional):** 
3d

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by liu-cong** [comment]
Should probably implement this in Mako

**Comment by liu-cong** [comment]
Definition of upgrade: upgrade from an old release to a newer release.

**Comment by zhongduo** [comment]
I believe this is done by #1854 . We should be able to close this one.
