### ISSUE TITLE
Define Broker config API

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#634]
* Define Broker class name
* Config object: ConfigMap or CRD?
* Config properties and defaults

/area broker

Estimate: <1 week

**Comment by liu-cong** [comment]
We can start with defining some constants and convert them to configurations.

We should use a ConfigMap and use the [default-br-config](https://github.com/knative/eventing/blob/11bafe000b9b97277ed011cc9ef83e075485b146/config/core/configmaps/default-broker.yaml#L22) configuration to point to the configmap.

**Comment by grantr** [comment]
Basic configuration we know we need: GCP project.

We may add configuration of decoupling topic name, but no clear need for that right now.

**Comment by grantr** [comment]
Deprioritizing this one. If we need a configuration value, for now put a TODO so we can find them later.

**Comment by grantr** [comment]
Closing this issue as there's no need for it to exist. We can create additional issues to define configuration variables as needed.
