### ISSUE TITLE
This `key.json` is what I wanted to be documented earlier in the Topic type's Secret ref field. How does the user know to use this key otherwise?

### ISSUE THREAD

**Issue by n3wscott** [google/knative-gcp#64]
This `key.json` is what I wanted to be documented earlier in the Topic type's Secret ref field. How does the user know to use this key otherwise?

_Originally posted by @grantr in https://github.com/GoogleCloudPlatform/cloud-run-events/pull/35_

**Comment by akashrv** [comment]
@grantr @n3wscott So what is the fix here?
