### ISSUE TITLE
E2E test for Trigger metrics

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#647]
## Expected Behavior
We need to have e2e tests for Trigger metrics using StackDriver as backend (event_count, dispatch_latencies, etc)

## Actual Behavior
We don't have 

## Additional Info
https://cloud.google.com/monitoring/api/metrics_knative

**Comment by nachocano** [comment]
We should sync with serving folks , especially @yanweiguo, as he has been adding E2E tests on their side, and we might be able to reuse some of their stuff

**Comment by Harwayne** [comment]
This is story pointed based on occurring after #648 is finished.
