### ISSUE TITLE
Broker/Trigger metrics for new Broker impl

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#649]
## Expected Behavior
In the new Broker implementation, we should implement at least the same metrics we currently expose in eventing (in the ingress and filter pods). 

## Additional Info
https://github.com/knative/eventing/blob/master/pkg/broker/ingress/stats_reporter.go
https://github.com/knative/eventing/blob/master/pkg/broker/filter/stats_reporter.go
https://cloud.google.com/monitoring/api/metrics_knative

List of tasks:

- [x] ingress: https://github.com/google/knative-gcp/issues/840
- [x] fanout: https://github.com/google/knative-gcp/issues/853
- [x] retry: https://github.com/google/knative-gcp/issues/899
- [ ] E2E test: #648, #647 

## Exit Criteria
- E2E test that verifies the metrics through all components of the Broker.

**Comment by yolocs** [comment]
Link a couple of issues:

- https://github.com/google/knative-gcp/issues/853
- https://github.com/google/knative-gcp/issues/840

**Comment by liu-cong** [comment]
Updated list of tasks:

- [ ] ingress: https://github.com/google/knative-gcp/issues/840
- [ ] fanout: https://github.com/google/knative-gcp/issues/853
- [ ] retry: https://github.com/google/knative-gcp/issues/899

**Comment by grantr** [comment]
Remaining e2e tasks are tracked in separate issues.
