### ISSUE TITLE
Tracing through new Broker Covered by E2E Test

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#650]
## Expected Behavior
The new Broker implementation should support Tracing and setting SD as the backend.

## Additional Info
https://github.com/google/knative-gcp/issues/226

## Exit Criteria
- E2E that verifies the trace of an event through all components of the Broker and to a Knative Service as the eventual sink.

**Comment by grantr** [comment]
Including tests

**Comment by yolocs** [comment]
Link a couple of issues:

- https://github.com/google/knative-gcp/issues/854
- missing one for ingress?

**Comment by liu-cong** [comment]
- [ ] ingress: https://github.com/google/knative-gcp/issues/855
- [ ] fanout: https://github.com/google/knative-gcp/issues/854
- [ ] retry: https://github.com/google/knative-gcp/issues/898
