### ISSUE TITLE
Enable tracing tests when assertions are more lenient

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#652]
We should enable https://github.com/google/knative-gcp/blob/94506c23b2be7b939bc03054ebaf979090455d97/test/e2e/e2e_test.go#L145, once https://github.com/knative/eventing/issues/2046 is fixed

Creating this so that we don't miss it.

**Comment by grantr** [comment]
https://github.com/knative/eventing/issues/2046 is fixed now.
