### ISSUE TITLE
Design how trigger resources will be efficiently tracked

### ISSUE THREAD

**Issue by yolocs** [google/knative-gcp#654]
The current eventing core broker queries API server for trigger resources. This is a potential bottleneck as API server usually shouldn't be on the data plane. We need to figure out how to efficiently track trigger resource.

In a recent prototype, I have tried to use ConfigMap to track triggers - which is pretty effective when trigger updates (updates & creates) are at low qps. But it has potential problem when handling high qps trigger updates. And the additional configmap could potentially cause RBAC complexity.

**Comment by grantr** [comment]
Current consensus is use ConfigMaps as volumes.
