### ISSUE TITLE
Decide what resources to surface for gcp broker

### ISSUE THREAD

**Issue by yolocs** [google/knative-gcp#655]
The current eventing core broker, when combined with Pubsub channel, surfaces a lot of resources. The broker itself will introduce a Pubsub `Channel` which introduces a `Topic` and a `Pullsubscription` and for each `Trigger` will additionally introduce one `Topic` and `Pullsubscription`. These "logical" resources for the most of the time are useless to the users and they increases the cognitive load to understand the system. We should seek ways to eliminate such resources.

**Comment by liu-cong** [comment]
We decided to go with configmap for now.

**Comment by yolocs** [comment]
> We decided to go with configmap for now.

This is different from the ConfigMap issue. I don't think we have explicitly reached an agreement on what resources to surface. Although it seems we're lean toward **only** exposing broker/trigger resources. If that's the case, we can close this one.

**Comment by yolocs** [comment]
We have reached an agreement to not expose any additional resources other than broker/trigger. This will make it a little bit harder for users to find out what Pubsub topic/subscription the broker uses, but again for the most time they don't need to worry about them at all. If we find that's a problem, we will seek ways to better expose topic/subscription.
