### ISSUE TITLE
 E2E tests for workload identity

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#658]
**Problem**
We need to have e2e tests to verify workload identity. When enabled workload identity, the control plane should work without secret, and the data plane should work with a qualified GCP serviceAccount inputted (without secret). 

**Exit Criteria**
e2e tests to verify workload identity.

**Comment by grac3gao** [comment]
Put some thoughts here. 
Compare with the existing secret method:
1. In control plane, we have a different controller deployment for workload identity, which means the init set up for the e2e testing cluster needs to change (apply different yams for controller deployment, and running command to enable WI in control plane)
2. In data plane, we need to have a GSA, and when running the e2e test, instead of duplicate secret, set the GSA under spec.serviceAccount

**Comment by grac3gao** [comment]
Sync with @chizhg offline, and Chi listed what needs to be done for this:
1. After https://github.com/kubernetes/test-infra/pull/16888 is merged, update prow-tests image to get the latest kubetest
2. Add a new script in knative-gcp/test, namely e2e-wi-tests.sh. In this script, source e2e-common.sh and override the setup and teardown functions to install wi-enabled control plane components, call initialize $@ --cluster-creation-flag "--workload-pool=\${PROJECT}.svc.id.goog" to create a cluster with Workload Identity enabled.
3. Update Prow config to run e2e-wi-tests.sh and e2e-tests.sh separately in two Prow jobs.

He will take step1 and step3, and I will take step2, and update test lib to make it compatible with WI.

**Comment by grac3gao** [comment]
After running e2e test in PROW, there is an issue. In PROW, the control plane's Google Service Account doesn't belong to the current project, which will cause error like: `NOT_FOUND: Service account projects/knative-boskos-96/serviceAccounts/prow-job@knative-tests.iam.gserviceaccount.com does not exist`, this makes the GSA unable to set iam policy binding for Workload Identity.

**Comment by grac3gao** [comment]
E2E test for Workload Identity works. Thanks for your help! @chizhg. Currently, testing for if two e2e test scripts can properly run in the same boskos project in PROW.

**Comment by ericlem** [comment]
Done.
