### ISSUE TITLE
Broker ConfigMap data and common utility to read it

### ISSUE THREAD

**Issue by yolocs** [google/knative-gcp#660]
**Problem**

From https://github.com/google/knative-gcp/issues/654, we have agreed that we want to use ConfigMap for tracking triggers and likely for other broker configs.

- We need to decide what data and how to store them in ConfigMap.
- It's likely the same ConfigMap will be loaded in multiple broker workloads and the controller. We should have a common lib to manipulate the ConfigMap so that those components can focus on implementing the broker business logic.

**Time Estimate (optional):** 
1w

**Additional**

During my previous prototype, I found https://github.com/micro/go-micro/tree/master/config pretty useful. If the license permits, we can consider using it.

**Comment by yolocs** [comment]
Once the *contract* of the config is settled, we can parallel the work:

1. Controller (https://github.com/google/knative-gcp/issues/635) - reconciles Pubsub resources and update the config
2. Fanout (https://github.com/google/knative-gcp/issues/637) - it loads the config and reconciles itself
3. Retry (https://github.com/google/knative-gcp/issues/638) - it loads the config and reconciles itself

**Comment by grantr** [comment]
Go micro is apache licensed, so probably fine: https://github.com/micro/go-micro/blob/master/LICENSE
I'm fine with that, but if it doesn't work out an alternative with similar features is viper, by the author of cobra: https://github.com/spf13/viper (MIT license).

I haven't thought about it too much, but maybe it would make sense to have a single ConfigMap with one key (file) per handler (ingress, fanout, retry). A single ConfigMap allows the controller to transactionally update the configs for all handlers at once, plus makes it slightly easier to run all workloads in the same pod (since there's only one volume mount). Separate files allows each handler to focus only on the configs that are relevant to its function.

**Comment by yolocs** [comment]
I was thinking have a single config file. I will put several options in this issue soon so that we can vote.

**Comment by grantr** [comment]
Something to keep in mind is that we want to minimize delay between when the Trigger is created and the data plane is ready to service the Trigger.

A separate but related issue is that there's no obvious way for the controller to know when the Trigger has processed an updated configmap. But this is a general issue for all data plane components so we don't have to solve it here.

**Comment by yolocs** [comment]
Some initial thoughts on the config.

```
type TargetsConfig struct {
	// Namespace => name => target.
	Targets map[string]map[string]Target
}

type Target struct {
	// UID of the trigger resource.
	// Can be used for naming topic and subscription.
	ID        string
	Namespace string
	Name      string
	Filter    *v1beta1.TriggerFilter

	// Resolved subscriber URI.
	SubscriberURI *apis.URL

	// If a target is not ready,
	// we can even skip sending events to it.
	IsReady bool

	RetryTopic        string
	RetrySubscription string
}
```

Essentially it's a list of triggers + retry topic/sub. In the ConfigMap it could be `encode(serialize(TargetsConfig))`. The ConfigMap size [limit](https://stackoverflow.com/questions/53012798/kubernetes-configmap-size-limitation) is the limit from etcd. It makes sense to me to be mindful about how much config data we store from the beginning.

Additionally we can have libs:

```
type ReadOnlyTargets interface {
	// Range over targets in a namespace.
	RangeNamespace(namespace string, f func(t Target) bool)
	// Range over all targets.
	Range(f func(t Target) bool)
	// Serialize.
	Bytes() []byte
}

type Targets interface {
	ReadOnlyTargets

	// Combined they can be called like:
	// targets.Union(a, b, c).Except(d, e, f).Bytes()
	// Adds targets to the list.
	Union(ts ...Target) Targets
	// Remove targets from the list.
	Except(ts ...Target) Targets
}

func NewReadyOnlyTargetsFromFile(path string) (ReadOnlyTargets, error) {
	// E.g. Read and watch the ConfigMap volume mount file.
	return nil, nil
}

func NewTargetsFromConfigMap(cm *corev1.ConfigMap) (Targets, error) {
	// E.g. read bytes from ConfigMap
	return nil, nil
}
```

The controller should be the only one that updates the ConfigMap. It can use `NewTargetsFromConfigMap()` to read the existing ConfigMap, and use `Union()` and `Except()` to update the list and `Bytes()` to write back to the ConfigMap.

Other workloads should mount the ConfigMap as readonly volume and use `NewReadOnlyTargetsFromFile()` to load the config in memory. It should be implemented in a way that changes to the file are auto refreshed into memory.

**Comment by yolocs** [comment]
> Something to keep in mind is that we want to minimize delay between when the Trigger is created and the data plane is ready to service the Trigger.

Putting a reference here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically

Although it's a little bit upsetting to see that there are long opening issues regarding to make this behavior more deterministic (e.g. https://github.com/kubernetes/kubernetes/issues/30189).

**Comment by liu-cong** [comment]
For watching file changes, can also use https://github.com/fsnotify/fsnotify. This is what kubernetes uses,  see [1](https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/pkg/util/filesystem/watcher.go#L20)

**Comment by yolocs** [comment]
> For watching file changes, can also use [fsnotify/fsnotify](https://github.com/fsnotify/fsnotify). This is what kubernetes uses, see [1](https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/pkg/util/filesystem/watcher.go#L20)

I think both micro-go/config and viper use fsnotify behind the scene :)
