### ISSUE TITLE
This should be a method on the type.

### ISSUE THREAD

**Issue by n3wscott** [google/knative-gcp#67]
This should be a method on the type.

_Originally posted by @grantr in https://github.com/GoogleCloudPlatform/cloud-run-events/pull/35_

**Comment by n3wscott** [comment]
Ref: https://github.com/GoogleCloudPlatform/cloud-run-events/pull/35#discussion_r298767429

I am not sure it should be. If it was on the type then you can't reuse the method logic. It should be part of the reconciler SDK on a RuntimeObject.

**Comment by nachocano** [comment]
/close
currently not a method on the type.. using the same as eventing, so that we can benefit from the reconciler code-gen that is coming soon
