### ISSUE TITLE
Use Semantic.DeepEqual here, not cmp.Diff. cmp.Diff is meant for tests. https://github.com/google/go-cmp

### ISSUE THREAD

**Issue by n3wscott** [google/knative-gcp#68]
Use Semantic.DeepEqual here, not cmp.Diff. cmp.Diff is meant for tests. https://github.com/google/go-cmp

_Originally posted by @grantr in https://github.com/GoogleCloudPlatform/cloud-run-events/pull/35_

**Comment by akashrv** [comment]
@n3wscott @grantr  Wouldn't it have been easier to either fix this, or resolve the comment in the PR rather than create an issue and add to tech debt?
