### ISSUE TITLE
updateFinalizers should use update

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#70]
This code seems unnecessary. `updateFinalizers` is only called if we changed the finalizers during reconcile. IIUC the only thing this is protecting against is if something else changes the object while we reconciled, but we can let the patch fail and try again, right?

_Originally posted by @grantr in https://github.com/GoogleCloudPlatform/cloud-run-events/pull/35#discussion_r298767037_

**Comment by akashrv** [comment]
@grantr @n3wscott Will this be fixed or close the issue?

**Comment by nachocano** [comment]
/close
leave it as is so that we can benefit from the reconciler code-gen that is coming soon
