### ISSUE TITLE
Write tests for pubsub adapter

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#71]
Stub tests need to be filled in: https://github.com/GoogleCloudPlatform/cloud-run-events/pull/66/files#diff-e4aeeba1df8e80967ec05b8535f5d297

**Comment by akashrv** [comment]
@grantr please verify and update the issue

**Comment by grantr** [comment]
Unit tests for the pubsub adapter are now in https://github.com/google/knative-gcp/blob/master/pkg/pubsub/adapter/adapter_test.go. They are all stub tests.
