### ISSUE TITLE
Topic reconciler checks for existence with the wrong name

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#712]
**Describe the bug**
This call should be using the topic name given in the Topic spec as argument, but it's using the ProjectID instead:
https://github.com/google/knative-gcp/blob/45d9dbd44358730aa34474225fa2969c12ff1d43/pkg/reconciler/pubsub/topic/topic.go#L127

Since the existence check is checking for the wrong topic, the reconciler will always attempt to create the topic. This works because we have error handling for this case:

https://github.com/google/knative-gcp/blob/45d9dbd44358730aa34474225fa2969c12ff1d43/pkg/reconciler/pubsub/topic/topic.go#L142-L144

Maybe this comment can be removed and the logic simplified when this bug is fixed.

 **Expected behavior**
The topic reconciler checks for the existence of a topic before trying to create it.

 **To Reproduce**

 **Knative-GCP release version**
0.13.0

**Additional context**
This bug was introduced in #419. The previous operation-based reconciler was correct:

https://github.com/google/knative-gcp/blob/d02c888d059ec547a3812538214aa19deb321b35/pkg/operations/pubsub/topic.go#L130

/cc @nachocano

**Comment by nachocano** [comment]
oops! Thanks Grant, let me fix this and clean up some unnecessary stuff as well

/assign
