### ISSUE TITLE
Include cluster name in k8s Service Account name for Workload Identity

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#715]
**Describe the bug**
When enable Workload Identity, reconciler will create a k8s Service Account, the k8s SA's name is the same as corresponding Google Cloud Service Account. 
https://github.com/google/knative-gcp/blob/45d9dbd44358730aa34474225fa2969c12ff1d43/pkg/reconciler/identity/resources/service_account.go#L31

More details about reconciler logic for workload identity: https://github.com/google/knative-gcp/blob/master/docs/install/pubsub-service-account.md

It is better to make k8s SA use name like googleServiceAccount + cluster name.
We can use `cluster, _ := metadata.InstanceAttributeValue("cluster-name")` to get cluster name, and clusterName is also an optional value in `ObjectMeta`.

 **Expected behavior**
Include cluster name in k8s Service Account name for Workload Identity

**Comment by grantr** [comment]
> clusterName is also an optional value in ObjectMeta

Thanks for pointing this out @grac3gao! That gave me an idea that we should set this automatically in the webhook for all objects. Opened #735 for that.

**Comment by grac3gao** [comment]
It would be better to fix #735 together with this issue. If #735 is fixed, which means all cloud run resources on GKE would have a default non-empty metadata.clusterName, then we can only use `ObjectMeta.getClusterName()` to get cluster name.
