### ISSUE TITLE
Issues with workload identity install docs

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#719]
**Describe the bug**
Following the readme, I ran into these issues:

### Paths in commands
`controller-gke.yaml` is in `config/core/deployments` so the command `ko apply -f controller-gke.yaml` should include the directory from the repo root.

The `init_control_plane*` scripts are in the `hack` directory, so the commands to run them should be prefixed with `hack/` rather than `./`.

### gcloud configuration dependency

The `init_control_plane_gke.sh` script fails if the cluster is not in the gcloud configured zone:

```sh
 $ hack/init_control_plane_gke.sh
Operation "operations/acf.10358169-34c2-481f-85cc-e874e790cc93" finished successfully.
Operation "operations/acf.88e79cc0-eea7-4ea9-b197-c55b589c5a5e" finished successfully.
WARNING: Problem loading details of cluster to update:

ResponseError: code=404, message=Not found: projects/grantrodgers-knative-dev/zones/us-central1-b/clusters/gcpbroker-1.
Could not find [gcpbroker-1] in [us-central1-b].
Did you mean [gcpbroker-1] in [us-west1-c]?
```
In this case gcloud was configured for us-central1-b, but my cluster was in us-west1-c. I had to change the gcloud config to be us-west1-c. This is fine but it should be mentioned in the docs.

### pre-existing service account

I already had a `cloud-run-events` service account in my project. This generated errors in the `init_control_plane_gke.sh` script, which may be safe to ignore, but the script doesn't tell me. Ideally the script would be idempotent so this wouldn't be an issue, but maybe that's difficult.

```
ERROR: (gcloud.iam.service-accounts.create) Resource in project [grantrodgers-knative-dev] is the subject of a conflict: Service account cloud-run-events already exists within project projects/grantrodgers-knative-dev.

...

error: --overwrite is false but found the following declared annotation(s): 'iam.gke.io/gcp-service-account' already has a value (cloud-run-events@grantrodgers-knative-dev.iam.gserviceaccount.com)
```

I got a similar error on running `init_control_plane.sh`, which would presumably be encountered by everyone who runs both of these scripts:
```
ERROR: (gcloud.iam.service-accounts.create) Resource in project [grantrodgers-knative-dev] is the subject of a conflict: Service account cloud-run-events already exists within project projects/grantrodgers-knative-dev.
```

 **Expected behavior**
No errors when following the instructions, or documentation of common errors encountered and what to do about them.

 **To Reproduce**
Create a cluster and follow the workload identity instructions.

 **Knative-GCP release version**
HEAD

 **Additional context**

**Comment by grac3gao** [comment]
Thank you! @grantr, you might be the first user for this updated install doc:) I'll address those comments.
