### ISSUE TITLE
Why is this `PROJECT_ID` and not `PROJECT`?

### ISSUE THREAD

**Issue by n3wscott** [google/knative-gcp#72]
Why is this `PROJECT_ID` and not `PROJECT`?

_Originally posted by @grantr in https://github.com/GoogleCloudPlatform/cloud-run-events/pull/35/files/b43fb10e9247b0db8e1abd323dc4814609315d1b_

**Comment by akashrv** [comment]
@n3wscott Do you intend to change it or close the issue?
