### ISSUE TITLE
Default metadata.clusterName for all cloud run resources on GKE

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#735]
**Problem**
When we create GCP resources like PubSub Topics for objects in the cluster, it would be useful to use the cluster name as part of the GCP resource name. This helps with name uniqueness (technically Kubernetes object UIDs aren't unique across clusters) and helps users more easily find the resources associated with a cluster or object.

As @grac3gao points out in #715, the GKE metadata contains the cluster name and that's accessible from the pod. ObjectMeta also includes a `clusterName` field. We can use these features to automatically set cluster name for any object in a defaulting webhook, allowing controllers to use it for resource names. Both the webhook and the controller must consider this optional so they still work outside GKE. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Contributor, User

**Exit Criteria**
A controller can create a GCP resource with a name or label containing the cluster name.

**Time Estimate (optional):** 
3

**Additional context (optional)**

**Comment by grantr** [comment]
cc @Harwayne who pointed out the Kubernetes UID guarantees.

**Comment by liu-cong** [comment]
It seems that customers can disable the metadata access: https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata

It's worth confirming this.

**Comment by grac3gao** [comment]
@liu-cong for the link you provided about customers can disable the metadata access, are you referring to the section [Metadata concealment](https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata#concealment)?

**Comment by liu-cong** [comment]
Metadata concealment seems to be most relevant. But as long as we make this
optional, doesn't seem to be a big issue.

**Comment by grac3gao** [comment]
Looks like Metadata concealment will be deprecated, and they recommend to use workload identity instead of metadata concealment…the latest gcloud SDK stops providing the flag to create a cluster with metadata concealment enabled cluster. I guess it will prevent pod getting metadata information by not giving the specific Google Service Account permission like `compute.instances.get`

By the way, we use `metadata.ProjectID()`(
https://github.com/google/knative-gcp/blob/master/pkg/utils/metadata.go )
to get project ID and set it to status in several controllers, I am not sure whether this will affect users who are running cluster outside GKE?

**Comment by liu-cong** [comment]
Our binaries should take a PROJECT_ID env var for specifying the project.
This env var should always be set outside of GKE (GCE).

**Comment by grantr** [comment]
@grac3gao mentioned today that the apiserver ignores this field in create and update requests. There's some background at https://github.com/kubernetes/kubernetes/issues/65885. We'll probably have to use an annotation instead of `metadata.clusterName`.

**Comment by grac3gao** [comment]
@grantr I was wondering which way will be better, adding an annotation, or adding a ClusterName field under spec (maybe under the IdentitySpec)?

**Comment by grantr** [comment]
I think once #950 gets in, we can close this issue as fixed and create followup issues for adding the functionality from #950 to additional resources.
