### ISSUE TITLE
Simplify e2e tests setup scripts

### ISSUE THREAD

**Issue by chizhg** [google/knative-gcp#738]
**Problem**
In [e2e-common.sh](https://github.com/google/knative-gcp/blob/master/test/e2e-common.sh), there are a lot of `gcloud` commands to configure the authentication mechanism. These are only used when users run the scripts on their local, and there is no way to keep them up-to-date.

**Exit Criteria**
Since it's a one-time setting for running it locally, we should direct users to run [./hack/init_control_plane.sh](https://github.com/google/knative-gcp/blob/master/hack/init_control_plane.sh) and [./hack/init_control_plane_gke.sh](https://github.com/google/knative-gcp/blob/master/hack/init_control_plane.sh) instead of creating a new service account every time they run the scripts. Then all these `gcloud` commands in the scripts can be removed.

/assign

**Comment by capri-xiyue** [comment]
I'm working on https://github.com/google/knative-gcp/issues/766. These two issues are related to each other. @chizhg  I will just assign this issue to myself. Let me know if you already make some progress related to this issue.

**Comment by capri-xiyue** [comment]
Closed this because it got fixed in https://github.com/google/knative-gcp/pull/973
