### ISSUE TITLE
Remove skip for channel-based broker related E2E tests of Workload Identity

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#746]
**Problem**
For Workload Identity, E2E tests related on channel with broker, and eventing are currently skipped.

For channel with broker tests, the problem is: https://github.com/google/knative-gcp/pull/709#discussion_r398056790, the solution is https://github.com/google/knative-gcp/pull/709#discussion_r398316358
For eventing tests, the problem is https://github.com/google/knative-gcp/pull/709#discussion_r398052796, the solution is https://github.com/google/knative-gcp/pull/709#discussion_r398313023

Both need some refactor for the existing eventing test lib.
Remove skip after that refactoring.

We only need these to test against the channel-based broker. The GCP broker already tests with workload identity.

**Exit Criteria**
Remove the skip after eventing test lib change.

**Comment by ericlem** [comment]
Low priority since it's for the channel based broker.
