### ISSUE TITLE
Small E2E test that runs a test after an upgrade

### ISSUE THREAD

**Issue by ericlem** [google/knative-gcp#749]
**Problem**
We want to have upgrade tests that ensure that the systems works during and after upgrade.  As a stepping stone to get there, we'll start by doing an install/upgrade and then running basic tests to ensure the system works AFTER the upgrade.

**Exit Criteria**
This would install the last official gcp release, upgrade to the current head eventing and gcp code (using a method as close as possible to the expected actual upgrade path), and then runs a test.

**Comment by nlopezgi** [comment]
closing as we now have upgrade tests in this repo
