### ISSUE TITLE
Workload Identity has delay in receive-adapter

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#759]
**Describe the bug**
After Workload Identity reconciled for a source in the data plane (create a k8s Service Account, set iam policy binding as WorkloadIdentityUser to the GoogleServiceAccount with the K8s ServiceAccount, annotate the k8s ServiceAccount), the source will mark ready after topic, pullsubscription and other condition are all marked ready. 

But the receive-adapter will continue with error state for about 1min, error message is `Unable to generate token; IAM returned 403 Forbidden: The caller does not have permission`, which looks like it didn't get that policy binding.

There is a delay for the workload identity functionality working in the receive-adapter pod. During this 1min delay, user can publish message (the publisher doesn't have this issue, the publisher permission is given by the controller?), but they need to wait for 1 min to receive that message. When the receive-adapter is in error state, if you check the GoogleServiceAcount's iam policy, you'll find the role is already bound, and the k8s service account annotation is also there. Thus, it might be the cold start time for the workload identity to put a new member into this project's workload identity pool. If this GSA is already used for other sources in the same namespace, then the newly applied source will not have this problem, as they are using same ksa and bindings.

I was wondering if the source's ready status condition should also check the receive-adapter's state in this case, so that user will not sent message when receive-adapter is in error state? Would like to hear about opinions for how to deal with this.

Also, this makes me think about the initial condition when enabling control plane's Workload Identity. It also needs to wait for 1 min at the beginning, I'll check that.

**Comment by grac3gao** [comment]
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#deployment-status

Deployments have this condition that we can check to see if minimum replicas are ready:
- lastTransitionTime: 2016-10-04T12:25:42Z
    lastUpdateTime: 2016-10-04T12:25:42Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"

**Comment by grac3gao** [comment]
For the control plane, because we have that 1 min delay, once the control plane is enabled WI, user need to wait for 1 min to apply resources. Otherwise, resources will still fail for permission issue. 
If the user apply resources before configuring any credential in control plane, after configuring WI, restarting controller immediately will not lead to reconcile resource successfully. It will still fail for the first 1 min, and because of exponential back off, usually need to wait for 5 min reSync time to make such resource ready. (Restarting controller help resource become ready immediately when using secret)

**Comment by yolocs** [comment]
@capri-xiyue Do you know if this is fixed as described in https://github.com/google/knative-gcp/issues/759#issuecomment-608619710?

**Comment by grac3gao** [comment]
@capri-xiyue could you confirm if currently, the source's condition will also reflect underlying receiver-adaptor's deployment status? based on your PR https://github.com/google/knative-gcp/pull/1339

**Comment by capri-xiyue** [comment]
@grac3gao  Yep. Currently, the source's condition will reflect underlying receiver-adaptor's deployment status.

**Comment by grac3gao** [comment]
#1339 fixed this
