### ISSUE TITLE
Modify init_scripts of knative-gcp so that they can run multiple times(Idempotence)

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#766]
**Problem**
Currently, we have several init_scripts for example (https://github.com/google/knative-gcp/blob/master/hack/init_control_plane_gke.sh and https://github.com/google/knative-gcp/blob/master/hack/init_control_plane.sh). However, usera can only run it one time.  
I just found it's quite inconvenient if something goes wrong in the script but it doesn't support running for multiple rounds.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
The init scripts can run multiple times(Idempotence) 
**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by ericlem** [comment]
I'll see if i can get to any of this during upgrade work.  It would be useful there.
/assign

**Comment by capri-xiyue** [comment]
Once we make init_control_plane.sh,init_control_plane_gke.sh, init_data_plane.sh idempotent so they can be run as part of e2e test setup process.

**Comment by capri-xiyue** [comment]
This is related to https://github.com/google/knative-gcp/issues/738

**Comment by capri-xiyue** [comment]
Closed this because it got fixed in https://github.com/google/knative-gcp/pull/973
