### ISSUE TITLE
Add integration test for broker ingress

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#786]
**Problem**
Prepare pubsub topics, start ingress, send events to it, and pull events from pubsub to verify.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment]
Why have a separate integration test for the ingress component:
- Easier to test locally
- Easier to identify a bug in a single component
