### ISSUE TITLE
googleServiceAccount not recognized during CloudPubSubSource creation

### ISSUE THREAD

**Issue by ethai** [google/knative-gcp#787]
**Describe the bug**

I'm unable to create my CloudPubSubSource object when I include the googleServiceAccount in my manifest.  

```javascript


apiVersion: events.cloud.google.com/v1alpha1
kind: CloudPubSubSource
metadata:
  name: cloudpubsubsource-transactions
spec:
  googleServiceAccount: MY_GSA
  project: MY_PROJECT
  topic: transactions
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Broker
      name: default

```

The error I'm getting is 

admission webhook "webhook.events.cloud.google.com" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "googleServiceAccount"

 **Expected behavior**

The pubsub object should be created

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative-GCP release version**

v0.13.0

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by grac3gao** [comment]
`googleServiceAccount` is newly added, and used to be named as `serviceAccount`. This issue might be caused by an old version of knative-gcp. Could you try `ko apply -f ./config` to update the latest knative-gcp to see if that solves the problem.

**Comment by ethai** [comment]
I tried with the latest knative-gcp 0.13.1 and am still seeing the same error

**Comment by ethai** [comment]
Hi, I'm looking at the CRD in the latest yaml and I believe the problem is that CloudPubSubSource doesn't even accept the googleServiceAccount property and only supports 'secret'

**Comment by grac3gao** [comment]
Oh, I didn't notice you are using v0.13.0 release version. v0.13.0 release doesn't include this functionality, if you want to use `googleServiceAccount` now, you need to fetch the latest master branch of knative-gcp repo and apply `ko apply -f ./config` in the current master branch (instead of install a release). This functionality is only in the current master branch.

**Comment by ethai** [comment]
so in short does this mean the 'release' install essentially supports secrets and not workload identity?

**Comment by grac3gao** [comment]
v0.13.0 release doesn't include WI, as WI is a newly added functionality. This doesn't mean future release would not include it. But currently, if you use release to install Knative-GCP, WI is not supported.

**Comment by ethai** [comment]
perfect and thanks - closing thread as i'll workaround with secret
