### ISSUE TITLE
Pubsub topic push fails forever if first attempt to create/open topic fails

### ISSUE THREAD

**Issue by ericlem** [google/knative-gcp#796]
**Describe the bug**
Pubsub publisher returns an error of the form "unable to create topic XXX, <nil>" for all pub sub publish attempts after hitting an error during initial pubsub connection creation in some circumstances.  It can be recovered by restarting the pod.

 **Expected behavior**
Errors are returned by publish calls while the underlying pub sub creation/get API's return errors, but publishes succeed soon after the underlying error goes away.
 
 **Additional context**
It's quite likely that the underlying problem is in and should be fixed in the cloudevents sdk pubsub transport.

Initial indications are that the issue involves the function getOrCreateTopic in v1/cloudevents/transport/pubsub/internal/connection.go

This function attempts to create the connection inside a sync.Once() block, returning failure on subsequent calls if the connection wasn't created.  This logic probably needs to be fixed.  We might also switch to the v2 version of the API, but in any case need to make sure that the v2 code doesn't have a similar issue.

**Comment by grantr** [comment]
This is a bug in the SDK's PubSub transport so it affects the broker as well.

**Comment by ericlem** [comment]
This is being worked on here: https://github.com/cloudevents/sdk-go/issues/472

**Comment by ericlem** [comment]
I fixed this upstream in cloudevents.  Will be fixed when we pull in cloudevents v2-rc2

**Comment by ericlem** [comment]
The fix has been pulled in/fixed.
