### ISSUE TITLE
Migrate to cloudevents sdk-go v2

### ISSUE THREAD

**Issue by ian-mi** [google/knative-gcp#800]
**Problem**
Now that v2.0.0-RC1 has been released, knative-gcp should begin migrating the v2 of the cloudevents SDK.

**Exit Criteria**
All v1 dependencies have been removed.

**Time Estimate (optional):** 
1w

**Comment by grantr** [comment]
This is done for gcp broker.

**Comment by grantr** [comment]
@Harwayne @ian-mi do you know if this is completed for sources and channels in this repo?

**Comment by Harwayne** [comment]
I believe #1481 fixed this. @ian-mi please re-open if I am incorrect.

/close
