### ISSUE TITLE
TestBrokerTracing - Flaky

### ISSUE THREAD

**Issue by Harwayne** [google/knative-gcp#818]
**Describe the bug**
`TestBrokerTracing` has been very flaky recently in prow (anecdotally, failing >75% of the time). 

 **Expected behavior**
The test should consistently pass.

**Exit Criteria**
Running the test via Prow succeeds 20 times in a row.

 **To Reproduce**
Remove the ignore for the test and run it through prow repeatedly.

**Comment by grantr** [comment]
This is only about the pubsub broker tests - the gcp broker tracing tests have their own issue.

**Comment by capri-xiyue** [comment]
FYI: Logs of prow
https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/google_knative-gcp/784/pull-google-knative-gcp-integration-tests/1248388433005514752/

**Comment by Harwayne** [comment]
TestChannelTracing tests the Channel. And we have separate tests for GCP Broker tracing. So this is no longer needed at all.
