### ISSUE TITLE
Decide how triggers should be reconciled if their broker doesn't exist

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#828]
**Describe the bug**
Currently a trigger is only reconciled if its broker exists. A trigger created before a broker, or more importantly a trigger that still exists after its broker is deleted, will never be reconciled. This is an issue for gcp triggers because those triggers need to be finalized, so deleting a trigger when its broker doesn't exist causes it to hang forever because its finalizer will never be removed. It's also a bad user experience for a trigger with no existing broker to never get a status or to have a stale status.

 **Expected behavior**
Triggers are reconciled and have a status that remains current even if their broker doesn't exist.

 **To Reproduce**
1. Create a trigger pointing to a broker that doesn't exist
1. Observe Trigger never gets a status
1. Create the broker
1. Observe trigger gets a status and topic/sub
1. Delete the broker
1. Delete the trigger
1. Observe trigger is never deleted

 **Knative-GCP release version**
HEAD

 **Additional context**
This is an issue in the two brokers in knative eventing also, but since they don't have finalizers it only causes stale trigger statuses.

**Comment by grantr** [comment]
https://github.com/knative/eventing/issues/2996 now tracks this issue in Eventing

**Comment by grantr** [comment]
This is slightly more complicated than originally stated. There is no such thing as a "gcp trigger". The trigger only gets a broker class through its broker, so a trigger created before its broker exists has no broker class, and (currently) no controller that can update its status.

Furthermore, a trigger pointing to a broker that no longer exists may have resources related to that broker's broker class but the trigger itself has no knowledge of its broker class.

**Comment by grantr** [comment]
First step is to come up with a solution to solve this for both trigger creation and broker deletion.

**Comment by grantr** [comment]
It looks like https://github.com/knative/eventing/issues/2996 has determined that webhooks can't set any values in status (the apiserver clears status during create). So what we'll need to do for Triggers created before brokers is add a status to them in a controller. There might be some race conditions with this, but probably not anything that disrupts ultimate convergence (and correctness).

When we have access to crd/v1 we can set default values on status, which is effectively the same as the webhook defaulting solution, but it's not supported in GKE yet.

**Comment by liu-cong** [comment]
I brought this up in the Eventing WG meeting and the general thoughts are: 1. Broker should stop accepting events once deleted; 2. Broker can attempt to deliver undelivered events but no guarantee will be specified in the spec. Will continue to collect opinions in the issue: https://github.com/knative/eventing/issues/3130

For now events will be dropped once a Broker is deleted (current behavior). I think no event loss guarantee could be a differentiator for GCP Broker to consider in the future, but that has to be verified by real use cases :)
