### ISSUE TITLE
E2E test new broker and receives/forwards an event

### ISSUE THREAD

**Issue by ericlem** [google/knative-gcp#837]
**Problem**

Add a very basic E2E tests to start up a new gcp broker, send an event, and make sure it is received as a first test at integrating the new broker into E2E tests.

This test should essentially be a copy of test/e2e/BrokerWithPubSubChannelTestImpl with a new
helper function equivalent to createBrokerWithPubSubChannel that can be used to create the
new style broker.  

This will also have to add a step to install yaml files to configure and deploy the control plane and shared data plane components of the new broker.

**Exit Criteria**
A new test that performs the same actions as BrokerWithPubSubChannelTestImpl on
the new gcp broker.

**Time Estimate (optional):** 
5

**Additional context (optional)**
This will rely on a set of yaml's being produced that can be installed to configure the control and data planes of the new broker.

**Comment by grantr** [comment]
There's some overlap here with #639, currently assigned to @capri-xiyue. @ericlem does this seem like a sub-task of #639?
