### ISSUE TITLE
Add .Logf() calls to test/lib helpers

### ISSUE THREAD

**Issue by ericlem** [google/knative-gcp#839]
**Problem**
Tracking down failures in E2E tests has proven time consuming.  Information about the state of the system at the time of failure is useful.  As an experiment, we should try instrumenting a lot
of the functions in test/lib with basic .Logf() calls to record both failed and successful operations.
This would make it easier to determine from logs(without looking at code) that (for instance) creation of a broker succeeded, but creation of the trigger didn't, or that X attempts were made to check that a service was up before failing.

**Exit Criteria**
all functions in test/lib that have access to the appropriate Testing structure (and aren't expected to be called in tight loops) have .Logf() calls indicating what they were called to do and the success or failure of the call (failure may be indicated by an existing Fatalf/Errorf if it exists)

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment]
Recommend calling `t.Helper()` as well
