### ISSUE TITLE
Flaky E2E tests related to Cloud Audit Logs

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#842]
**Describe the bug**
`TestCloudAuditLogsSource` is kind of flaky. It is related to the SLO of CloudAuditLogsSource.
CAL source misses the CloudAuditLogs which gets created shortly after CAL source becomes ready( https://github.com/ian-mi/knative-gcp/pull/2#pullrequestreview-333515256).
The error logs of prow looks as follows: https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/google_knative-gcp/784/pull-google-knative-gcp-integration-tests/1248021891256422401/

 **Expected behavior**
The test should consistently pass.

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative-GCP release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by grantr** [comment]
This is less flaky than it used to be, but still a bit flaky.

**Comment by capri-xiyue** [comment]
@ian-mi All E2E tests related to CAL is still flaky. I investigated the logs, the root cause of that CAL fails to emit a event even though it shows it's ready. Can you help investigate it to see how we can fix it?

**Comment by nlopezgi** [comment]
Closing as this is old. Please open a new bug if seen again
