### ISSUE TITLE
#2 GCP broker controller doesn't recreate decouple topic if it's deleted

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#843]
**Describe the bug**

 **Expected behavior**

 **To Reproduce**
Create a broker, make sure decouple topic is created. Delete the topic manually. Wait for 5 min (I believe this is the global resync period? I waited 20min), the topic is not recreated.

 **Knative-GCP release version**

**Time Estimate (optional):**
2

 **Additional context**
Maybe the global resync is not enabled? I don't see any logs in the controller. Re-deploy the controller will recreate the topic.

cc @grantr

**Comment by grantr** [comment]
Fixed in #739
