### ISSUE TITLE
Failure to delete topic/sub on broker deletion cancels targets update

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#873]
**Describe the bug**
As mentioned by @ian-mi in https://github.com/google/knative-gcp/pull/739/files#r407860969, if topic deletion fails during Broker finalize, the targets config is not updated in that reconcile pass.

 **Expected behavior**
The targets config should make as much progress toward the current cluster state as possible even when reconcile fails.

 **To Reproduce**
Theoretical repo:
1. Delete broker
1. Delete the broker's topic between when the controller checks if the topic exists and attempts to delete it (likely impossible in practice)

**Comment by grantr** [comment]
@liu-cong this may be fixed by #1280

**Comment by liu-cong** [comment]
Yes this should be fixed by @1280. Added this issue to the PR description.
