### ISSUE TITLE
Support liveness probes in broker ingress

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#882]
**Problem**
- Related to #785. 
- serve health and readiness endpoints
- Also add probes in the deployment yamls (or the BrokerCell controller if it replaces the yaml)

Ref: https://blog.colinbreck.com/kubernetes-liveness-and-readiness-probes-how-to-avoid-shooting-yourself-in-the-foot/

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**

**Comment by grantr** [comment]
How to test:
- Unit tests that verify endpoints are being served and accurate
- E2E test that verifies when ingress pods change state the broker readiness changes. How do we force a change in the broker readiness?

Let's first investigate how to test these probes in E2E tests.
