### ISSUE TITLE
Refactor control plane init scripts to avoid error message

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#896]
**Problem**
`./hack/init_control_plane_gke.sh` or `./hack/init_control_plane.sh` will print an error message if the script is trying to create the `cloud-run-events` GSA if it already exists. Though in our installation docs, we have a note explaining this is a safe error, it can still be scary especially for a first time user.

This is also brought up in PR review: https://github.com/google/knative-gcp/pull/894#discussion_r411508201

Ideally, the script should:
* Check if the GSA exists, if so, skip creating it

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by capri-xiyue** [comment]
Close this because it got fixed in https://github.com/google/knative-gcp/pull/973
