### ISSUE TITLE
State Transition Testing for knative-gcp

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#908]
**Problem**
Tests include how the status of resources change from negative path to happy path and from happy path to negative path. Such tests can help us 
verify how we handle the error messages of underlying implementation correctly
verify the reconciler time needed.
It should include knative-gcp resources like:

- Broker
- Source
- Trigger
- Channel

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**

Create a list of tests that we need to perform prior to release in a document.  These tests can be tests that are automated, or manual (with a goal to eventually move them to automated tests).

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment]
Break this down into multiple tasks.

P1: determine what tests should be run. Exit criteria: document in manual testing guide.

P2: automated tests.

**Comment by capri-xiyue** [comment]
Just wanna clarify, this State Transition Testing is not to verify exactly how long the reconcile needs. Just work as a relaxing boundary(For example, in 3 mins, the reconcile should happen)

**Comment by ericlem** [comment]
Try to timebox the effort to get a best effort within the time provided.

**Comment by capri-xiyue** [comment]
[Docs for the State Transition Testing](https://docs.google.com/document/d/1-I26hHg1KxAuOW9CxWNTBmHz-qAlb5CZInDhR0OdQ20/edit?usp=sharing)
