### ISSUE TITLE
Test deletion of sources also deletes GCP resources

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#909]
**Problem**
We need to verify sources get created and get deleted correctly
For example, when we delete a cloudstoragesource, all the underlying pull subscriptions and topic etc. should also get deleted

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
Smoke Testing for knative-gcp of 4 sources(pubsub, storage, scheduler, auditlogs)

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment]
Creation is probably covered by existing e2e tests. Deletion is not covered.

**Comment by capri-xiyue** [comment]
I separated the original issue into two issues.
This issue will focus on sources and https://github.com/google/knative-gcp/issues/1165 will focus on gcp broker
