### ISSUE TITLE
Add unit test for gcp broker fanout service

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#910]
**Problem**
Add integration test for gcp broker fanout service. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment]
@yolocs have you worked on this already?

**Comment by yolocs** [comment]
No. I only have unit test that runs with test pubsub server and test http server.

**Comment by capri-xiyue** [comment]
Just wanna clarify, what I actually mean is a unit tests without a local cluster(Based on my understanding, I think our unit tests in knative-gcp is more like a integration tests, that's why I call it integration tests here, sorry for the confusion)

**Comment by grantr** [comment]
@capri-xiyue thanks for clarifying. Does the unit test that @yolocs mentions, with test http and pubsub servers, satisfy this issue?

**Comment by yolocs** [comment]
I think it's already there. @capri-xiyue Let me know what you think is missing.

**Comment by capri-xiyue** [comment]
Closed since it's already fixed
