### ISSUE TITLE
BrokerCell watch ingress endpoints and update READY status immediately

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#912]
**Problem**
Currently broker controller relies on the 5min global resync to update broker status if ingress endpoint status changes. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
* Broker status changes immediately as its ingress endpoint status changes.
* Is unit test/integ test applicable?

**Comment by grantr** [comment]
https://github.com/google/knative-gcp/blob/b2bd566ad841eecd499bdc843c537b04dcadaef5/pkg/reconciler/broker/controller.go#L129-L133

This will probably be part of the BrokerCell work.

**Comment by grantr** [comment]
It will be hard to write a unit test that verifies the informer is triggering a reconcile. We can write a state transition E2E test to verify that the readiness changes.

**Comment by grantr** [comment]
Switching to BrokerCell controller since BrokerCell owns ingress endpoints now.
