### ISSUE TITLE
Broker retry service needs to avoid re-filtering if trigger has not changed

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#918]
**Problem**
Based on the decision of #906, as a future optimization, broker retry service needs to avoid re-filtering if trigger has not changed

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment]
Priority clarification for triage: This issue requests a performance optimization that is not needed for correctness. #917 adds filtering to retry and is needed to ensure correctness. #917 is higher priority.
