### ISSUE TITLE
Failed to run e2e-tests.sh with E2E tests related to CloudSchedulerSource

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#924]
**Describe the bug**
When I ran `E2E_PROJECT_ID=$PROJECT_ID test/e2e-tests.sh`,
All E2E tests related to CloudSchedulerSource failed.
- --- FAIL: TestCloudSchedulerSourceBrokerWithPubSubChannel 
- --- FAIL: TestSmokeCloudSchedulerSourceSetup
- --- FAIL: TestCloudSchedulerSourceWithTargetTestImpl

It looks like these E2E tests failed because of the lack of app engine. We didn't set up the creation of app engine with correct time zone in our https://github.com/google/knative-gcp/blob/master/test/e2e-common.sh.
We need to fix it. Also need to figure out why E2E tests passes in prow.

 **Expected behavior**
All E2E tests pass when running command`E2E_PROJECT_ID=$PROJECT_ID test/e2e-tests.sh` 

 **To Reproduce**
Run `E2E_PROJECT_ID=$PROJECT_ID test/e2e-tests.sh` 
 **Knative-GCP release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by capri-xiyue** [comment]
This issue can be combined with https://github.com/google/knative-gcp/issues/766 and https://github.com/google/knative-gcp/issues/738

**Comment by grantr** [comment]
This only happens when running tests on an existing cluster. Prow projects already have app engine setup.

**Comment by capri-xiyue** [comment]
> This only happens when running tests on an existing cluster. Prow projects already have app engine setup.

To clarify,  this happens when we fail to create app engine and use `go test` on an existing cluster or when we run e2e with `test/e2e-tests.sh` directly which will creates a new cluster

**Comment by capri-xiyue** [comment]
Closed this because it got fixed in https://github.com/google/knative-gcp/pull/973
