### ISSUE TITLE
GCP Broker e2e  Performance Tests

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#929]
**Problem**

There are already some examples in channel based broker. We should be able to reuse most of the components.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment]
Duplicate of #981
