### ISSUE TITLE
GCP Broker Component Level Benchmarks

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#930]
**Problem**
Add micro benchmarks for each component
 * These tests help identify bottlenecks easily
 * Ideally these tests can run locally so developers can use them to find performance improvements/regression
 * Nice-to-haves
   * Enable a command such as /benchmark-broker-ingress in github to trigger a test against a PR. this is a convenient tool to use for any PRs that may affect performance.
   * Run a continuous job and integrate with Mako so we have a history

**Components**
- [x] Delivery Processor #1078
- [x] Ingress Handler #1108 
- [ ] fanout processor
- [ ] filter processor
- [ ] fanout pool
- [ ] retry pool

Note: May be benchmarking the pools will also include the processors. In that case individual benchmarks for the processor can be skipped.

**Comment by yolocs** [comment]
It would be helpful to define "performance". Historically we have latency test in Mako which is only measured by one client seeding events and one subscriber. But that doesn't seem to provide good simulation of the system running under heavy load or with various subscribers (e.g. always returning error, slow response, etc.). I would also imagine a proper simulation would incur quite some cost especially when we run it continuously.
