### ISSUE TITLE
Decide the retry policy for Broker

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#970]
**Problem**
Currently, for broker retry, we use the default receive settings provided by the PubSub lib, (only change the `synchronous` to be true)

The default setting is 
```
var DefaultReceiveSettings = ReceiveSettings{
	MaxExtension:           10 * time.Minute,
	MaxOutstandingMessages: 1000,
	MaxOutstandingBytes:    1e9, // 1G
	NumGoroutines:          1,
}
```

`synchronous=true` will make that: no more than MaxOutstandingMessages will be in memory at one time. MaxOutstandingBytes still refers to the total bytes processed, rather than in memory. NumGoroutines is ignored.

We need to revisit it, and decide the retry policy for Broker.
But before that, probably we need a plan for some performance test, so that we'll have data to review when  making a decision. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
Have a decision for retry policy.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by alexander-alvarez** [comment]
Would this be something that would be configurable?

I'm asking because we ran into an issue recently where we were infinitely retrying a knative function that was throwing 500 errors until the message expired from the topic which can be days depending on how it's configured.

From:
https://pkg.go.dev/cloud.google.com/go/pubsub?tab=doc#Subscription.Receive
> If the service returns a non-retryable error, Receive returns that error after all of the outstanding calls to f have returned. If ctx is done, Receive returns nil after all of the outstanding calls to f have returned and all messages have been acknowledged or have expired.

It seems like this could be avoided by configuring the timeout. Is the timeout something that is exposed (or intending to be exposed)?

**Comment by grantr** [comment]
@alexander-alvarez in your situation, were you hoping to configure a specific trigger to consider status code 500 as non-retryable? Did you want this configuration permanently or temporarily? Did you want it to apply to all triggers or only one trigger?

Is the timeout you'd like to configure the message delivery timeout, or the message expiration timeout (N days)? Would it be sufficient to configure this for all triggers, or would you want to configure a different value for each trigger?

**Comment by alexander-alvarez** [comment]
@grantr 

In the context of our apps 500 errors are most likely non-retryable, so it would likely be a permanent config for all of our triggers (local overrides always welcome). By non-retryable I mean we'd have to do a deployment to fix the downstream code and retry after deploying -- but in the meantime every retry attempt will continue to fail and just cause more noise.

I could be wrong in my tracing of the source, but I believe it's the message delivery timeout (as the message expiration timeout could be configured on the subscription). I'm mostly responding to https://godoc.org/cloud.google.com/go#hdr-Timeouts_and_Cancellation
> By default, all requests in sub-packages will run indefinitely, retrying on transient errors when correctness allows. To set timeouts or arrange for cancellation, use contexts

So if I understand correctly, if we had some sort of timeout it wouldn't run indefinitely?

For the timeout, ideally being able to set a global default with a local trigger override would make sense. We're providing anthos + knative-gcp as a platform for our other internal dev teams, so being able to give them sensible defaults and escape hatches where applicable is the best course of strategy for us.


Let me know if anything is unclear!
