### ISSUE TITLE
Use one single installation script to install knative-gcp and all its dependencies

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#976]
**Problem**
There are some scripts to install things in Knative-GCP (for example https://github.com/google/knative-gcp/blob/master/hack/init_control_plane.sh). However, it's a little confusing because some steps are still in docs and some in scripts. Makes it hard to figure out what to do in what order.
It will be better if we can provide one single installation script to install knative-gcp and all its dependencies like knative-eventing and knative-serving.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
One single installation script to install knative-gcp and all its dependencies like knative-eventing and knative-serving.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by capri-xiyue** [comment]
@grac3gao @grantr

**Comment by meteatamel** [comment]
This can be a starting point: https://github.com/meteatamel/knative-tutorial/blob/master/setup/install-knative-gcp

**Comment by ericlem** [comment]
We will work on this as an intern project
