### ISSUE TITLE
Manual test that can be used to measure broker event loss/unavailability

### ISSUE THREAD

**Issue by ericlem** [google/knative-gcp#977]
**Problem**
We need to show that we are not losing events during upgrade and various other reconfigurations (broker restart, trigger creation, etc, etc).  We want to eventually merge all of that into full fledged E2E tests, but to get the data sooner (and to act as a building block for those future tests) we will first implement a manually runable test.

**Exit Criteria**
Two scripts.
* Start script - Requires that knative eventing already be installed.  Takes as input a namespace and deploys an event sender and receiver pod, returning once the two pods are successfully talking to each other.  
* End script - Run by the user after whatever event they want to test (for instance a manually run upgrade).  This terminates the data send and data receive, waiting for events to drain out of the system for a reasonable period of time (a couple minutes).  This returns the whether there were any events accepted (http 200) by the broker than never made it to the receiver.  It returns whether there were events received at the time the end script was run (ie, whether at least one new event sent after the call to the end script is accepted by the broker and seen by the reciever).  And it returns the period of time from the first broker error message (non 200) and the last error message seen during the run.

To produce this data we will need a pod that sends data (and records what events were successfully or unsuccessfully sent), a pod that receives data (and records what events were received), and has a simple interface to allow the sender to be stopped and queried for this list, and the receiver to be queried for its list.
 

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Comment by ericlem** [comment]
Code written.  Need to run tests.

**Comment by liu-cong** [comment]
It seems that some of these tests can be automated by the probers. And the send/receive tracker code can be useful for our probers. @danyinggu
