### ISSUE TITLE
Include cluster name in Topic and Subscription name for Broker

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#978]
**Problem**
Once PR #950 lands, controller can get clusterName from resource's annotation (if it is running in GKE). 

It would be useful to include cluster name in Topic and Subscription name for Broker, for users can find the resources associated with a cluster more easily.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
Include cluster name in Topic and Subscription name for Broker

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment]
Closing this for now. It's no longer clear this is a good idea and cluster name is kind of hard to get.
