### ISSUE TITLE
What metric to report if request is not an event?

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#982]
**Problem**

Related [discussion](https://github.com/google/knative-gcp/pull/949/files#r416107753)
If a request to ingress is not an event, what metrics should we report?

* Do not report any metrics. That's how channel based broker works today. User has to rely on the logs to know this case.
* Report this metric using the `event_count` metric, but with an `Unknown` event type. This can be a bit odd since there is no event at all in this case. And technically `Unknown` can be a valid event type...
* Report additional metrics like HTTP request_count. This solves the confusion. However, the HTTP request_count metric overlaps with event_count in most cases. Also it's arguably adds complexity for users to understand. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 

**Exit Criteria**
Pick an option from above or propose a new one. Come up with detailed work items to implement the solution. For example, if exporting new metrics, need to add those to metrics PRD.

This issue doesn't involve implementing the solution.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**

cc @ian-mi

**Comment by grantr** [comment]
Related to #1522

**Comment by Harwayne** [comment]
The decision is to report invalid events in the `event_count` metric with the `_invalid_cloud_event_` event type and response code 400.

This is very similar to a suggestion in the initial post:

> * Report this metric using the `event_count` metric, but with an `Unknown` event type. This can be a bit odd since there is no event at all in this case. And technically Unknown can be a valid event type...

But, uses the sentinel type `_invalid_cloud_event_`. Yes, that is technically a valid cloud event, but we already use an allow list to only record certain event types (others are converted to `custom`), so does not actually collide with any existing values. It may confuse users who have an actual event type `_invalid_cloud_event_`, but that seems unlikely.

The decision hinged around the idea that most users will be looking at the `event_count` metric. If we also include HTTP `request_count`, it will be almost entirely redundant information (as the overwhelming majority of requests are expected to be valid events). We also thought about using the empty string as the event type, as it is invalid according to the CloudEvents spec, but decided against it as it is immediately obvious what `_invalid_cloud_event_` represents, whereas the empty string would need to be looked up in documentation.

**Comment by Harwayne** [comment]
/close

#1706 tracks implementation.
