### ISSUE TITLE
PullSubscriptions do not recover from Topic deletion

### ISSUE THREAD

**Issue by Harwayne** [google/knative-gcp#997]
**Describe the bug**
When a `Topic` is deleted, all `PullSubscriptions` pointing to that Topic stop working, permanently. The `PullSubscription` is still marked as Ready=true, but it will not get any new events, ever (any still yet to be processed will still be sent).

 **Expected behavior**
Everything self-heals such that the higher level objects (e.g. `Channel` and `Broker`) work.

 **To Reproduce**
1. Create a PubSub `Channel` and a `Subscription` to that Channel. 
    `kubectl apply -f docs/examples/channel`
1. Wait for them to be Ready=true.
    `kubectl get channel demo`
    `kubectl get subscription demo`
1. Optional. Send an event to the Channel and see that it is sent to the subscriber.
    There is a PingSource pointed at the Channel already, so just wait at least one minute.
    `kubectl logs -l app=event-display`
1. Delete the Channel's `Topic`. 
    `kubectl delete topic cre-demo-chan`
1. See everything get back to Ready=true.
    `kubectl get channel demo`
    `kubectl get subscription demo`
1. Events sent to the Channel will not be sent to the subscriber.
     The PingSource is still sending events every minute, so just wait at least one minute. Notice that there will be no new log entries. 
    `kubectl logs -l app=event-display`
1. Optional. Add a new `Subscription` and see that events are sent to the new subscriber, but not the old one.

 **Additional context**
We likely need our `PullSubscription` reconciler to check the value returned by the GCP API. In particular, look at the PullSubscription's `topic` field. If it is `_deleted-topic_`, then realize there is more work to do.

This seems to be a property of the Pub/Sub API:

```shell
└─( 2 ) ❱❱❱ gcloud pubsub topics create my-topic
Created topic [projects/my-proj/topics/my-topic].

└─( 2 ) ❱❱❱ gcloud pubsub topics describe my-topic
messageStoragePolicy:
  allowedPersistenceRegions:
  - asia-east1
  - asia-northeast1
  - asia-southeast1
  - australia-southeast1
  - europe-north1
  - europe-west1
  - europe-west2
  - europe-west3
  - europe-west4
  - us-central1
  - us-central2
  - us-east1
  - us-east4
  - us-west1
  - us-west2
  - us-west3
  - us-west4
name: projects/my-proj/topics/my-topic

└─( 2 ) ❱❱❱ gcloud pubsub subscriptions create my-sub --topic my-topic
Created subscription [projects/my-proj/subscriptions/my-sub].

└─( 2 ) ❱❱❱ gcloud pubsub subscriptions describe my-sub
ackDeadlineSeconds: 10
expirationPolicy:
  ttl: 2678400s
messageRetentionDuration: 604800s
name: projects/my-proj/subscriptions/my-sub
pushConfig: {}
topic: projects/my-proj/topics/my-topic

└─( 2 ) ❱❱❱ gcloud pubsub topics delete my-topic
Deleted topic [projects/my-proj/topics/my-topic].

└─( 2 ) ❱❱❱ gcloud pubsub subscriptions describe my-sub
ackDeadlineSeconds: 10
expirationPolicy:
  ttl: 2678400s
messageRetentionDuration: 604800s
name: projects/my-proj/subscriptions/my-sub
pushConfig: {}
topic: _deleted-topic_

└─( 2 ) ❱❱❱ gcloud pubsub topics create my-topic
Created topic [projects/my-proj/topics/my-topic].

└─( 2 ) ❱❱❱ gcloud pubsub subscriptions describe my-sub
ackDeadlineSeconds: 10
expirationPolicy:
  ttl: 2678400s
messageRetentionDuration: 604800s
name: projects/my-proj/subscriptions/my-sub
pushConfig: {}
topic: _deleted-topic_
```

**Comment by grantr** [comment]
See also #832 which considers this in the context of gcp broker.

**Comment by grantr** [comment]
This is P1 for Sources, P2 for channels.

**Comment by Harwayne** [comment]
After some discussion, we have determined the minimum bar is that statuses must correctly reflect the state of the world. It would be much better if everything self-heals, but that is not the minimum requirement for this bug (at least the release blocking portion of it). 

For example, if we are in the broken state described above, the status must be Ready=false with an error message directing the user to action. 

---

Some thoughts about possible options:
1. The `PullSubscription` reconciler reads the GCP object and reads the `topic` field. If it is `_deleted-topic_`, then the PullSubscription's status is marked as Ready=false. No additional work is done.
    - Pros:
      - Straightforward to implement.
      - Any events from the old object that were enqueued but not successfully delivered will continue to be attempted until the user takes manual action.
    - Cons
     - All newly sent events to the Topic will not be delivered.
1. The `PullSubscription` reconciler reads the GCP object and reads the `topic` field. If it is `_deleted-topic_`, then the GCP object is deleted and a new one is created. 
    - Pros:
      - Newly sent events to the Topic will be delivered to this PullSubscription.
      - Straightforward to implement.
      - Self heals.
    - Cons
      - Any events from the old object that were enqueued but not successfully delivered are lost.
      - May need to restart the receive adapter Pod.
1. Have `PullSubscription` pin `Topic` while in use. Thus `Topic` can't be deleted while any `PullSubscriptions` point at it.
    - Pros:
      - Prevents the issue while the user is entirely within K8s.
      - No event loss (while the user is entirely within K8s).
    - Cons:
      - User could still delete the Topic inside GCP (e.g. `gcloud pubsub topics delete`) and we still have the same problems. So this solution seems insufficient on its own.

**Comment by grantr** [comment]
We'll break this down into a few issues:
- Accurate readiness for Sources/Channels/Brokers. This is P1/R1.
- Auto-heal for Sources/Channel/Brokers (Ok to lose events in this case) This is P1/R2.

**Comment by liu-cong** [comment]
> Auto-heal for Sources, Channel, Brokers/Triggers (separate issues). (Ok to lose events in this case) This is P1/R2.

Not sure if auto-heal with loss of events is necessarily better than just marking the status and letting the user fix it manually.

**Comment by grantr** [comment]
Removing this from GCP Broker project and area since we now have #1233 and #1235 tracking the status accuracy issue.

**Comment by nachocano** [comment]
My understanding is that we are going with solution 1. 
The PullSubscription reconciler reads the GCP object and reads the topic field. If it is _deleted-topic_, then the PullSubscription's status is marked as Ready=false. No additional work is done.

I believe that is what folks the GCP broker is doing, is that correct @liu-cong ?

**Comment by liu-cong** [comment]
For broker/trigger, we went with option 2, see discussions in https://github.com/google/knative-gcp/issues/1235. The main reason is that pubsub will **drop** events published to a topic if there is no subscription. (we initially thought pubsub will buffer messages)

**Comment by nachocano** [comment]
ohh ok... I haven't had time to work on this today. I assign to @capri-xiyue as she might have cycles tomorrow and I'll be off. 
This might require more work then. @capri-xiyue please sync with @liu-cong .
